/* Auto-generated by LeapLab AppInverter */
(function() {
  'use strict';

  // ── App State ──────────────────────────────────────────────────────────
  var state = {};
  var currentScreen = "Screen1";
  var components = {};

  function showRuntimeError(message) {
    var root = document.getElementById('app-root');
    if (!root) return;
    root.innerHTML = '';
    var box = document.createElement('div');
    box.className = 'startup-error';
    var title = document.createElement('strong');
    title.textContent = 'App failed to render';
    var detail = document.createElement('span');
    detail.textContent = message || 'Unknown runtime error';
    box.appendChild(title);
    box.appendChild(detail);
    root.appendChild(box);
  }

  // ── Native Bridge ──────────────────────────────────────────────────────
  var NativeBridge = {
    showAlert: function(title, message) {
      alert(message);
    },
    showToast: function(message) {
      var toast = document.createElement('div');
      toast.className = 'toast-notification';
      toast.textContent = message;
      document.body.appendChild(toast);
      setTimeout(function() { toast.remove(); }, 3000);
    },
    showListPickerModal: function(elements, callback) {
      var overlay = document.createElement('div');
      overlay.style.position = 'fixed';
      overlay.style.top = '0'; overlay.style.left = '0';
      overlay.style.width = '100%'; overlay.style.height = '100%';
      overlay.style.backgroundColor = 'rgba(0,0,0,0.5)';
      overlay.style.zIndex = '10000';
      overlay.style.display = 'flex';
      overlay.style.flexDirection = 'column';
      
      var modal = document.createElement('div');
      modal.style.backgroundColor = '#fff';
      modal.style.width = '80%';
      modal.style.maxWidth = '400px';
      modal.style.maxHeight = '80%';
      modal.style.margin = 'auto';
      modal.style.borderRadius = '8px';
      modal.style.overflowY = 'auto';
      modal.style.boxShadow = '0 4px 6px rgba(0,0,0,0.1)';

      if (!elements || elements.length === 0) {
        var emptyMsg = document.createElement('div');
        emptyMsg.textContent = 'No elements to pick';
        emptyMsg.style.padding = '16px';
        modal.appendChild(emptyMsg);
      } else {
        elements.forEach(function(item, index) {
          var itemDiv = document.createElement('div');
          itemDiv.textContent = item;
          itemDiv.style.padding = '16px';
          itemDiv.style.borderBottom = '1px solid #eee';
          itemDiv.style.cursor = 'pointer';
          itemDiv.addEventListener('click', function() {
            document.body.removeChild(overlay);
            callback(index, item);
          });
          modal.appendChild(itemDiv);
        });
      }

      var closeBtn = document.createElement('div');
      closeBtn.textContent = 'Cancel';
      closeBtn.style.padding = '16px';
      closeBtn.style.textAlign = 'center';
      closeBtn.style.color = '#4285f4';
      closeBtn.style.fontWeight = 'bold';
      closeBtn.style.cursor = 'pointer';
      closeBtn.addEventListener('click', function() {
        document.body.removeChild(overlay);
      });
      modal.appendChild(closeBtn);

      overlay.appendChild(modal);
      document.body.appendChild(overlay);
    },
    vibrate: function(ms) {
      if (navigator.vibrate) navigator.vibrate(ms || 200);
    },
    openUrl: function(url) {
      window.open(url, '_blank');
    },
    playSound: function(src) {
      try { new Audio(src).play(); } catch(e) {}
    },
    getStorageItem: function(key) {
      try { return localStorage.getItem('leapapp_' + key); } catch(e) { return null; }
    },
    setStorageItem: function(key, value) {
      try { localStorage.setItem('leapapp_' + key, value); } catch(e) {}
    }
  };

  // ── React Native Compatibility Shims ───────────────────────────────────
  // Maps block-generated RN code (navigation, Alert, Vibration) to web APIs
  var navigation = {
    navigate: function(screen) { navigateTo(screen); },
    goBack: function() { closeScreen(); }
  };
  var Alert = {
    alert: function(msg) { NativeBridge.showAlert('Alert', msg); }
  };
  var Vibration = {
    vibrate: function(ms) { NativeBridge.vibrate(ms); }
  };

  // ── Non-Visible Component Shims ────────────────────────────────────────
  function ClockShim(id, props) {
    this.id = id;
    this._timerEnabled = props.TimerEnabled !== undefined ? !!props.TimerEnabled : true;
    this._timerInterval = props.TimerInterval !== undefined ? Number(props.TimerInterval) : 1000;
    this._timerId = null;
    this.updateTimer();
  }
  ClockShim.prototype = {
    get TimerEnabled() { return this._timerEnabled; },
    set TimerEnabled(v) { this._timerEnabled = !!v; this.updateTimer(); },
    get TimerInterval() { return this._timerInterval; },
    set TimerInterval(v) { this._timerInterval = Number(v); this.updateTimer(); },
    updateTimer: function() {
      if (this._timerId) clearInterval(this._timerId);
      if (this._timerEnabled && this._timerInterval > 0) {
        var self = this;
        this._timerId = setInterval(function() {
          if (typeof window[self.id + '_Timer'] === 'function') {
            window[self.id + '_Timer']();
          }
        }, this._timerInterval);
      }
    },
    Now: function() { return new Date(); },
    SystemTime: function() { return Date.now(); },
    MakeInstant: function(text) { return new Date(text); },
    MakeInstantFromMillis: function(m) { return new Date(Number(m)); },
    GetMillis: function(instant) { return (instant instanceof Date ? instant : new Date(instant)).getTime(); },
    AddDays: function(instant, days) {
      var d = new Date(instant);
      d.setDate(d.getDate() + Number(days));
      return d;
    },
    AddHours: function(instant, hours) {
      var d = new Date(instant);
      d.setHours(d.getHours() + Number(hours));
      return d;
    },
    AddMinutes: function(instant, minutes) {
      var d = new Date(instant);
      d.setMinutes(d.getMinutes() + Number(minutes));
      return d;
    },
    AddSeconds: function(instant, seconds) {
      var d = new Date(instant);
      d.setSeconds(d.getSeconds() + Number(seconds));
      return d;
    },
    AddWeeks: function(instant, weeks) {
      var d = new Date(instant);
      d.setDate(d.getDate() + (Number(weeks) * 7));
      return d;
    },
    AddMonths: function(instant, months) {
      var d = new Date(instant);
      d.setMonth(d.getMonth() + Number(months));
      return d;
    },
    AddYears: function(instant, years) {
      var d = new Date(instant);
      d.setFullYear(d.getFullYear() + Number(years));
      return d;
    },
    Duration: function(start, end) {
      return Math.abs(new Date(end).getTime() - new Date(start).getTime());
    },
    DurationToDays: function(dur) { return dur / (24 * 3600 * 1000); },
    DurationToHours: function(dur) { return dur / (3600 * 1000); },
    DurationToMinutes: function(dur) { return dur / (60 * 1000); },
    DurationToSeconds: function(dur) { return dur / 1000; },
    DurationToWeeks: function(dur) { return dur / (7 * 24 * 3600 * 1000); },
    FormatDate: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleDateString(); },
    FormatDateTime: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleString(); },
    FormatTime: function(inst) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleTimeString(); }
  };

  function TinyDBShim(id, props) {
    this.id = id;
    this._namespace = props.Namespace || id;
  }
  TinyDBShim.prototype = {
    get Namespace() { return this._namespace; },
    set Namespace(v) { this._namespace = v; },
    _getKey: function(tag) { return 'tinydb_' + this._namespace + '_' + tag; },
    StoreValue: function(tag, val) {
      try { localStorage.setItem(this._getKey(tag), JSON.stringify(val)); } catch(e) {}
    },
    GetValue: function(tag, fallback) {
      try {
        var v = localStorage.getItem(this._getKey(tag));
        return v === null ? fallback : JSON.parse(v);
      } catch(e) { return fallback; }
    },
    ClearTag: function(tag) {
      try { localStorage.removeItem(this._getKey(tag)); } catch(e) {}
    },
    ClearAll: function() {
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        var keysToRemove = [];
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) keysToRemove.push(key);
        }
        keysToRemove.forEach(function(k) { localStorage.removeItem(k); });
      } catch(e) {}
    },
    GetTags: function() {
      var tags = [];
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) tags.push(key.substring(prefix.length));
        }
      } catch(e) {}
      return tags;
    }
  };

  function NotifierShim(id) {
    this.id = id;
  }
  NotifierShim.prototype = {
    ShowAlert: function(notice) {
      NativeBridge.showToast(notice);
    },
    ShowMessageDialog: function(message, title, buttonText) {
      alert((title ? title + "\n\n" : "") + message);
    },
    ShowChooseDialog: function(message, title, button1, button2, cancelable) {
      var res = confirm((title ? title + "\n\n" : "") + message);
      var choice = res ? button1 : button2;
      var self = this;
      setTimeout(function() {
        if (typeof window[self.id + '_AfterChoosing'] === 'function') {
          window[self.id + '_AfterChoosing'](choice);
        }
      }, 50);
    },
    ShowTextDialog: function(message, title, cancelable) {
      var res = prompt((title ? title + "\n\n" : "") + message);
      var self = this;
      if (res !== null) {
        setTimeout(function() {
          if (typeof window[self.id + '_AfterTextInput'] === 'function') {
            window[self.id + '_AfterTextInput'](res);
          }
        }, 50);
      }
    }
  };

  function SoundShim(id, props) {
    this.id = id;
    this._source = props.Source || props.source || '';
    this._volume = props.Volume !== undefined ? Number(props.Volume) : 1.0;
    this._isLooping = !!props.IsLooping;
    this._audio = null;
  }
  SoundShim.prototype = {
    get Source() { return this._source; },
    set Source(v) {
      this._source = v;
      if (this._audio) this._audio.src = v;
    },
    get Volume() { return this._volume; },
    set Volume(v) {
      this._volume = Number(v);
      if (this._audio) this._audio.volume = this._volume;
    },
    get IsLooping() { return this._isLooping; },
    set IsLooping(v) {
      this._isLooping = !!v;
      if (this._audio) this._audio.loop = this._isLooping;
    },
    _initAudio: function() {
      if (!this._audio && this._source) {
        this._audio = new Audio(this._source);
        this._audio.volume = this._volume;
        this._audio.loop = this._isLooping;
        var self = this;
        this._audio.addEventListener('ended', function() {
          if (typeof window[self.id + '_Completed'] === 'function') {
            window[self.id + '_Completed']();
          }
        });
      }
    },
    Play: function() {
      this._initAudio();
      if (this._audio) this._audio.play().catch(function(e){});
    },
    Start: function() { this.Play(); },
    Pause: function() {
      if (this._audio) this._audio.pause();
    },
    Stop: function() {
      if (this._audio) {
        this._audio.pause();
        this._audio.currentTime = 0;
      }
    },
    Resume: function() { this.Play(); },
    Vibrate: function(ms) {
      NativeBridge.vibrate(ms);
    }
  };

  function TextToSpeechShim(id) {
    this.id = id;
    this._pitch = 1.0;
    this._speechRate = 1.0;
  }
  TextToSpeechShim.prototype = {
    get Pitch() { return this._pitch; },
    set Pitch(v) { this._pitch = Number(v); },
    get SpeechRate() { return this._speechRate; },
    set SpeechRate(v) { this._speechRate = Number(v); },
    Speak: function(message) {
      if (!window.speechSynthesis) return;
      var self = this;
      if (typeof window[self.id + '_BeforeSpeaking'] === 'function') {
        window[self.id + '_BeforeSpeaking']();
      }
      var utterance = new SpeechSynthesisUtterance(message);
      utterance.pitch = this._pitch;
      utterance.rate = this._speechRate;
      utterance.onend = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](true);
        }
      };
      utterance.onerror = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](false);
        }
      };
      window.speechSynthesis.speak(utterance);
    }
  };

  function LocationSensorShim(id, props) {
    this.id = id;
    this._enabled = props.Enabled !== undefined ? !!props.Enabled : true;
    this._latitude = 0;
    this._longitude = 0;
    this._altitude = 0;
    this._accuracy = 0;
    this._watchId = null;
    this.updateWatcher();
  }
  LocationSensorShim.prototype = {
    get Enabled() { return this._enabled; },
    set Enabled(v) { this._enabled = !!v; this.updateWatcher(); },
    get Latitude() { return this._latitude; },
    get Longitude() { return this._longitude; },
    get Altitude() { return this._altitude; },
    get Accuracy() { return this._accuracy; },
    updateWatcher: function() {
      if (this._watchId) {
        navigator.geolocation.clearWatch(this._watchId);
        this._watchId = null;
      }
      if (this._enabled && navigator.geolocation) {
        var self = this;
        this._watchId = navigator.geolocation.watchPosition(function(pos) {
          self._latitude = pos.coords.latitude;
          self._longitude = pos.coords.longitude;
          self._altitude = pos.coords.altitude || 0;
          self._accuracy = pos.coords.accuracy || 0;
          if (typeof window[self.id + '_LocationChanged'] === 'function') {
            window[self.id + '_LocationChanged'](self._latitude, self._longitude, self._altitude, pos.coords.speed || 0);
          }
        }, function(err) {}, { enableHighAccuracy: true });
      }
    }
  };

  function WebShim(id, props) {
    this.id = id;
    this._url = props.Url || props.url || '';
  }
  WebShim.prototype = {
    get Url() { return this._url; },
    set Url(v) { this._url = v; },
    Get: function() {
      var self = this;
      fetch(this._url)
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    },
    PostText: function(text) {
      var self = this;
      fetch(this._url, {
        method: 'POST',
        body: text,
        headers: { 'Content-Type': 'text/plain' }
      })
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    },
    Delete: function() {
      var self = this;
      fetch(this._url, { method: 'DELETE' })
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    }
  };

  // ── Color Utilities ────────────────────────────────────────────────────
  function parseColor(color) {
    try {
      var canvas = document.createElement('canvas');
      var ctx = canvas.getContext('2d');
      ctx.fillStyle = color;
      var resolved = ctx.fillStyle;
      if (resolved.charAt(0) === '#') {
        return [
          parseInt(resolved.substring(1, 3), 16),
          parseInt(resolved.substring(3, 5), 16),
          parseInt(resolved.substring(5, 7), 16)
        ];
      }
    } catch (e) {}
    if (typeof color === 'string') {
      var match = color.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);
      if (match) {
        return [parseInt(match[1], 16), parseInt(match[2], 16), parseInt(match[3], 16)];
      }
    }
    return [0, 0, 0];
  }

  function blendColors(color1, color2, ratio) {
    var c1 = parseColor(color1);
    var c2 = parseColor(color2);
    var r = Math.min(1, Math.max(0, Number(ratio)));
    var red = Math.round(c1[0] * (1 - r) + c2[0] * r);
    var green = Math.round(c1[1] * (1 - r) + c2[1] * r);
    var blue = Math.round(c1[2] * (1 - r) + c2[2] * r);
    return 'rgb(' + red + ',' + green + ',' + blue + ')';
  }

  // ── Component Registry ─────────────────────────────────────────────────
  function getComponent(id) {
    return components[id] || document.getElementById('comp-' + id);
  }

  function getComponentValue(id, prop) {
    var el = getComponent(id);
    if (!el) return '';
    
    // Special properties
    if (prop === 'Selection' || prop === 'selection') return el._selection || '';
    if (prop === 'SelectionIndex' || prop === 'selectionIndex') return el._selectionIndex || 0;
    if (prop === 'Elements' || prop === 'elements') return el._elements || [];
    if (prop === 'ElementsFromString' || prop === 'elementsFromString') return (el._elements || []).join(',');
    
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') return el.value;
    if (el.type === 'checkbox') return el.checked;
    return el.textContent || '';
  }

  function setComponentProperty(id, prop, value) {
    var el = getComponent(id);
    if (!el) return;
    switch (prop) {
      case 'Text': case 'text':
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.value = value;
        else el.textContent = value;
        break;
      case 'BackgroundColor': case 'backgroundColor':
        el.style.backgroundColor = value;
        break;
      case 'TextColor': case 'textColor':
        el.style.color = value;
        break;
      case 'Visible': case 'visible':
        el.style.display = value ? '' : 'none';
        break;
      case 'Enabled': case 'enabled':
        el.disabled = !value;
        if (!value) el.style.opacity = '0.5';
        else el.style.opacity = '1';
        break;
      case 'Width': case 'width':
        el.style.width = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'Height': case 'height':
        el.style.height = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'FontSize': case 'fontSize':
        el.style.fontSize = value + 'px';
        break;
      case 'Picture': case 'picture': case 'Image':
        if (el.tagName === 'IMG') el.src = value;
        else el.style.backgroundImage = 'url(' + value + ')';
        break;
      case 'Hint': case 'hint':
        el.placeholder = value;
        break;
      case 'Checked': case 'checked':
        var cb = el.querySelector('input[type="checkbox"]') || el;
        cb.checked = !!value;
        break;
      case 'ElementsFromString': case 'elementsFromString':
        el._elements = typeof value === 'string' ? value.split(',') : [];
        break;
      case 'Elements': case 'elements':
        el._elements = Array.isArray(value) ? value : (typeof value === 'string' ? value.split(',') : []);
        break;
      case 'Selection': case 'selection':
        el._selection = value;
        var idx = (el._elements || []).indexOf(value);
        el._selectionIndex = idx >= 0 ? idx + 1 : 0;
        break;
    }
  }

  // ── Screen Navigation ──────────────────────────────────────────────────
  function navigateTo(screenId) {
    var allScreens = document.querySelectorAll('.screen');
    for (var i = 0; i < allScreens.length; i++) {
      allScreens[i].classList.remove('active');
    }
    var target = document.getElementById('screen-' + screenId);
    if (target) {
      target.classList.add('active');
      currentScreen = screenId;
    }
  }

  function closeScreen() {
    // Go back to first screen
    navigateTo("Screen1");
  }

  function render_Screen1() {
    var container = document.createElement('div');
    container.id = "screen-Screen1";
    container.className = 'screen';
    var el_Button1 = document.createElement('button');
    el_Button1.id = 'comp-Button1';
    el_Button1.className = 'comp-button';
    el_Button1.textContent = "Click Me";
    el_Button1.addEventListener('click', function() {
      if (typeof window['Button1_Click'] === 'function') window['Button1_Click']();
    });
    components['Button1'] = el_Button1;
    container.appendChild(el_Button1);
    document.getElementById('app-root').appendChild(container);
  }


  // ── Component Proxy Objects ──────────────────────────────────────────
  // Proxy: Button1 (Button)
  var Button1 = {
    get Text() { return getComponentValue('Button1', 'Text'); },
    set Text(v) { setComponentProperty('Button1', 'Text', v); },
    get BackgroundColor() { return getComponentValue('Button1', 'BackgroundColor'); },
    set BackgroundColor(v) { setComponentProperty('Button1', 'BackgroundColor', v); },
    get TextColor() { return getComponentValue('Button1', 'TextColor'); },
    set TextColor(v) { setComponentProperty('Button1', 'TextColor', v); },
    get Visible() { return getComponentValue('Button1', 'Visible'); },
    set Visible(v) { setComponentProperty('Button1', 'Visible', v); },
    get Enabled() { return getComponentValue('Button1', 'Enabled'); },
    set Enabled(v) { setComponentProperty('Button1', 'Enabled', v); },
    get Width() { return getComponentValue('Button1', 'Width'); },
    set Width(v) { setComponentProperty('Button1', 'Width', v); },
    get Height() { return getComponentValue('Button1', 'Height'); },
    set Height(v) { setComponentProperty('Button1', 'Height', v); },
    get FontSize() { return getComponentValue('Button1', 'FontSize'); },
    set FontSize(v) { setComponentProperty('Button1', 'FontSize', v); },
    get Hint() { return getComponentValue('Button1', 'Hint'); },
    set Hint(v) { setComponentProperty('Button1', 'Hint', v); },
    get Picture() { return getComponentValue('Button1', 'Picture'); },
    set Picture(v) { setComponentProperty('Button1', 'Picture', v); },
    get Checked() { return getComponentValue('Button1', 'Checked'); },
    set Checked(v) { setComponentProperty('Button1', 'Checked', v); },
    Click: function() {},
  };


  // ── Block Logic (User-defined) ───────────────────────────────────────
  

  // ── Initialization ─────────────────────────────────────────────────────
  window.LeapApp = {
    init: function() {
      var root = document.getElementById('app-root');
      if (!root) throw new Error('Missing app root element.');
      root.innerHTML = '';
      render_Screen1();
      navigateTo("Screen1");
    },
    navigateTo: navigateTo,
    getComponent: getComponent,
    setProperty: setComponentProperty,
    getValue: getComponentValue,
    NativeBridge: NativeBridge,
    state: state
  };

})();
