import * as fabric from 'fabric';
const canvas = new fabric.Canvas('c');
const rect1 = new fabric.Rect();
const rect2 = new fabric.Rect();
canvas.add(rect1, rect2);
const sel = new fabric.ActiveSelection([rect1, rect2], { canvas });
const items = sel.removeAll();
const grp = new fabric.Group(items);
canvas.add(grp);
const items2 = grp.removeAll();
const sel2 = new fabric.ActiveSelection(items2, { canvas });
