/**
 * HTML/CSS/JS Generator for AppInverter → APK Injection
 *
 * Converts AppInverter state (screens, components, block logic)
 * into a complete mobile web application (HTML + CSS + JS).
 * This output is injected into a WebView-based APK template.
 *
 * Works in both Electron and browser environments.
 * Uses CommonJS exports for Node.js (Electron main process) compatibility.
 */

/**
 * Generate the complete index.html for the app
 */
function generateIndexHtml(appState) {
  const { appName, screens } = appState;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <title>${escapeHtml(appName || 'My App')}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app-root"></div>
  <script src="app.js"><\/script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      LeapApp.init();
    });
  <\/script>
</body>
</html>`;
}

/**
 * Generate the CSS stylesheet for the app
 */
function generateStylesCss(appState) {
  const { screens } = appState;

  let css = `/* Auto-generated by LeapLab AppInverter */
* { margin: 0; padding: 0; box-sizing: border-box; }

html, body {
  width: 100%;
  height: 100%;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  overflow: hidden;
  -webkit-tap-highlight-color: transparent;
  -webkit-text-size-adjust: 100%;
}

#app-root {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}

.screen {
  width: 100%;
  height: 100%;
  display: none;
  flex-direction: column;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

.screen.active {
  display: flex;
}

/* Component base styles */
.comp-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: none;
  outline: none;
  -webkit-appearance: none;
  touch-action: manipulation;
  user-select: none;
}

.comp-button:active {
  opacity: 0.75;
  transform: scale(0.97);
}

.comp-label {
  display: block;
}

.comp-textbox {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
}

.comp-textbox:focus {
  border-color: #4285f4;
  box-shadow: 0 0 0 2px rgba(66,133,244,0.2);
}

.comp-image {
  display: block;
  object-fit: contain;
}

.comp-checkbox {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.comp-checkbox input[type="checkbox"] {
  width: 20px;
  height: 20px;
  accent-color: #4285f4;
}

.comp-slider {
  display: block;
  width: 100%;
  -webkit-appearance: none;
  height: 6px;
  border-radius: 3px;
  background: #ddd;
  outline: none;
}

.comp-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: #4285f4;
  cursor: pointer;
}

.comp-switch {
  display: flex;
  align-items: center;
  gap: 8px;
}

.comp-listview {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
  border: 1px solid #e0e0e0;
}

.comp-listview-item {
  padding: 12px 16px;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;
}

.comp-listview-item:active {
  background: #e8f0fe;
}

.comp-spinner {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
  background: white;
  cursor: pointer;
}

.comp-datepicker, .comp-timepicker {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: 1px solid #ccc;
  background: white;
}

.comp-webviewer {
  border: none;
  display: block;
}

.comp-canvas {
  display: block;
  touch-action: none;
}

/* Arrangement containers */
.arrangement-horizontal {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
}

.arrangement-vertical {
  display: flex;
  flex-direction: column;
}

.arrangement-horizontal-scroll {
  display: flex;
  flex-direction: row;
  overflow-x: auto;
  flex-wrap: nowrap;
}

.arrangement-vertical-scroll {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
}

.arrangement-table {
  display: grid;
}

/* Notification / Toast */
.toast-notification {
  position: fixed;
  bottom: 80px;
  left: 50%;
  transform: translateX(-50%);
  background: rgba(0,0,0,0.8);
  color: white;
  padding: 12px 24px;
  border-radius: 24px;
  font-size: 14px;
  z-index: 9999;
  animation: toast-in 0.3s ease, toast-out 0.3s ease 2.7s;
  pointer-events: none;
}

@keyframes toast-in {
  from { opacity: 0; transform: translateX(-50%) translateY(20px); }
  to { opacity: 1; transform: translateX(-50%) translateY(0); }
}

@keyframes toast-out {
  from { opacity: 1; }
  to { opacity: 0; }
}
`;

  // Per-component styles
  screens.forEach(screen => {
    const bgColor = screen.backgroundColor || '#ffffff';
    css += `\n#screen-${screen.id} { background-color: ${bgColor}; }\n`;

    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      css += generateComponentCss(comp);
    });
  });

  return css;
}

/**
 * Generate the JavaScript application code
 */
function generateAppJs(appState) {
  const { screens, blockLogic } = appState;
  let blockCode = '';

  // If blockLogic is XML, we note it — the actual code generation
  // should happen via Blockly's JS generator before calling this.
  // If it's already JS, use it directly.
  if (blockLogic && !blockLogic.trim().startsWith('<')) {
    blockCode = blockLogic;
  }

  let js = `/* Auto-generated by LeapLab AppInverter */
(function() {
  'use strict';

  // ── App State ──────────────────────────────────────────────────────────
  var state = {};
  var currentScreen = '${screens[0]?.id || 'Screen1'}';
  var components = {};

  // ── Native Bridge ──────────────────────────────────────────────────────
  var NativeBridge = {
    showAlert: function(title, message) {
      alert(message);
    },
    showToast: function(message) {
      var toast = document.createElement('div');
      toast.className = 'toast-notification';
      toast.textContent = message;
      document.body.appendChild(toast);
      setTimeout(function() { toast.remove(); }, 3000);
    },
    showListPickerModal: function(elements, callback) {
      var overlay = document.createElement('div');
      overlay.style.position = 'fixed';
      overlay.style.top = '0'; overlay.style.left = '0';
      overlay.style.width = '100%'; overlay.style.height = '100%';
      overlay.style.backgroundColor = 'rgba(0,0,0,0.5)';
      overlay.style.zIndex = '10000';
      overlay.style.display = 'flex';
      overlay.style.flexDirection = 'column';
      
      var modal = document.createElement('div');
      modal.style.backgroundColor = '#fff';
      modal.style.width = '80%';
      modal.style.maxWidth = '400px';
      modal.style.maxHeight = '80%';
      modal.style.margin = 'auto';
      modal.style.borderRadius = '8px';
      modal.style.overflowY = 'auto';
      modal.style.boxShadow = '0 4px 6px rgba(0,0,0,0.1)';

      if (!elements || elements.length === 0) {
        var emptyMsg = document.createElement('div');
        emptyMsg.textContent = 'No elements to pick';
        emptyMsg.style.padding = '16px';
        modal.appendChild(emptyMsg);
      } else {
        elements.forEach(function(item, index) {
          var itemDiv = document.createElement('div');
          itemDiv.textContent = item;
          itemDiv.style.padding = '16px';
          itemDiv.style.borderBottom = '1px solid #eee';
          itemDiv.style.cursor = 'pointer';
          itemDiv.addEventListener('click', function() {
            document.body.removeChild(overlay);
            callback(index, item);
          });
          modal.appendChild(itemDiv);
        });
      }

      var closeBtn = document.createElement('div');
      closeBtn.textContent = 'Cancel';
      closeBtn.style.padding = '16px';
      closeBtn.style.textAlign = 'center';
      closeBtn.style.color = '#4285f4';
      closeBtn.style.fontWeight = 'bold';
      closeBtn.style.cursor = 'pointer';
      closeBtn.addEventListener('click', function() {
        document.body.removeChild(overlay);
      });
      modal.appendChild(closeBtn);

      overlay.appendChild(modal);
      document.body.appendChild(overlay);
    },
    vibrate: function(ms) {
      if (navigator.vibrate) navigator.vibrate(ms || 200);
    },
    openUrl: function(url) {
      window.open(url, '_blank');
    },
    playSound: function(src) {
      try { new Audio(src).play(); } catch(e) {}
    },
    getStorageItem: function(key) {
      try { return localStorage.getItem('leapapp_' + key); } catch(e) { return null; }
    },
    setStorageItem: function(key, value) {
      try { localStorage.setItem('leapapp_' + key, value); } catch(e) {}
    }
  };

  // ── React Native Compatibility Shims ───────────────────────────────────
  // Maps block-generated RN code (navigation, Alert, Vibration) to web APIs
  var navigation = {
    navigate: function(screen) { navigateTo(screen); },
    goBack: function() { closeScreen(); }
  };
  var Alert = {
    alert: function(msg) { NativeBridge.showAlert('Alert', msg); }
  };
  var Vibration = {
    vibrate: function(ms) { NativeBridge.vibrate(ms); }
  };

  // ── Component Registry ─────────────────────────────────────────────────
  function getComponent(id) {
    return components[id] || document.getElementById('comp-' + id);
  }

  function getComponentValue(id, prop) {
    var el = getComponent(id);
    if (!el) return '';
    
    // Special properties
    if (prop === 'Selection' || prop === 'selection') return el._selection || '';
    if (prop === 'SelectionIndex' || prop === 'selectionIndex') return el._selectionIndex || 0;
    if (prop === 'Elements' || prop === 'elements') return el._elements || [];
    if (prop === 'ElementsFromString' || prop === 'elementsFromString') return (el._elements || []).join(',');
    
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') return el.value;
    if (el.type === 'checkbox') return el.checked;
    return el.textContent || '';
  }

  function setComponentProperty(id, prop, value) {
    var el = getComponent(id);
    if (!el) return;
    switch (prop) {
      case 'Text': case 'text':
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.value = value;
        else el.textContent = value;
        break;
      case 'BackgroundColor': case 'backgroundColor':
        el.style.backgroundColor = value;
        break;
      case 'TextColor': case 'textColor':
        el.style.color = value;
        break;
      case 'Visible': case 'visible':
        el.style.display = value ? '' : 'none';
        break;
      case 'Enabled': case 'enabled':
        el.disabled = !value;
        if (!value) el.style.opacity = '0.5';
        else el.style.opacity = '1';
        break;
      case 'Width': case 'width':
        el.style.width = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'Height': case 'height':
        el.style.height = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'FontSize': case 'fontSize':
        el.style.fontSize = value + 'px';
        break;
      case 'Picture': case 'picture': case 'Image':
        if (el.tagName === 'IMG') el.src = value;
        else el.style.backgroundImage = 'url(' + value + ')';
        break;
      case 'Hint': case 'hint':
        el.placeholder = value;
        break;
      case 'Checked': case 'checked':
        var cb = el.querySelector('input[type="checkbox"]') || el;
        cb.checked = !!value;
        break;
      case 'ElementsFromString': case 'elementsFromString':
        el._elements = typeof value === 'string' ? value.split(',') : [];
        break;
      case 'Elements': case 'elements':
        el._elements = Array.isArray(value) ? value : (typeof value === 'string' ? value.split(',') : []);
        break;
      case 'Selection': case 'selection':
        el._selection = value;
        var idx = (el._elements || []).indexOf(value);
        el._selectionIndex = idx >= 0 ? idx + 1 : 0;
        break;
    }
  }

  // ── Screen Navigation ──────────────────────────────────────────────────
  function navigateTo(screenId) {
    var allScreens = document.querySelectorAll('.screen');
    for (var i = 0; i < allScreens.length; i++) {
      allScreens[i].classList.remove('active');
    }
    var target = document.getElementById('screen-' + screenId);
    if (target) {
      target.classList.add('active');
      currentScreen = screenId;
    }
  }

  function closeScreen() {
    // Go back to first screen
    navigateTo('${screens[0]?.id || 'Screen1'}');
  }

`;

  // Generate screen rendering
  screens.forEach(screen => {
    js += generateScreenRenderer(screen);
  });

  // Generate component proxy objects so block-generated code like
  // Button1.Text or Button1.Text = 'Hello' works seamlessly.
  js += `\n  // ── Component Proxy Objects ──────────────────────────────────────────\n`;
  screens.forEach(screen => {
    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      js += generateComponentProxy(comp);
    });
  });

  // Event handlers from block logic
  js += `
  // ── Block Logic (User-defined) ───────────────────────────────────────
  ${blockCode}

  // ── Initialization ─────────────────────────────────────────────────────
  window.LeapApp = {
    init: function() {
`;

  screens.forEach(screen => {
    js += `      render_${screen.id}();\n`;
  });

  js += `      navigateTo('${screens[0]?.id || 'Screen1'}');
    },
    navigateTo: navigateTo,
    getComponent: getComponent,
    setProperty: setComponentProperty,
    getValue: getComponentValue,
    NativeBridge: NativeBridge,
    state: state
  };

})();
`;

  return js;
}

/**
 * Generate all files needed for the APK injection
 */
function generateWebApp(appState) {
  return {
    'www/index.html': generateIndexHtml(appState),
    'www/styles.css': generateStylesCss(appState),
    'www/app.js': generateAppJs(appState),
    'www/app_config.json': JSON.stringify({
      appName: appState.appName || 'My App',
      packageName: appState.packageName || 'com.leaplab.myapp',
      versionCode: appState.versionCode || 1,
      versionName: appState.versionName || '1.0',
      screens: (appState.screens || []).map(s => s.id)
    }, null, 2)
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function walkComponentTree(list, visitor) {
  if (!list) return;
  for (const item of list) {
    visitor(item);
    if (item.children?.length) walkComponentTree(item.children, visitor);
  }
}

function resolveDimension(value, fallback) {
  if (value === 'fill_parent' || value === -2) return '100%';
  if (value === 'automatic' || value === -1 || value === undefined) return fallback || 'auto';
  if (typeof value === 'number') return value + 'px';
  return value;
}

function generateComponentCss(comp) {
  const { id, type, props = {} } = comp;
  const selector = `#comp-${id}`;
  let rules = '';

  const width = resolveDimension(props.width || props.Width, 'auto');
  const height = resolveDimension(props.height || props.Height, 'auto');
  const bgColor = props.backgroundColor || props.BackgroundColor || 'transparent';
  const textColor = props.textColor || props.TextColor;
  const fontSize = props.fontSize || props.FontSize || 14;
  const bold = props.bold || props.FontBold;
  const italic = props.italic || props.FontItalic;
  const padding = props.padding || 8;
  const margin = props.margin || 4;
  const borderRadius = props.borderRadius || props.Shape === 'rounded' ? 8 : 0;

  rules += `${selector} {\n`;
  if (width !== 'auto') rules += `  width: ${width};\n`;
  if (height !== 'auto') rules += `  height: ${height};\n`;
  if (bgColor !== 'transparent') rules += `  background-color: ${bgColor};\n`;
  if (textColor) rules += `  color: ${textColor};\n`;
  rules += `  font-size: ${fontSize}px;\n`;
  if (bold) rules += `  font-weight: bold;\n`;
  if (italic) rules += `  font-style: italic;\n`;
  rules += `  padding: ${padding}px;\n`;
  rules += `  margin: ${margin}px;\n`;
  if (borderRadius) rules += `  border-radius: ${borderRadius}px;\n`;
  rules += `}\n`;

  return rules;
}

function generateScreenRenderer(screen) {
  const screenId = screen.id;
  const components = screen.components || [];

  let js = `  function render_${screenId}() {\n`;
  js += `    var container = document.createElement('div');\n`;
  js += `    container.id = 'screen-${screenId}';\n`;
  js += `    container.className = 'screen';\n`;

  components.forEach(comp => {
    js += generateComponentCreation(comp, 'container');
  });

  js += `    document.getElementById('app-root').appendChild(container);\n`;
  js += `  }\n\n`;

  return js;
}

function generateComponentCreation(comp, parentVar) {
  const { id, type, props = {}, children } = comp;
  const varName = `el_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
  let js = '';

  switch (type) {
    case 'Button':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Button')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      if (typeof ${id}_Click === 'function') ${id}_Click();\n`;
      js += `    });\n`;
      break;

    case 'Label':
      js += `    var ${varName} = document.createElement('span');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-label';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || '')};\n`;
      break;

    case 'TextBox':
      const multiLine = props.multiLine || props.MultiLine;
      const tag = multiLine ? 'textarea' : 'input';
      js += `    var ${varName} = document.createElement('${tag}');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      if (!multiLine) js += `    ${varName}.type = 'text';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || '')};\n`;
      js += `    ${varName}.value = ${JSON.stringify(props.text || props.Text || '')};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'PasswordTextBox':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      js += `    ${varName}.type = 'password';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || 'Password')};\n`;
      break;

    case 'Image':
      js += `    var ${varName} = document.createElement('img');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-image';\n`;
      js += `    ${varName}.src = ${JSON.stringify(props.picture || props.Picture || '')};\n`;
      js += `    ${varName}.alt = ${JSON.stringify(id)};\n`;
      break;

    case 'CheckBox':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-checkbox';\n`;
      js += `    var ${varName}_cb = document.createElement('input');\n`;
      js += `    ${varName}_cb.type = 'checkbox';\n`;
      js += `    ${varName}_cb.checked = ${Boolean(props.checked || props.Checked)};\n`;
      js += `    ${varName}_cb.addEventListener('change', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.checked);\n`;
      js += `    });\n`;
      js += `    var ${varName}_lbl = document.createElement('span');\n`;
      js += `    ${varName}_lbl.textContent = ${JSON.stringify(props.text || props.Text || 'CheckBox')};\n`;
      js += `    ${varName}.appendChild(${varName}_cb);\n`;
      js += `    ${varName}.appendChild(${varName}_lbl);\n`;
      break;

    case 'Slider':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-slider';\n`;
      js += `    ${varName}.type = 'range';\n`;
      js += `    ${varName}.min = ${props.minValue || props.MinValue || 0};\n`;
      js += `    ${varName}.max = ${props.maxValue || props.MaxValue || 100};\n`;
      js += `    ${varName}.value = ${props.thumbPosition || props.ThumbPosition || 50};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(Number(e.target.value));\n`;
      js += `    });\n`;
      break;

    case 'Switch':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-switch';\n`;
      js += `    var ${varName}_sw = document.createElement('input');\n`;
      js += `    ${varName}_sw.type = 'checkbox';\n`;
      js += `    ${varName}_sw.checked = ${Boolean(props.on || props.On)};\n`;
      js += `    ${varName}_sw.addEventListener('change', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.checked);\n`;
      js += `    });\n`;
      js += `    ${varName}.appendChild(${varName}_sw);\n`;
      break;

    case 'ListView':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-listview';\n`;
      const items = props.elements || props.Elements || [];
      const itemsList = typeof items === 'string' ? items.split(',') : items;
      itemsList.forEach((item, idx) => {
        js += `    (function() {\n`;
        js += `      var item = document.createElement('div');\n`;
        js += `      item.className = 'comp-listview-item';\n`;
        js += `      item.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      item.addEventListener('click', function() {\n`;
        js += `        if (typeof ${id}_AfterPicking === 'function') ${id}_AfterPicking(${idx}, item.textContent);\n`;
        js += `      });\n`;
        js += `      ${varName}.appendChild(item);\n`;
        js += `    })();\n`;
      });
      break;

    case 'ListPicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'ListPicker')};\n`;

      const lpItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      js += `    ${varName}._elements = ${JSON.stringify(lpItems)};\n`;
      js += `    ${varName}._selection = '';\n`;
      js += `    ${varName}._selectionIndex = 0;\n`;

      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      if (typeof ${id}_BeforePicking === 'function') ${id}_BeforePicking();\n`;
      js += `      NativeBridge.showListPickerModal(${varName}._elements, function(index, item) {\n`;
      js += `        ${varName}._selection = item;\n`;
      js += `        ${varName}._selectionIndex = index + 1;\n`; // 1-based index for App Inventor
      js += `        if (typeof ${id}_AfterPicking === 'function') ${id}_AfterPicking();\n`;
      js += `      });\n`;
      js += `    });\n`;
      break;

    case 'Spinner':
      js += `    var ${varName} = document.createElement('select');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-spinner';\n`;
      const spinnerItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      const spinnerList = typeof spinnerItems === 'string' ? spinnerItems.split(',') : spinnerItems;
      spinnerList.forEach(item => {
        js += `    (function() {\n`;
        js += `      var opt = document.createElement('option');\n`;
        js += `      opt.value = ${JSON.stringify(String(item).trim())};\n`;
        js += `      opt.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      ${varName}.appendChild(opt);\n`;
        js += `    })();\n`;
      });
      js += `    ${varName}.addEventListener('change', function(e) {\n`;
      js += `      ${varName}._selection = e.target.value;\n`;
      js += `      ${varName}._selectionIndex = e.target.selectedIndex + 1;\n`;
      js += `      if (typeof ${id}_AfterSelecting === 'function') ${id}_AfterSelecting(e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'WebViewer':
      js += `    var ${varName} = document.createElement('iframe');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-webviewer';\n`;
      js += `    ${varName}.src = ${JSON.stringify(props.homeUrl || props.HomeUrl || 'about:blank')};\n`;
      break;

    case 'Canvas':
      js += `    var ${varName} = document.createElement('canvas');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-canvas';\n`;
      js += `    ${varName}.width = ${props.width || 300};\n`;
      js += `    ${varName}.height = ${props.height || 300};\n`;
      break;

    // Layout containers
    case 'HorizontalArrangement':
    case 'HorizontalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'horizontal-scroll' : 'horizontal'}';\n`;
      break;

    case 'VerticalArrangement':
    case 'VerticalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'vertical-scroll' : 'vertical'}';\n`;
      break;

    case 'TableArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-table';\n`;
      const cols = props.columns || props.Columns || 2;
      js += `    ${varName}.style.gridTemplateColumns = 'repeat(${cols}, 1fr)';\n`;
      break;

    default:
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(type + ' (' + id + ')')};\n`;
      break;
  }

  js += `    components['${id}'] = ${varName};\n`;

  // Render children for arrangement containers
  if (children && children.length > 0) {
    children.forEach(child => {
      js += generateComponentCreation(child, varName);
    });
  }

  js += `    ${parentVar}.appendChild(${varName});\n`;

  return js;
}

/**
 * Generate a proxy object for a component so block-generated code
 * like `Button1.Text` or `Button1.BackgroundColor = '#ff0000'` works.
 */
function generateComponentProxy(comp) {
  const { id, type, props = {} } = comp;
  const propNames = Object.keys(props);
  if (propNames.length === 0 && type !== 'Button' && type !== 'Label') return '';

  // Standard property list based on component type
  const allProps = new Set([
    'Text', 'BackgroundColor', 'TextColor', 'Visible', 'Enabled',
    'Width', 'Height', 'FontSize', 'Hint', 'Picture', 'Checked',
    ...propNames
  ]);

  let js = `  // Proxy: ${id} (${type})\n`;
  js += `  var ${id} = {\n`;

  for (const prop of allProps) {
    const camelProp = prop.charAt(0).toLowerCase() + prop.slice(1);
    js += `    get ${prop}() { return getComponentValue('${id}', '${prop}'); },\n`;
    js += `    set ${prop}(v) { setComponentProperty('${id}', '${prop}', v); },\n`;
  }

  // Add Click handler registration
  if (['Button', 'Label', 'Image', 'ListView', 'CheckBox'].includes(type)) {
    js += `    Click: function() {},\n`;
  }

  js += `  };\n\n`;
  return js;
}

// ── CommonJS Exports ────────────────────────────────────────────────────────

module.exports = {
  generateIndexHtml,
  generateStylesCss,
  generateAppJs,
  generateWebApp,
  generateComponentProxy
};
