/**
 * HTML/CSS/JS Generator for AppInverter → APK Injection
 *
 * Converts AppInverter state (screens, components, block logic)
 * into a complete mobile web application (HTML + CSS + JS).
 * This output is injected into a WebView-based APK template.
 *
 * Works in both Electron and browser environments.
 * Uses CommonJS exports for Node.js (Electron main process) compatibility.
 */

/**
 * Generate the complete index.html for the app
 */
function generateIndexHtml(appState) {
  const { appName, screens } = appState;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <title>${escapeHtml(appName || 'My App')}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app-root"></div>
  <script src="app.js"><\/script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      LeapApp.init();
    });
  <\/script>
</body>
</html>`;
}

/**
 * Generate the CSS stylesheet for the app
 */
function generateStylesCss(appState) {
  const { screens } = appState;

  let css = `/* Auto-generated by LeapLab AppInverter */
* { margin: 0; padding: 0; box-sizing: border-box; }

html, body {
  width: 100%;
  height: 100%;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  overflow: hidden;
  -webkit-tap-highlight-color: transparent;
  -webkit-text-size-adjust: 100%;
}

#app-root {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}

.screen {
  width: 100%;
  height: 100%;
  display: none;
  flex-direction: column;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

.screen.active {
  display: flex;
}

/* Component base styles */
.comp-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: none;
  outline: none;
  -webkit-appearance: none;
  touch-action: manipulation;
  user-select: none;
}

.comp-button:active {
  opacity: 0.75;
  transform: scale(0.97);
}

.comp-label {
  display: block;
}

.comp-textbox {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
}

.comp-textbox:focus {
  border-color: #4285f4;
  box-shadow: 0 0 0 2px rgba(66,133,244,0.2);
}

.comp-image {
  display: block;
  object-fit: contain;
}

.comp-checkbox {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.comp-checkbox input[type="checkbox"] {
  width: 20px;
  height: 20px;
  accent-color: #4285f4;
}

.comp-slider {
  display: block;
  width: 100%;
  -webkit-appearance: none;
  height: 6px;
  border-radius: 3px;
  background: #ddd;
  outline: none;
}

.comp-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: #4285f4;
  cursor: pointer;
}

.comp-switch {
  display: flex;
  align-items: center;
  gap: 8px;
}

.comp-listview {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
  border: 1px solid #e0e0e0;
}

.comp-listview-item {
  padding: 12px 16px;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;
}

.comp-listview-item:active {
  background: #e8f0fe;
}

.comp-spinner {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
  background: white;
  cursor: pointer;
}

.comp-datepicker, .comp-timepicker {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: 1px solid #ccc;
  background: white;
}

.comp-webviewer {
  border: none;
  display: block;
}

.comp-canvas {
  display: block;
  touch-action: none;
}

/* Arrangement containers */
.arrangement-horizontal {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
}

.arrangement-vertical {
  display: flex;
  flex-direction: column;
}

.arrangement-horizontal-scroll {
  display: flex;
  flex-direction: row;
  overflow-x: auto;
  flex-wrap: nowrap;
}

.arrangement-vertical-scroll {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
}

.arrangement-table {
  display: grid;
}

/* Notification / Toast */
.toast-notification {
  position: fixed;
  bottom: 80px;
  left: 50%;
  transform: translateX(-50%);
  background: rgba(0,0,0,0.8);
  color: white;
  padding: 12px 24px;
  border-radius: 24px;
  font-size: 14px;
  z-index: 9999;
  animation: toast-in 0.3s ease, toast-out 0.3s ease 2.7s;
  pointer-events: none;
}

@keyframes toast-in {
  from { opacity: 0; transform: translateX(-50%) translateY(20px); }
  to { opacity: 1; transform: translateX(-50%) translateY(0); }
}

@keyframes toast-out {
  from { opacity: 1; }
  to { opacity: 0; }
}
`;

  // Per-component styles
  screens.forEach(screen => {
    const bgColor = screen.backgroundColor || '#ffffff';
    css += `\n#screen-${screen.id} { background-color: ${bgColor}; }\n`;

    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      css += generateComponentCss(comp);
    });
  });

  return css;
}

/**
 * Generate the JavaScript application code
 */
function generateAppJs(appState) {
  const { screens, blockLogic } = appState;
  let blockCode = '';

  // If blockLogic is XML, we note it — the actual code generation
  // should happen via Blockly's JS generator before calling this.
  // If it's already JS, use it directly.
  if (blockLogic && !blockLogic.trim().startsWith('<')) {
    blockCode = blockLogic;
  }

  let js = `/* Auto-generated by LeapLab AppInverter */
(function() {
  'use strict';

  // ── App State ──────────────────────────────────────────────────────────
  var state = {};
  var currentScreen = '${screens[0]?.id || 'Screen1'}';
  var components = {};

  // ── Native Bridge ──────────────────────────────────────────────────────
  var NativeBridge = {
    showAlert: function(title, message) {
      alert(message);
    },
    showToast: function(message) {
      var toast = document.createElement('div');
      toast.className = 'toast-notification';
      toast.textContent = message;
      document.body.appendChild(toast);
      setTimeout(function() { toast.remove(); }, 3000);
    },
    showListPickerModal: function(elements, callback) {
      var overlay = document.createElement('div');
      overlay.style.position = 'fixed';
      overlay.style.top = '0'; overlay.style.left = '0';
      overlay.style.width = '100%'; overlay.style.height = '100%';
      overlay.style.backgroundColor = 'rgba(0,0,0,0.5)';
      overlay.style.zIndex = '10000';
      overlay.style.display = 'flex';
      overlay.style.flexDirection = 'column';
      
      var modal = document.createElement('div');
      modal.style.backgroundColor = '#fff';
      modal.style.width = '80%';
      modal.style.maxWidth = '400px';
      modal.style.maxHeight = '80%';
      modal.style.margin = 'auto';
      modal.style.borderRadius = '8px';
      modal.style.overflowY = 'auto';
      modal.style.boxShadow = '0 4px 6px rgba(0,0,0,0.1)';

      if (!elements || elements.length === 0) {
        var emptyMsg = document.createElement('div');
        emptyMsg.textContent = 'No elements to pick';
        emptyMsg.style.padding = '16px';
        modal.appendChild(emptyMsg);
      } else {
        elements.forEach(function(item, index) {
          var itemDiv = document.createElement('div');
          itemDiv.textContent = item;
          itemDiv.style.padding = '16px';
          itemDiv.style.borderBottom = '1px solid #eee';
          itemDiv.style.cursor = 'pointer';
          itemDiv.addEventListener('click', function() {
            document.body.removeChild(overlay);
            callback(index, item);
          });
          modal.appendChild(itemDiv);
        });
      }

      var closeBtn = document.createElement('div');
      closeBtn.textContent = 'Cancel';
      closeBtn.style.padding = '16px';
      closeBtn.style.textAlign = 'center';
      closeBtn.style.color = '#4285f4';
      closeBtn.style.fontWeight = 'bold';
      closeBtn.style.cursor = 'pointer';
      closeBtn.addEventListener('click', function() {
        document.body.removeChild(overlay);
      });
      modal.appendChild(closeBtn);

      overlay.appendChild(modal);
      document.body.appendChild(overlay);
    },
    vibrate: function(ms) {
      if (navigator.vibrate) navigator.vibrate(ms || 200);
    },
    openUrl: function(url) {
      window.open(url, '_blank');
    },
    playSound: function(src) {
      try { new Audio(src).play(); } catch(e) {}
    },
    getStorageItem: function(key) {
      try { return localStorage.getItem('leapapp_' + key); } catch(e) { return null; }
    },
    setStorageItem: function(key, value) {
      try { localStorage.setItem('leapapp_' + key, value); } catch(e) {}
    }
  };

  // ── React Native Compatibility Shims ───────────────────────────────────
  // Maps block-generated RN code (navigation, Alert, Vibration) to web APIs
  var navigation = {
    navigate: function(screen) { navigateTo(screen); },
    goBack: function() { closeScreen(); }
  };
  var Alert = {
    alert: function(msg) { NativeBridge.showAlert('Alert', msg); }
  };
  var Vibration = {
    vibrate: function(ms) { NativeBridge.vibrate(ms); }
  };

  // ── Non-Visible Component Shims ────────────────────────────────────────
  function ClockShim(id, props) {
    this.id = id;
    this._timerEnabled = props.TimerEnabled !== undefined ? !!props.TimerEnabled : true;
    this._timerInterval = props.TimerInterval !== undefined ? Number(props.TimerInterval) : 1000;
    this._timerId = null;
    this.updateTimer();
  }
  ClockShim.prototype = {
    get TimerEnabled() { return this._timerEnabled; },
    set TimerEnabled(v) { this._timerEnabled = !!v; this.updateTimer(); },
    get TimerInterval() { return this._timerInterval; },
    set TimerInterval(v) { this._timerInterval = Number(v); this.updateTimer(); },
    updateTimer: function() {
      if (this._timerId) clearInterval(this._timerId);
      if (this._timerEnabled && this._timerInterval > 0) {
        var self = this;
        this._timerId = setInterval(function() {
          if (typeof window[self.id + '_Timer'] === 'function') {
            window[self.id + '_Timer']();
          }
        }, this._timerInterval);
      }
    },
    Now: function() { return new Date(); },
    SystemTime: function() { return Date.now(); },
    MakeInstant: function(text) { return new Date(text); },
    MakeInstantFromMillis: function(m) { return new Date(Number(m)); },
    GetMillis: function(instant) { return (instant instanceof Date ? instant : new Date(instant)).getTime(); },
    AddDays: function(instant, days) {
      var d = new Date(instant);
      d.setDate(d.getDate() + Number(days));
      return d;
    },
    AddHours: function(instant, hours) {
      var d = new Date(instant);
      d.setHours(d.getHours() + Number(hours));
      return d;
    },
    AddMinutes: function(instant, minutes) {
      var d = new Date(instant);
      d.setMinutes(d.getMinutes() + Number(minutes));
      return d;
    },
    AddSeconds: function(instant, seconds) {
      var d = new Date(instant);
      d.setSeconds(d.getSeconds() + Number(seconds));
      return d;
    },
    AddWeeks: function(instant, weeks) {
      var d = new Date(instant);
      d.setDate(d.getDate() + (Number(weeks) * 7));
      return d;
    },
    AddMonths: function(instant, months) {
      var d = new Date(instant);
      d.setMonth(d.getMonth() + Number(months));
      return d;
    },
    AddYears: function(instant, years) {
      var d = new Date(instant);
      d.setFullYear(d.getFullYear() + Number(years));
      return d;
    },
    Duration: function(start, end) {
      return Math.abs(new Date(end).getTime() - new Date(start).getTime());
    },
    DurationToDays: function(dur) { return dur / (24 * 3600 * 1000); },
    DurationToHours: function(dur) { return dur / (3600 * 1000); },
    DurationToMinutes: function(dur) { return dur / (60 * 1000); },
    DurationToSeconds: function(dur) { return dur / 1000; },
    DurationToWeeks: function(dur) { return dur / (7 * 24 * 3600 * 1000); },
    FormatDate: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleDateString(); },
    FormatDateTime: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleString(); },
    FormatTime: function(inst) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleTimeString(); }
  };

  function TinyDBShim(id, props) {
    this.id = id;
    this._namespace = props.Namespace || id;
  }
  TinyDBShim.prototype = {
    get Namespace() { return this._namespace; },
    set Namespace(v) { this._namespace = v; },
    _getKey: function(tag) { return 'tinydb_' + this._namespace + '_' + tag; },
    StoreValue: function(tag, val) {
      try { localStorage.setItem(this._getKey(tag), JSON.stringify(val)); } catch(e) {}
    },
    GetValue: function(tag, fallback) {
      try {
        var v = localStorage.getItem(this._getKey(tag));
        return v === null ? fallback : JSON.parse(v);
      } catch(e) { return fallback; }
    },
    ClearTag: function(tag) {
      try { localStorage.removeItem(this._getKey(tag)); } catch(e) {}
    },
    ClearAll: function() {
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        var keysToRemove = [];
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) keysToRemove.push(key);
        }
        keysToRemove.forEach(function(k) { localStorage.removeItem(k); });
      } catch(e) {}
    },
    GetTags: function() {
      var tags = [];
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) tags.push(key.substring(prefix.length));
        }
      } catch(e) {}
      return tags;
    }
  };

  function NotifierShim(id) {
    this.id = id;
  }
  NotifierShim.prototype = {
    ShowAlert: function(notice) {
      NativeBridge.showToast(notice);
    },
    ShowMessageDialog: function(message, title, buttonText) {
      alert((title ? title + "\n\n" : "") + message);
    },
    ShowChooseDialog: function(message, title, button1, button2, cancelable) {
      var res = confirm((title ? title + "\n\n" : "") + message);
      var choice = res ? button1 : button2;
      var self = this;
      setTimeout(function() {
        if (typeof window[self.id + '_AfterChoosing'] === 'function') {
          window[self.id + '_AfterChoosing'](choice);
        }
      }, 50);
    },
    ShowTextDialog: function(message, title, cancelable) {
      var res = prompt((title ? title + "\n\n" : "") + message);
      var self = this;
      if (res !== null) {
        setTimeout(function() {
          if (typeof window[self.id + '_AfterTextInput'] === 'function') {
            window[self.id + '_AfterTextInput'](res);
          }
        }, 50);
      }
    }
  };

  function SoundShim(id, props) {
    this.id = id;
    this._source = props.Source || props.source || '';
    this._volume = props.Volume !== undefined ? Number(props.Volume) : 1.0;
    this._isLooping = !!props.IsLooping;
    this._audio = null;
  }
  SoundShim.prototype = {
    get Source() { return this._source; },
    set Source(v) {
      this._source = v;
      if (this._audio) this._audio.src = v;
    },
    get Volume() { return this._volume; },
    set Volume(v) {
      this._volume = Number(v);
      if (this._audio) this._audio.volume = this._volume;
    },
    get IsLooping() { return this._isLooping; },
    set IsLooping(v) {
      this._isLooping = !!v;
      if (this._audio) this._audio.loop = this._isLooping;
    },
    _initAudio: function() {
      if (!this._audio && this._source) {
        this._audio = new Audio(this._source);
        this._audio.volume = this._volume;
        this._audio.loop = this._isLooping;
        var self = this;
        this._audio.addEventListener('ended', function() {
          if (typeof window[self.id + '_Completed'] === 'function') {
            window[self.id + '_Completed']();
          }
        });
      }
    },
    Play: function() {
      this._initAudio();
      if (this._audio) this._audio.play().catch(function(e){});
    },
    Start: function() { this.Play(); },
    Pause: function() {
      if (this._audio) this._audio.pause();
    },
    Stop: function() {
      if (this._audio) {
        this._audio.pause();
        this._audio.currentTime = 0;
      }
    },
    Resume: function() { this.Play(); },
    Vibrate: function(ms) {
      NativeBridge.vibrate(ms);
    }
  };

  function TextToSpeechShim(id) {
    this.id = id;
    this._pitch = 1.0;
    this._speechRate = 1.0;
  }
  TextToSpeechShim.prototype = {
    get Pitch() { return this._pitch; },
    set Pitch(v) { this._pitch = Number(v); },
    get SpeechRate() { return this._speechRate; },
    set SpeechRate(v) { this._speechRate = Number(v); },
    Speak: function(message) {
      if (!window.speechSynthesis) return;
      var self = this;
      if (typeof window[self.id + '_BeforeSpeaking'] === 'function') {
        window[self.id + '_BeforeSpeaking']();
      }
      var utterance = new SpeechSynthesisUtterance(message);
      utterance.pitch = this._pitch;
      utterance.rate = this._speechRate;
      utterance.onend = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](true);
        }
      };
      utterance.onerror = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](false);
        }
      };
      window.speechSynthesis.speak(utterance);
    }
  };

  function LocationSensorShim(id, props) {
    this.id = id;
    this._enabled = props.Enabled !== undefined ? !!props.Enabled : true;
    this._latitude = 0;
    this._longitude = 0;
    this._altitude = 0;
    this._accuracy = 0;
    this._watchId = null;
    this.updateWatcher();
  }
  LocationSensorShim.prototype = {
    get Enabled() { return this._enabled; },
    set Enabled(v) { this._enabled = !!v; this.updateWatcher(); },
    get Latitude() { return this._latitude; },
    get Longitude() { return this._longitude; },
    get Altitude() { return this._altitude; },
    get Accuracy() { return this._accuracy; },
    updateWatcher: function() {
      if (this._watchId) {
        navigator.geolocation.clearWatch(this._watchId);
        this._watchId = null;
      }
      if (this._enabled && navigator.geolocation) {
        var self = this;
        this._watchId = navigator.geolocation.watchPosition(function(pos) {
          self._latitude = pos.coords.latitude;
          self._longitude = pos.coords.longitude;
          self._altitude = pos.coords.altitude || 0;
          self._accuracy = pos.coords.accuracy || 0;
          if (typeof window[self.id + '_LocationChanged'] === 'function') {
            window[self.id + '_LocationChanged'](self._latitude, self._longitude, self._altitude, pos.coords.speed || 0);
          }
        }, function(err) {}, { enableHighAccuracy: true });
      }
    }
  };

  function WebShim(id, props) {
    this.id = id;
    this._url = props.Url || props.url || '';
  }
  WebShim.prototype = {
    get Url() { return this._url; },
    set Url(v) { this._url = v; },
    Get: function() {
      var self = this;
      fetch(this._url)
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    },
    PostText: function(text) {
      var self = this;
      fetch(this._url, {
        method: 'POST',
        body: text,
        headers: { 'Content-Type': 'text/plain' }
      })
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    },
    Delete: function() {
      var self = this;
      fetch(this._url, { method: 'DELETE' })
        .then(function(res) {
          return res.text().then(function(text) {
            if (typeof window[self.id + '_GotText'] === 'function') {
              window[self.id + '_GotText'](self._url, res.status, res.headers.get('content-type') || '', text);
            }
          });
        })
        .catch(function(err) {
          if (typeof window[self.id + '_GotText'] === 'function') {
            window[self.id + '_GotText'](self._url, 0, '', err.message);
          }
        });
    }
  };

  // ── Component Registry ─────────────────────────────────────────────────
  function getComponent(id) {
    return components[id] || document.getElementById('comp-' + id);
  }

  function getComponentValue(id, prop) {
    var el = getComponent(id);
    if (!el) return '';
    
    // Special properties
    if (prop === 'Selection' || prop === 'selection') return el._selection || '';
    if (prop === 'SelectionIndex' || prop === 'selectionIndex') return el._selectionIndex || 0;
    if (prop === 'Elements' || prop === 'elements') return el._elements || [];
    if (prop === 'ElementsFromString' || prop === 'elementsFromString') return (el._elements || []).join(',');
    
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') return el.value;
    if (el.type === 'checkbox') return el.checked;
    return el.textContent || '';
  }

  function setComponentProperty(id, prop, value) {
    var el = getComponent(id);
    if (!el) return;
    switch (prop) {
      case 'Text': case 'text':
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.value = value;
        else el.textContent = value;
        break;
      case 'BackgroundColor': case 'backgroundColor':
        el.style.backgroundColor = value;
        break;
      case 'TextColor': case 'textColor':
        el.style.color = value;
        break;
      case 'Visible': case 'visible':
        el.style.display = value ? '' : 'none';
        break;
      case 'Enabled': case 'enabled':
        el.disabled = !value;
        if (!value) el.style.opacity = '0.5';
        else el.style.opacity = '1';
        break;
      case 'Width': case 'width':
        el.style.width = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'Height': case 'height':
        el.style.height = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'FontSize': case 'fontSize':
        el.style.fontSize = value + 'px';
        break;
      case 'Picture': case 'picture': case 'Image':
        if (el.tagName === 'IMG') el.src = value;
        else el.style.backgroundImage = 'url(' + value + ')';
        break;
      case 'Hint': case 'hint':
        el.placeholder = value;
        break;
      case 'Checked': case 'checked':
        var cb = el.querySelector('input[type="checkbox"]') || el;
        cb.checked = !!value;
        break;
      case 'ElementsFromString': case 'elementsFromString':
        el._elements = typeof value === 'string' ? value.split(',') : [];
        break;
      case 'Elements': case 'elements':
        el._elements = Array.isArray(value) ? value : (typeof value === 'string' ? value.split(',') : []);
        break;
      case 'Selection': case 'selection':
        el._selection = value;
        var idx = (el._elements || []).indexOf(value);
        el._selectionIndex = idx >= 0 ? idx + 1 : 0;
        break;
    }
  }

  // ── Screen Navigation ──────────────────────────────────────────────────
  function navigateTo(screenId) {
    var allScreens = document.querySelectorAll('.screen');
    for (var i = 0; i < allScreens.length; i++) {
      allScreens[i].classList.remove('active');
    }
    var target = document.getElementById('screen-' + screenId);
    if (target) {
      target.classList.add('active');
      currentScreen = screenId;
    }
  }

  function closeScreen() {
    // Go back to first screen
    navigateTo('${screens[0]?.id || 'Screen1'}');
  }

`;

  // Generate screen rendering
  screens.forEach(screen => {
    js += generateScreenRenderer(screen);
  });

  // Generate component proxy objects so block-generated code like
  // Button1.Text or Button1.Text = 'Hello' works seamlessly.
  js += `\n  // ── Component Proxy Objects ──────────────────────────────────────────\n`;
  screens.forEach(screen => {
    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      js += generateComponentProxy(comp);
    });
  });

  // Event handlers from block logic
  js += `
  // ── Block Logic (User-defined) ───────────────────────────────────────
  ${blockCode}

  // ── Initialization ─────────────────────────────────────────────────────
  window.LeapApp = {
    init: function() {
`;

  screens.forEach(screen => {
    js += `      render_${screen.id}();\n`;
  });

  js += `      navigateTo('${screens[0]?.id || 'Screen1'}');
    },
    navigateTo: navigateTo,
    getComponent: getComponent,
    setProperty: setComponentProperty,
    getValue: getComponentValue,
    NativeBridge: NativeBridge,
    state: state
  };

})();
`;

  return js;
}

/**
 * Generate all files needed for the APK injection
 */
function generateWebApp(appState) {
  return {
    'www/index.html': generateIndexHtml(appState),
    'www/styles.css': generateStylesCss(appState),
    'www/app.js': generateAppJs(appState),
    'www/app_config.json': JSON.stringify({
      appName: appState.appName || 'My App',
      packageName: appState.packageName || 'com.leaplab.myapp',
      versionCode: appState.versionCode || 1,
      versionName: appState.versionName || '1.0',
      screens: (appState.screens || []).map(s => s.id)
    }, null, 2)
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function walkComponentTree(list, visitor) {
  if (!list) return;
  for (const item of list) {
    visitor(item);
    if (item.children?.length) walkComponentTree(item.children, visitor);
  }
}

function resolveDimension(value, fallback) {
  if (value === 'fill_parent' || value === -2) return '100%';
  if (value === 'automatic' || value === -1 || value === undefined) return fallback || 'auto';
  if (typeof value === 'number') return value + 'px';
  return value;
}

function generateComponentCss(comp) {
  const { id, type, props = {} } = comp;
  const selector = `#comp-${id}`;
  let rules = '';

  const width = resolveDimension(props.width || props.Width, 'auto');
  const height = resolveDimension(props.height || props.Height, 'auto');
  const bgColor = props.backgroundColor || props.BackgroundColor || 'transparent';
  const textColor = props.textColor || props.TextColor;
  const fontSize = props.fontSize || props.FontSize || 14;
  const bold = props.bold || props.FontBold;
  const italic = props.italic || props.FontItalic;
  const padding = props.padding || 8;
  const margin = props.margin || 4;
  const borderRadius = props.borderRadius || props.Shape === 'rounded' ? 8 : 0;

  rules += `${selector} {\n`;
  if (width !== 'auto') rules += `  width: ${width};\n`;
  if (height !== 'auto') rules += `  height: ${height};\n`;
  if (bgColor !== 'transparent') rules += `  background-color: ${bgColor};\n`;
  if (textColor) rules += `  color: ${textColor};\n`;
  rules += `  font-size: ${fontSize}px;\n`;
  if (bold) rules += `  font-weight: bold;\n`;
  if (italic) rules += `  font-style: italic;\n`;
  rules += `  padding: ${padding}px;\n`;
  rules += `  margin: ${margin}px;\n`;
  if (borderRadius) rules += `  border-radius: ${borderRadius}px;\n`;
  rules += `}\n`;

  return rules;
}

function generateScreenRenderer(screen) {
  const screenId = screen.id;
  const components = screen.components || [];

  let js = `  function render_${screenId}() {\n`;
  js += `    var container = document.createElement('div');\n`;
  js += `    container.id = 'screen-${screenId}';\n`;
  js += `    container.className = 'screen';\n`;

  components.forEach(comp => {
    js += generateComponentCreation(comp, 'container');
  });

  js += `    document.getElementById('app-root').appendChild(container);\n`;
  js += `  }\n\n`;

  return js;
}

function generateComponentCreation(comp, parentVar) {
  const { id, type, props = {}, children } = comp;
  const varName = `el_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
  let js = '';

  switch (type) {
    case 'Button':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Button')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      if (typeof ${id}_Click === 'function') ${id}_Click();\n`;
      js += `    });\n`;
      break;

    case 'Label':
      js += `    var ${varName} = document.createElement('span');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-label';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || '')};\n`;
      break;

    case 'TextBox':
      const multiLine = props.multiLine || props.MultiLine;
      const tag = multiLine ? 'textarea' : 'input';
      js += `    var ${varName} = document.createElement('${tag}');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      if (!multiLine) js += `    ${varName}.type = 'text';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || '')};\n`;
      js += `    ${varName}.value = ${JSON.stringify(props.text || props.Text || '')};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'PasswordTextBox':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      js += `    ${varName}.type = 'password';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || 'Password')};\n`;
      break;

    case 'Image':
      js += `    var ${varName} = document.createElement('img');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-image';\n`;
      js += `    ${varName}.src = ${JSON.stringify(props.picture || props.Picture || '')};\n`;
      js += `    ${varName}.alt = ${JSON.stringify(id)};\n`;
      break;

    case 'CheckBox':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-checkbox';\n`;
      js += `    var ${varName}_cb = document.createElement('input');\n`;
      js += `    ${varName}_cb.type = 'checkbox';\n`;
      js += `    ${varName}_cb.checked = ${Boolean(props.checked || props.Checked)};\n`;
      js += `    ${varName}_cb.addEventListener('change', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.checked);\n`;
      js += `    });\n`;
      js += `    var ${varName}_lbl = document.createElement('span');\n`;
      js += `    ${varName}_lbl.textContent = ${JSON.stringify(props.text || props.Text || 'CheckBox')};\n`;
      js += `    ${varName}.appendChild(${varName}_cb);\n`;
      js += `    ${varName}.appendChild(${varName}_lbl);\n`;
      break;

    case 'Slider':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-slider';\n`;
      js += `    ${varName}.type = 'range';\n`;
      js += `    ${varName}.min = ${props.minValue || props.MinValue || 0};\n`;
      js += `    ${varName}.max = ${props.maxValue || props.MaxValue || 100};\n`;
      js += `    ${varName}.value = ${props.thumbPosition || props.ThumbPosition || 50};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(Number(e.target.value));\n`;
      js += `    });\n`;
      break;

    case 'Switch':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-switch';\n`;
      js += `    var ${varName}_sw = document.createElement('input');\n`;
      js += `    ${varName}_sw.type = 'checkbox';\n`;
      js += `    ${varName}_sw.checked = ${Boolean(props.on || props.On)};\n`;
      js += `    ${varName}_sw.addEventListener('change', function(e) {\n`;
      js += `      if (typeof ${id}_Changed === 'function') ${id}_Changed(e.target.checked);\n`;
      js += `    });\n`;
      js += `    ${varName}.appendChild(${varName}_sw);\n`;
      break;

    case 'ListView':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-listview';\n`;
      const items = props.elements || props.Elements || [];
      const itemsList = typeof items === 'string' ? items.split(',') : items;
      itemsList.forEach((item, idx) => {
        js += `    (function() {\n`;
        js += `      var item = document.createElement('div');\n`;
        js += `      item.className = 'comp-listview-item';\n`;
        js += `      item.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      item.addEventListener('click', function() {\n`;
        js += `        if (typeof ${id}_AfterPicking === 'function') ${id}_AfterPicking(${idx}, item.textContent);\n`;
        js += `      });\n`;
        js += `      ${varName}.appendChild(item);\n`;
        js += `    })();\n`;
      });
      break;

    case 'ListPicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'ListPicker')};\n`;

      const lpItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      js += `    ${varName}._elements = ${JSON.stringify(lpItems)};\n`;
      js += `    ${varName}._selection = '';\n`;
      js += `    ${varName}._selectionIndex = 0;\n`;

      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      if (typeof ${id}_BeforePicking === 'function') ${id}_BeforePicking();\n`;
      js += `      NativeBridge.showListPickerModal(${varName}._elements, function(index, item) {\n`;
      js += `        ${varName}._selection = item;\n`;
      js += `        ${varName}._selectionIndex = index + 1;\n`; // 1-based index for App Inventor
      js += `        if (typeof ${id}_AfterPicking === 'function') ${id}_AfterPicking();\n`;
      js += `      });\n`;
      js += `    });\n`;
      break;

    case 'Spinner':
      js += `    var ${varName} = document.createElement('select');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-spinner';\n`;
      const spinnerItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      const spinnerList = typeof spinnerItems === 'string' ? spinnerItems.split(',') : spinnerItems;
      spinnerList.forEach(item => {
        js += `    (function() {\n`;
        js += `      var opt = document.createElement('option');\n`;
        js += `      opt.value = ${JSON.stringify(String(item).trim())};\n`;
        js += `      opt.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      ${varName}.appendChild(opt);\n`;
        js += `    })();\n`;
      });
      js += `    ${varName}.addEventListener('change', function(e) {\n`;
      js += `      ${varName}._selection = e.target.value;\n`;
      js += `      ${varName}._selectionIndex = e.target.selectedIndex + 1;\n`;
      js += `      if (typeof ${id}_AfterSelecting === 'function') ${id}_AfterSelecting(e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'WebViewer':
      js += `    var ${varName} = document.createElement('iframe');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-webviewer';\n`;
      js += `    ${varName}.src = ${JSON.stringify(props.homeUrl || props.HomeUrl || 'about:blank')};\n`;
      break;

    case 'Canvas':
      js += `    var ${varName} = document.createElement('canvas');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-canvas';\n`;
      js += `    ${varName}.width = ${props.width || 300};\n`;
      js += `    ${varName}.height = ${props.height || 300};\n`;
      js += `    (function(canvas) {\n`;
      js += `      var isDrawing = false;\n`;
      js += `      var lastX = 0, lastY = 0;\n`;
      js += `      var startX = 0, startY = 0;\n`;
      js += `      function getPos(e) {\n`;
      js += `        var rect = canvas.getBoundingClientRect();\n`;
      js += `        var clientX = e.touches ? e.touches[0].clientX : e.clientX;\n`;
      js += `        var clientY = e.touches ? e.touches[0].clientY : e.clientY;\n`;
      js += `        return { x: clientX - rect.left, y: clientY - rect.top };\n`;
      js += `      }\n`;
      js += `      function handleStart(e) {\n`;
      js += `        isDrawing = true;\n`;
      js += `        var pos = getPos(e);\n`;
      js += `        lastX = pos.x; lastY = pos.y;\n`;
      js += `        startX = pos.x; startY = pos.y;\n`;
      js += `        if (typeof window['${id}_TouchDown'] === 'function') window['${id}_TouchDown'](pos.x, pos.y);\n`;
      js += `      }\n`;
      js += `      function handleMove(e) {\n`;
      js += `        if (!isDrawing) return;\n`;
      js += `        e.preventDefault();\n`;
      js += `        var pos = getPos(e);\n`;
      js += `        if (typeof window['${id}_Dragged'] === 'function') window['${id}_Dragged'](startX, startY, lastX, lastY, pos.x, pos.y, false);\n`;
      js += `        lastX = pos.x; lastY = pos.y;\n`;
      js += `      }\n`;
      js += `      function handleEnd(e) {\n`;
      js += `        if (!isDrawing) return;\n`;
      js += `        isDrawing = false;\n`;
      js += `        if (typeof window['${id}_TouchUp'] === 'function') window['${id}_TouchUp'](lastX, lastY);\n`;
      js += `        if (typeof window['${id}_Touched'] === 'function') window['${id}_Touched'](lastX, lastY, false);\n`;
      js += `      }\n`;
      js += `      canvas.addEventListener('mousedown', handleStart);\n`;
      js += `      canvas.addEventListener('mousemove', handleMove);\n`;
      js += `      canvas.addEventListener('mouseup', handleEnd);\n`;
      js += `      canvas.addEventListener('touchstart', handleStart, {passive: false});\n`;
      js += `      canvas.addEventListener('touchmove', handleMove, {passive: false});\n`;
      js += `      canvas.addEventListener('touchend', handleEnd);\n`;
      js += `    })(${varName});\n`;
      break;

    // Layout containers
    case 'HorizontalArrangement':
    case 'HorizontalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'horizontal-scroll' : 'horizontal'}';\n`;
      break;

    case 'VerticalArrangement':
    case 'VerticalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'vertical-scroll' : 'vertical'}';\n`;
      break;

    case 'TableArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-table';\n`;
      const cols = props.columns || props.Columns || 2;
      js += `    ${varName}.style.gridTemplateColumns = 'repeat(${cols}, 1fr)';\n`;
      break;

    default:
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(type + ' (' + id + ')')};\n`;
      break;
  }

  js += `    components['${id}'] = ${varName};\n`;

  // Render children for arrangement containers
  if (children && children.length > 0) {
    children.forEach(child => {
      js += generateComponentCreation(child, varName);
    });
  }

  js += `    ${parentVar}.appendChild(${varName});\n`;

  return js;
}

/**
 * Generate a proxy object for a component so block-generated code
 * like `Button1.Text` or `Button1.Text = 'Hello' works.
 */
function generateComponentProxy(comp) {
  const { id, type, props = {} } = comp;

  // Non-visible shims instantiation
  if (type === 'Clock') {
    return `  var ${id} = new ClockShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'TinyDB') {
    return `  var ${id} = new TinyDBShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Notifier') {
    return `  var ${id} = new NotifierShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Sound' || type === 'Player') {
    return `  var ${id} = new SoundShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'TextToSpeech') {
    return `  var ${id} = new TextToSpeechShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'LocationSensor') {
    return `  var ${id} = new LocationSensorShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Web') {
    return `  var ${id} = new WebShim('${id}', ${JSON.stringify(props)});\n`;
  }

  const propNames = Object.keys(props);
  if (propNames.length === 0 && type !== 'Button' && type !== 'Label') return '';

  // Standard property list based on component type
  const allProps = new Set([
    'Text', 'BackgroundColor', 'TextColor', 'Visible', 'Enabled',
    'Width', 'Height', 'FontSize', 'Hint', 'Picture', 'Checked',
    ...propNames
  ]);

  let js = `  // Proxy: ${id} (${type})\n`;
  js += `  var ${id} = {\n`;

  for (const prop of allProps) {
    const camelProp = prop.charAt(0).toLowerCase() + prop.slice(1);
    js += `    get ${prop}() { return getComponentValue('${id}', '${prop}'); },\n`;
    js += `    set ${prop}(v) { setComponentProperty('${id}', '${prop}', v); },\n`;
  }

  // Add Click handler registration
  if (['Button', 'Label', 'Image', 'ListView', 'CheckBox'].includes(type)) {
    js += `    Click: function() {},\n`;
  }

  js += `  };\n\n`;
  return js;
}

// ── CommonJS Exports ────────────────────────────────────────────────────────

module.exports = {
  generateIndexHtml,
  generateStylesCss,
  generateAppJs,
  generateWebApp,
  generateComponentProxy
};
