/**
 * HTML/CSS/JS Generator for AppInverter → APK Injection
 *
 * Converts AppInverter state (screens, components, block logic)
 * into a complete mobile web application (HTML + CSS + JS).
 * This output is injected into a WebView-based APK template.
 *
 * Works in both Electron and browser environments.
 * Uses CommonJS exports for Node.js (Electron main process) compatibility.
 */

/**
 * Generate the complete index.html for the app
 */
function generateIndexHtml(appState) {
  const { appName, screens } = appState;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <title>${escapeHtml(appName || 'My App')}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div id="app-root">
    <div class="startup-loading">Loading app...</div>
  </div>
  <script src="app.js"><\/script>
  <script>
    (function() {
      function showStartupError(message) {
        var root = document.getElementById('app-root');
        if (!root) return;
        root.innerHTML = '';
        var errorBox = document.createElement('div');
        errorBox.className = 'startup-error';
        var title = document.createElement('strong');
        title.textContent = 'App failed to start';
        var detail = document.createElement('span');
        detail.textContent = message || 'Unknown runtime error';
        errorBox.appendChild(title);
        errorBox.appendChild(detail);
        root.appendChild(errorBox);
      }

      function startLeapApp() {
        try {
          if (!window.LeapApp || typeof window.LeapApp.init !== 'function') {
            throw new Error('Generated app runtime was not loaded.');
          }
          window.LeapApp.init();
        } catch (error) {
          showStartupError(error && error.message ? error.message : String(error));
        }
      }

      window.addEventListener('unhandledrejection', function(event) {
        var reason = event.reason;
        showStartupError(reason && reason.message ? reason.message : String(reason || 'Unhandled promise rejection'));
      });

      if (document.readyState === 'complete' || document.readyState === 'interactive') {
        startLeapApp();
      } else {
        document.addEventListener('DOMContentLoaded', startLeapApp);
      }
    })();
  </script>
</body>
</html>`;
}

const DEFAULT_DESIGN_VIEWPORT = { width: 412, height: 915 };

function firstDefined(...values) {
  for (const value of values) {
    if (value !== undefined && value !== null) return value;
  }
  return undefined;
}

function positiveNumber(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function getDesignViewport(appState) {
  const viewport = appState?.designViewport || {};
  const firstScreen = Array.isArray(appState?.screens) ? appState.screens[0] : null;
  const orientation = String(
    firstDefined(viewport.orientation, firstScreen?.screenOrientation, firstScreen?.ScreenOrientation, '')
  ).toLowerCase();
  const fallback = orientation === 'landscape'
    ? { width: DEFAULT_DESIGN_VIEWPORT.height, height: DEFAULT_DESIGN_VIEWPORT.width }
    : DEFAULT_DESIGN_VIEWPORT;

  return {
    width: positiveNumber(firstDefined(viewport.width, appState?.designWidth, firstScreen?.designWidth), fallback.width),
    height: positiveNumber(firstDefined(viewport.height, appState?.designHeight, firstScreen?.designHeight), fallback.height)
  };
}

/**
 * Generate the CSS stylesheet for the app
 */
function generateStylesCss(appState) {
  const screens = Array.isArray(appState.screens) && appState.screens.length
    ? appState.screens
    : [{ id: 'Screen1', components: [], nonVisibleComponents: [] }];
  const designViewport = getDesignViewport(appState);

  let css = `/* Auto-generated by LeapLab AppInverter */
* { margin: 0; padding: 0; box-sizing: border-box; }

html, body {
  width: 100%;
  height: 100%;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  overflow: hidden;
  -webkit-tap-highlight-color: transparent;
  -webkit-text-size-adjust: 100%;
}

#app-root {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #0f172a;
}

.startup-loading,
.startup-error {
  min-height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  color: #1f2937;
  font: 600 16px/1.4 -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.startup-error {
  flex-direction: column;
  gap: 8px;
  background: #fff7ed;
  color: #9a3412;
  text-align: center;
}

.startup-error span {
  max-width: 520px;
  color: #7c2d12;
  font-size: 13px;
  font-weight: 500;
}

.screen {
  width: 100%;
  height: 100%;
  display: none;
  position: absolute;
  inset: 0;
  overflow: hidden;
  align-items: center;
  justify-content: center;
  background: #0f172a;
}

.screen.active {
  display: flex;
}

.screen-viewport {
  width: ${designViewport.width}px;
  height: ${designViewport.height}px;
  flex: 0 0 auto;
  position: relative;
  overflow: hidden;
  background: #ffffff;
  transform-origin: center center;
  -webkit-font-smoothing: antialiased;
}

.screen-inner {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
  min-height: 0;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  padding: 8px;
  gap: 5px;
}

/* Component base styles */
.comp-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  outline: none;
  -webkit-appearance: none;
  touch-action: manipulation;
  user-select: none;
  font-family: sans-serif;
}

.comp-button:active {
  opacity: 0.75;
  transform: scale(0.97);
}

.comp-label {
  display: inline;
}

.comp-textbox {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
}

.comp-textbox:focus {
  border-color: #4285f4;
  box-shadow: 0 0 0 2px rgba(66,133,244,0.2);
}

.comp-image {
  display: block;
  object-fit: contain;
}

.comp-checkbox {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}

.comp-checkbox input[type="checkbox"] {
  width: 20px;
  height: 20px;
  accent-color: #4285f4;
}

.comp-slider {
  display: block;
  width: 100%;
  -webkit-appearance: none;
  height: 6px;
  border-radius: 3px;
  background: #ddd;
  outline: none;
}

.comp-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  background: #4285f4;
  cursor: pointer;
}

.comp-switch {
  display: flex;
  align-items: center;
  gap: 8px;
}

.comp-listview {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
  border: 1px solid #e0e0e0;
}

.comp-listview-item {
  padding: 12px 16px;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;
}

.comp-listview-item:active {
  background: #e8f0fe;
}

.comp-spinner {
  display: block;
  border: 1px solid #ccc;
  outline: none;
  -webkit-appearance: none;
  background: white;
  cursor: pointer;
}

.comp-datepicker, .comp-timepicker {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  border: 1px solid #ccc;
  background: white;
}

.comp-webviewer {
  border: none;
  display: block;
}

.comp-canvas {
  display: block;
  touch-action: none;
}

/* Arrangement containers */
.arrangement-horizontal {
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
}

.arrangement-vertical {
  display: flex;
  flex-direction: column;
}

.arrangement-horizontal-scroll {
  display: flex;
  flex-direction: row;
  overflow-x: auto;
  flex-wrap: nowrap;
}

.arrangement-vertical-scroll {
  display: flex;
  flex-direction: column;
  overflow-y: auto;
}

.arrangement-table {
  display: grid;
}

.arrangement-absolute {
  position: relative;
}

/* Notification / Toast */
.toast-notification {
  position: fixed;
  bottom: 80px;
  left: 50%;
  transform: translateX(-50%);
  background: rgba(0,0,0,0.8);
  color: white;
  padding: 12px 24px;
  border-radius: 24px;
  font-size: 14px;
  z-index: 9999;
  animation: toast-in 0.3s ease, toast-out 0.3s ease 2.7s;
  pointer-events: none;
}

@keyframes toast-in {
  from { opacity: 0; transform: translateX(-50%) translateY(20px); }
  to { opacity: 1; transform: translateX(-50%) translateY(0); }
}

@keyframes toast-out {
  from { opacity: 1; }
  to { opacity: 0; }
}
`;

  // Per-component styles
  screens.forEach(screen => {
    const bgColor = screen.backgroundColor || '#ffffff';
    const bgImage = screen.backgroundImage || screen.BackgroundImage || '';
    let screenCss = `${cssIdSelector('screen-' + screen.id)} .screen-viewport { background-color: ${bgColor};`;
    if (bgImage) screenCss += ` background-image: url(${mediaUrl(bgImage)}); background-size: 100% 100%;`;
    screenCss += ` }\n`;
    css += screenCss;

    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      css += generateComponentCss(comp);
    });
  });

  return css;
}

/**
 * Generate the JavaScript application code
 */
function generateAppJs(appState) {
  const { blockLogic } = appState;
  const screens = Array.isArray(appState.screens) && appState.screens.length
    ? appState.screens
    : [{ id: 'Screen1', title: 'Screen1', components: [], nonVisibleComponents: [] }];
  const designViewport = getDesignViewport(appState);
  validateComponentIdentifiers(screens);
  const firstScreenId = screens[0]?.id || 'Screen1';
  let blockCode = '';

  // If blockLogic is XML, we note it — the actual code generation
  // should happen via Blockly's JS generator before calling this.
  // If it's already JS, use it directly.
  if (blockLogic && !blockLogic.trim().startsWith('<')) {
    blockCode = blockLogic;
  }

  let js = `/* Auto-generated by LeapLab AppInverter */
(function() {
  'use strict';

  // ── App State ──────────────────────────────────────────────────────────
  var state = {};
  var currentScreen = ${JSON.stringify(firstScreenId)};
  var components = {};
  var DESIGN_WIDTH = ${designViewport.width};
  var DESIGN_HEIGHT = ${designViewport.height};

  function showRuntimeError(message) {
    var root = document.getElementById('app-root');
    if (!root) return;
    root.innerHTML = '';
    var box = document.createElement('div');
    box.className = 'startup-error';
    var title = document.createElement('strong');
    title.textContent = 'App failed to render';
    var detail = document.createElement('span');
    detail.textContent = message || 'Unknown runtime error';
    box.appendChild(title);
    box.appendChild(detail);
    root.appendChild(box);
  }

  // ── Native Bridge ──────────────────────────────────────────────────────
  var NativeBridge = {
    showAlert: function(title, message) {
      alert(message);
    },
    showToast: function(message) {
      var toast = document.createElement('div');
      toast.className = 'toast-notification';
      toast.textContent = message;
      document.body.appendChild(toast);
      setTimeout(function() { toast.remove(); }, 3000);
    },
    showListPickerModal: function(elements, callback) {
      var overlay = document.createElement('div');
      overlay.style.position = 'fixed';
      overlay.style.top = '0'; overlay.style.left = '0';
      overlay.style.width = '100%'; overlay.style.height = '100%';
      overlay.style.backgroundColor = 'rgba(0,0,0,0.5)';
      overlay.style.zIndex = '10000';
      overlay.style.display = 'flex';
      overlay.style.flexDirection = 'column';
      
      var modal = document.createElement('div');
      modal.style.backgroundColor = '#fff';
      modal.style.width = '80%';
      modal.style.maxWidth = '400px';
      modal.style.maxHeight = '80%';
      modal.style.margin = 'auto';
      modal.style.borderRadius = '8px';
      modal.style.overflowY = 'auto';
      modal.style.boxShadow = '0 4px 6px rgba(0,0,0,0.1)';

      if (!elements || elements.length === 0) {
        var emptyMsg = document.createElement('div');
        emptyMsg.textContent = 'No elements to pick';
        emptyMsg.style.padding = '16px';
        modal.appendChild(emptyMsg);
      } else {
        elements.forEach(function(item, index) {
          var itemDiv = document.createElement('div');
          itemDiv.textContent = item;
          itemDiv.style.padding = '16px';
          itemDiv.style.borderBottom = '1px solid #eee';
          itemDiv.style.cursor = 'pointer';
          itemDiv.addEventListener('click', function() {
            document.body.removeChild(overlay);
            callback(index, item);
          });
          modal.appendChild(itemDiv);
        });
      }

      var closeBtn = document.createElement('div');
      closeBtn.textContent = 'Cancel';
      closeBtn.style.padding = '16px';
      closeBtn.style.textAlign = 'center';
      closeBtn.style.color = '#4285f4';
      closeBtn.style.fontWeight = 'bold';
      closeBtn.style.cursor = 'pointer';
      closeBtn.addEventListener('click', function() {
        document.body.removeChild(overlay);
      });
      modal.appendChild(closeBtn);

      overlay.appendChild(modal);
      document.body.appendChild(overlay);
    },
    vibrate: function(ms) {
      if (navigator.vibrate) navigator.vibrate(ms || 200);
    },
    openUrl: function(url) {
      window.open(url, '_blank');
    },
    playSound: function(src) {
      try { new Audio(src).play(); } catch(e) {}
    },
    getStorageItem: function(key) {
      try { return localStorage.getItem('leapapp_' + key); } catch(e) { return null; }
    },
    setStorageItem: function(key, value) {
      try { localStorage.setItem('leapapp_' + key, value); } catch(e) {}
    }
  };

  // ── React Native Compatibility Shims ───────────────────────────────────
  // Maps block-generated RN code (navigation, Alert, Vibration) to web APIs
  var navigation = {
    navigate: function(screen) { navigateTo(screen); },
    goBack: function() { closeScreen(); }
  };
  var Alert = {
    alert: function(msg) { NativeBridge.showAlert('Alert', msg); }
  };
  var Vibration = {
    vibrate: function(ms) { NativeBridge.vibrate(ms); }
  };

  // ── Non-Visible Component Shims ────────────────────────────────────────
  function ClockShim(id, props) {
    this.id = id;
    this._timerEnabled = props.TimerEnabled !== undefined ? !!props.TimerEnabled : true;
    this._timerInterval = props.TimerInterval !== undefined ? Number(props.TimerInterval) : 1000;
    this._timerId = null;
    this.updateTimer();
  }
  ClockShim.prototype = {
    get TimerEnabled() { return this._timerEnabled; },
    set TimerEnabled(v) { this._timerEnabled = !!v; this.updateTimer(); },
    get TimerInterval() { return this._timerInterval; },
    set TimerInterval(v) { this._timerInterval = Number(v); this.updateTimer(); },
    updateTimer: function() {
      if (this._timerId) clearInterval(this._timerId);
      if (this._timerEnabled && this._timerInterval > 0) {
        var self = this;
        this._timerId = setInterval(function() {
          if (typeof window[self.id + '_Timer'] === 'function') {
            window[self.id + '_Timer']();
          }
        }, this._timerInterval);
      }
    },
    Now: function() { return new Date(); },
    SystemTime: function() { return Date.now(); },
    MakeInstant: function(text) { return new Date(text); },
    MakeInstantFromMillis: function(m) { return new Date(Number(m)); },
    GetMillis: function(instant) { return (instant instanceof Date ? instant : new Date(instant)).getTime(); },
    AddDays: function(instant, days) {
      var d = new Date(instant);
      d.setDate(d.getDate() + Number(days));
      return d;
    },
    AddHours: function(instant, hours) {
      var d = new Date(instant);
      d.setHours(d.getHours() + Number(hours));
      return d;
    },
    AddMinutes: function(instant, minutes) {
      var d = new Date(instant);
      d.setMinutes(d.getMinutes() + Number(minutes));
      return d;
    },
    AddSeconds: function(instant, seconds) {
      var d = new Date(instant);
      d.setSeconds(d.getSeconds() + Number(seconds));
      return d;
    },
    AddWeeks: function(instant, weeks) {
      var d = new Date(instant);
      d.setDate(d.getDate() + (Number(weeks) * 7));
      return d;
    },
    AddMonths: function(instant, months) {
      var d = new Date(instant);
      d.setMonth(d.getMonth() + Number(months));
      return d;
    },
    AddYears: function(instant, years) {
      var d = new Date(instant);
      d.setFullYear(d.getFullYear() + Number(years));
      return d;
    },
    Duration: function(start, end) {
      return Math.abs(new Date(end).getTime() - new Date(start).getTime());
    },
    DurationToDays: function(dur) { return dur / (24 * 3600 * 1000); },
    DurationToHours: function(dur) { return dur / (3600 * 1000); },
    DurationToMinutes: function(dur) { return dur / (60 * 1000); },
    DurationToSeconds: function(dur) { return dur / 1000; },
    DurationToWeeks: function(dur) { return dur / (7 * 24 * 3600 * 1000); },
    FormatDate: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleDateString(); },
    FormatDateTime: function(inst, pattern) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleString(); },
    FormatTime: function(inst) { return (inst instanceof Date ? inst : new Date(inst)).toLocaleTimeString(); }
  };

  function TinyDBShim(id, props) {
    this.id = id;
    this._namespace = props.Namespace || id;
  }
  TinyDBShim.prototype = {
    get Namespace() { return this._namespace; },
    set Namespace(v) { this._namespace = v; },
    _getKey: function(tag) { return 'tinydb_' + this._namespace + '_' + tag; },
    StoreValue: function(tag, val) {
      try { localStorage.setItem(this._getKey(tag), JSON.stringify(val)); } catch(e) {}
    },
    GetValue: function(tag, fallback) {
      try {
        var v = localStorage.getItem(this._getKey(tag));
        return v === null ? fallback : JSON.parse(v);
      } catch(e) { return fallback; }
    },
    ClearTag: function(tag) {
      try { localStorage.removeItem(this._getKey(tag)); } catch(e) {}
    },
    ClearAll: function() {
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        var keysToRemove = [];
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) keysToRemove.push(key);
        }
        keysToRemove.forEach(function(k) { localStorage.removeItem(k); });
      } catch(e) {}
    },
    GetTags: function() {
      var tags = [];
      try {
        var prefix = 'tinydb_' + this._namespace + '_';
        for (var i = 0; i < localStorage.length; i++) {
          var key = localStorage.key(i);
          if (key.indexOf(prefix) === 0) tags.push(key.substring(prefix.length));
        }
      } catch(e) {}
      return tags;
    }
  };

  function NotifierShim(id) {
    this.id = id;
  }
  NotifierShim.prototype = {
    ShowAlert: function(notice) {
      NativeBridge.showToast(notice);
    },
    ShowMessageDialog: function(message, title, buttonText) {
      var sep = String.fromCharCode(10, 10);
      alert((title ? title + sep : "") + message);
    },
    ShowChooseDialog: function(message, title, button1, button2, cancelable) {
      var sep = String.fromCharCode(10, 10);
      var res = confirm((title ? title + sep : "") + message);
      var choice = res ? button1 : button2;
      var self = this;
      setTimeout(function() {
        if (typeof window[self.id + '_AfterChoosing'] === 'function') {
          window[self.id + '_AfterChoosing'](choice);
        }
      }, 50);
    },
    ShowTextDialog: function(message, title, cancelable) {
      var sep = String.fromCharCode(10, 10);
      var res = prompt((title ? title + sep : "") + message);
      var self = this;
      if (res !== null) {
        setTimeout(function() {
          if (typeof window[self.id + '_AfterTextInput'] === 'function') {
            window[self.id + '_AfterTextInput'](res);
          }
        }, 50);
      }
    }
  };

  function SoundShim(id, props) {
    this.id = id;
    var src = props.Source || props.source || '';
    this._source = (src && !src.startsWith('http') && !src.startsWith('data:') && !src.startsWith('file:') && !src.startsWith('blob:')) ? 'media/' + src : src;
    this._volume = props.Volume !== undefined ? Number(props.Volume) : 1.0;
    this._isLooping = !!props.IsLooping;
    this._audio = null;
  }
  SoundShim.prototype = {
    get Source() { return this._source; },
    set Source(v) {
      this._source = v;
      if (this._audio) this._audio.src = v;
    },
    get Volume() { return this._volume; },
    set Volume(v) {
      this._volume = Number(v);
      if (this._audio) this._audio.volume = this._volume;
    },
    get IsLooping() { return this._isLooping; },
    set IsLooping(v) {
      this._isLooping = !!v;
      if (this._audio) this._audio.loop = this._isLooping;
    },
    _initAudio: function() {
      if (!this._audio && this._source) {
        this._audio = new Audio(this._source);
        this._audio.volume = this._volume;
        this._audio.loop = this._isLooping;
        var self = this;
        this._audio.addEventListener('ended', function() {
          if (typeof window[self.id + '_Completed'] === 'function') {
            window[self.id + '_Completed']();
          }
        });
      }
    },
    Play: function() {
      this._initAudio();
      if (this._audio) this._audio.play().catch(function(e){});
    },
    Start: function() { this.Play(); },
    Pause: function() {
      if (this._audio) this._audio.pause();
    },
    Stop: function() {
      if (this._audio) {
        this._audio.pause();
        this._audio.currentTime = 0;
      }
    },
    Resume: function() { this.Play(); },
    Vibrate: function(ms) {
      NativeBridge.vibrate(ms);
    }
  };

  function TextToSpeechShim(id) {
    this.id = id;
    this._pitch = 1.0;
    this._speechRate = 1.0;
  }
  TextToSpeechShim.prototype = {
    get Pitch() { return this._pitch; },
    set Pitch(v) { this._pitch = Number(v); },
    get SpeechRate() { return this._speechRate; },
    set SpeechRate(v) { this._speechRate = Number(v); },
    Speak: function(message) {
      if (!window.speechSynthesis) return;
      var self = this;
      if (typeof window[self.id + '_BeforeSpeaking'] === 'function') {
        window[self.id + '_BeforeSpeaking']();
      }
      var utterance = new SpeechSynthesisUtterance(message);
      utterance.pitch = this._pitch;
      utterance.rate = this._speechRate;
      utterance.onend = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](true);
        }
      };
      utterance.onerror = function() {
        if (typeof window[self.id + '_AfterSpeaking'] === 'function') {
          window[self.id + '_AfterSpeaking'](false);
        }
      };
      window.speechSynthesis.speak(utterance);
    }
  };

  function LocationSensorShim(id, props) {
    this.id = id;
    this._enabled = props.Enabled !== undefined ? !!props.Enabled : true;
    this._latitude = 0;
    this._longitude = 0;
    this._altitude = 0;
    this._accuracy = 0;
    this._watchId = null;
    this.updateWatcher();
  }
  LocationSensorShim.prototype = {
    get Enabled() { return this._enabled; },
    set Enabled(v) { this._enabled = !!v; this.updateWatcher(); },
    get Latitude() { return this._latitude; },
    get Longitude() { return this._longitude; },
    get Altitude() { return this._altitude; },
    get Accuracy() { return this._accuracy; },
    updateWatcher: function() {
      if (this._watchId) {
        navigator.geolocation.clearWatch(this._watchId);
        this._watchId = null;
      }
      if (this._enabled && navigator.geolocation) {
        var self = this;
        this._watchId = navigator.geolocation.watchPosition(function(pos) {
          self._latitude = pos.coords.latitude;
          self._longitude = pos.coords.longitude;
          self._altitude = pos.coords.altitude || 0;
          self._accuracy = pos.coords.accuracy || 0;
          if (typeof window[self.id + '_LocationChanged'] === 'function') {
            window[self.id + '_LocationChanged'](self._latitude, self._longitude, self._altitude, pos.coords.speed || 0);
          }
        }, function(err) {}, { enableHighAccuracy: true });
      }
    }
  };

  function WebShim(id, props) {
    this.id = id;
    this._url = props.Url || props.url || '';
    this._timeout = props.Timeout !== undefined ? Number(props.Timeout) : 0;
    this._saveResponse = !!props.SaveResponse;
    this._responseFileName = props.ResponseFileName || '';
    this._allowCookies = props.AllowCookies !== undefined ? !!props.AllowCookies : true;
    this._headers = {};
  }
  WebShim.prototype = {
    get Url() { return this._url; },
    set Url(v) { this._url = v; },
    get Timeout() { return this._timeout; },
    set Timeout(v) { this._timeout = Number(v) || 0; },
    get SaveResponse() { return this._saveResponse; },
    set SaveResponse(v) { this._saveResponse = !!v; },
    get ResponseFileName() { return this._responseFileName; },
    set ResponseFileName(v) { this._responseFileName = String(v || ''); },
    get AllowCookies() { return this._allowCookies; },
    set AllowCookies(v) { this._allowCookies = !!v; },
    _emitGotText: function(url, status, responseType, content) {
      if (typeof window[this.id + '_GotText'] === 'function') {
        window[this.id + '_GotText'](url, status, responseType || '', content || '');
      }
    },
    _emitTimedOut: function(url) {
      if (typeof window[this.id + '_TimedOut'] === 'function') {
        window[this.id + '_TimedOut'](url || this._url);
      }
    },
    _emitGotFile: function(url, status, responseType, fileName) {
      if (typeof window[this.id + '_GotFile'] === 'function') {
        window[this.id + '_GotFile'](url, status, responseType || '', fileName || '');
      }
    },
    _request: function(method, body, contentType) {
      var self = this;
      var controller = (typeof AbortController !== 'undefined') ? new AbortController() : null;
      var timeoutId = null;
      if (controller && self._timeout > 0) {
        timeoutId = setTimeout(function() { controller.abort(); }, self._timeout);
      }
      var options = {
        method: method || 'GET',
        body: body,
        headers: {}
      };
      if (contentType) options.headers['Content-Type'] = contentType;
      if (controller) options.signal = controller.signal;

      fetch(this._url, options)
        .then(function(res) {
          if (timeoutId) clearTimeout(timeoutId);
          var responseType = res.headers.get('content-type') || '';
          if (self._saveResponse) {
            return res.blob().then(function(blob) {
              var fileName = self._responseFileName || ('response_' + Date.now());
              // Browser/WebView-safe pseudo-file path signal for blocks.
              self._emitGotFile(self._url, res.status, responseType, fileName);
            });
          }
          return res.text().then(function(text) {
            self._emitGotText(self._url, res.status, responseType, text);
          });
        })
        .catch(function(err) {
          if (timeoutId) clearTimeout(timeoutId);
          if (err && err.name === 'AbortError') {
            self._emitTimedOut(self._url);
          } else {
            self._emitGotText(self._url, 0, '', err && err.message ? err.message : String(err));
          }
        });
    },
    Get: function() {
      this._request('GET');
    },
    PostText: function(text) {
      this._request('POST', text, 'text/plain');
    },
    PostTextWithEncoding: function(text, encoding) {
      var enc = encoding || 'utf-8';
      this._request('POST', text, 'text/plain; charset=' + enc);
    },
    PostFile: function(path) {
      this._emitGotText(this._url, 0, '', 'PostFile is not available in this runtime.');
    },
    PutText: function(text) {
      this._request('PUT', text, 'text/plain');
    },
    PutTextWithEncoding: function(text, encoding) {
      var enc = encoding || 'utf-8';
      this._request('PUT', text, 'text/plain; charset=' + enc);
    },
    PutFile: function(path) {
      this._emitGotText(this._url, 0, '', 'PutFile is not available in this runtime.');
    },
    PatchText: function(text) {
      this._request('PATCH', text, 'text/plain');
    },
    PatchTextWithEncoding: function(text, encoding) {
      var enc = encoding || 'utf-8';
      this._request('PATCH', text, 'text/plain; charset=' + enc);
    },
    PatchFile: function(path) {
      this._emitGotText(this._url, 0, '', 'PatchFile is not available in this runtime.');
    },
    Delete: function() {
      this._request('DELETE');
    },
    ClearCookies: function() {
      // No-op in pure WebView JS runtime; browser controls cookie jar.
    },
    BuildRequestData: function(list) {
      if (!Array.isArray(list)) return '';
      return list.map(function(pair) {
        var k = encodeURIComponent(String(pair[0] || ''));
        var v = encodeURIComponent(String(pair[1] || ''));
        return k + '=' + v;
      }).join('&');
    },
    JsonTextDecode: function(jsonText) {
      return JSON.parse(jsonText);
    },
    JsonTextDecodeWithDictionaries: function(jsonText) {
      return JSON.parse(jsonText);
    },
    JsonObjectEncode: function(obj) {
      return JSON.stringify(obj);
    },
    HtmlTextDecode: function(htmlText) {
      var textarea = document.createElement('textarea');
      textarea.innerHTML = String(htmlText || '');
      return textarea.value;
    },
    UriEncode: function(text) {
      return encodeURIComponent(String(text || ''));
    },
    UriDecode: function(text) {
      try { return decodeURIComponent(String(text || '')); } catch (e) { return String(text || ''); }
    }
  };

  function extractMacAddress(address) {
    if (!address) return '';
    address = String(address).trim();
    if (address.includes('\\n')) {
      var parts = address.split('\\n');
      return parts[parts.length - 1].trim();
    }
    if (address.includes(' ')) {
      var parts = address.split(' ');
      for (var i = parts.length - 1; i >= 0; i--) {
        var p = parts[i].trim();
        if (p.includes(':') && p.length >= 12) {
          return p;
        }
      }
    }
    return address;
  }

  function BluetoothConnectionBaseShim(id, props) {
    this.id = id;
    this._enabled = props.Enabled !== undefined ? !!props.Enabled : true;
    this._isConnected = false;
    this._secure = props.Secure !== undefined ? !!props.Secure : false;
    this._delimiterByte = props.DelimiterByte !== undefined ? Number(props.DelimiterByte) : 10;
    this._characterEncoding = props.CharacterEncoding || 'utf-8';
    this._highByteFirst = props.HighByteFirst !== undefined ? !!props.HighByteFirst : false;
    this._buffer = [];
  }
  BluetoothConnectionBaseShim.prototype = {
    _emitError: function(functionName, message) {
      if (typeof window[this.id + '_BluetoothError'] === 'function') {
        window[this.id + '_BluetoothError'](functionName, message);
      } else {
        alert('Bluetooth Error in ' + functionName + ': ' + message);
      }
    },
    get Enabled() { return this._enabled; },
    set Enabled(v) { this._enabled = !!v; },
    get IsConnected() {
      // Use native bridge status when available
      if (window.Android && typeof window.Android.isConnected === 'function') {
        try { return window.Android.isConnected(); } catch(e) {}
      }
      return this._isConnected;
    },
    set IsConnected(v) { this._isConnected = !!v; },
    get Available() { return (typeof navigator !== 'undefined' && !!navigator.bluetooth) || !!window.Android; },
    get Secure() { return this._secure; },
    set Secure(v) { this._secure = !!v; },
    get DelimiterByte() { return this._delimiterByte; },
    set DelimiterByte(v) { this._delimiterByte = Number(v) || 0; },
    get CharacterEncoding() { return this._characterEncoding; },
    set CharacterEncoding(v) { this._characterEncoding = String(v || 'utf-8'); },
    get HighByteFirst() { return this._highByteFirst; },
    set HighByteFirst(v) { this._highByteFirst = !!v; },
    Disconnect: function() {
      // Use native bridge disconnect when available
      if (window.Android && typeof window.Android.disconnect === 'function') {
        try { window.Android.disconnect(); } catch(e) {}
      }
      this._isConnected = false;
    },
    BytesAvailableToReceive: function() { return this._buffer.length; },
    ReceiveText: function(numberOfBytes) {
      // Try native bridge first
      if (window.Android && typeof window.Android.receiveText === 'function') {
        try {
          var nativeText = window.Android.receiveText();
          if (nativeText) return nativeText;
        } catch(e) {}
      }
      var count = Number(numberOfBytes);
      if (!Number.isFinite(count) || count < 0) count = this._buffer.length;
      var chunk = this._buffer.splice(0, count);
      return chunk.join('');
    },
    ReceiveSigned1ByteNumber: function() { return 0; },
    ReceiveSigned2ByteNumber: function() { return 0; },
    ReceiveSigned4ByteNumber: function() { return 0; },
    ReceiveUnsigned1ByteNumber: function() { return 0; },
    ReceiveUnsigned2ByteNumber: function() { return 0; },
    ReceiveUnsigned4ByteNumber: function() { return 0; },
    ReceiveSignedBytes: function(numberOfBytes) {
      var t = this.ReceiveText(numberOfBytes);
      return t.split('').map(function(c) { return c.charCodeAt(0) | 0; });
    },
    ReceiveUnsignedBytes: function(numberOfBytes) {
      var t = this.ReceiveText(numberOfBytes);
      return t.split('').map(function(c) { return c.charCodeAt(0) & 255; });
    },
    SendText: function(text) {
      // Use native bridge when available
      if (window.Android && typeof window.Android.sendText === 'function') {
        try {
          window.Android.sendText(String(text));
          return;
        } catch(e) {}
      }
      if (!this._isConnected) this._emitError('SendText', 'Not connected');
    },
    Send1ByteNumber: function(number) { this.SendText(String(number)); },
    Send2ByteNumber: function(number) { this.SendText(String(number)); },
    Send4ByteNumber: function(number) { this.SendText(String(number)); },
    SendBytes: function(list) { this.SendText(Array.isArray(list) ? list.join(',') : String(list)); }
  };

  function BluetoothClientShim(id, props) {
    BluetoothConnectionBaseShim.call(this, id, props || {});
    this._disconnectOnError = props.DisconnectOnError !== undefined ? !!props.DisconnectOnError : true;
    this._noLocationNeeded = props.NoLocationNeeded !== undefined ? !!props.NoLocationNeeded : false;
    this._pollingRate = props.PollingRate !== undefined ? Number(props.PollingRate) : 100;
    this._addressesAndNames = [];
  }
  BluetoothClientShim.prototype = Object.create(BluetoothConnectionBaseShim.prototype);
  BluetoothClientShim.prototype.constructor = BluetoothClientShim;
  Object.defineProperty(BluetoothClientShim.prototype, 'AddressesAndNames', {
    get: function() {
      // If native Android bridge is available, fetch paired devices
      if (window.Android && typeof window.Android.getPairedDevices === 'function') {
        try {
          var json = window.Android.getPairedDevices();
          var devices = JSON.parse(json);
          this._addressesAndNames = devices.map(function(d) { return d.name + '\\n' + d.address; });
        } catch(e) {}
      }
      return this._addressesAndNames;
    }
  });
  Object.defineProperty(BluetoothClientShim.prototype, 'DisconnectOnError', {
    get: function() { return this._disconnectOnError; },
    set: function(v) { this._disconnectOnError = !!v; }
  });
  Object.defineProperty(BluetoothClientShim.prototype, 'NoLocationNeeded', {
    get: function() { return this._noLocationNeeded; },
    set: function(v) { this._noLocationNeeded = !!v; }
  });
  Object.defineProperty(BluetoothClientShim.prototype, 'PollingRate', {
    get: function() { return this._pollingRate; },
    set: function(v) { this._pollingRate = Number(v) || 100; }
  });
  BluetoothClientShim.prototype.Connect = function(address) {
    var self = this;
    if (!this._enabled) { this._emitError('Connect', 'Bluetooth is disabled'); return false; }
    address = extractMacAddress(address);
    // Try native Android bridge first (available in APK WebView)
    if (window.Android && typeof window.Android.connect === 'function') {
      try {
        var result = window.Android.connect(address);
        if (result === 'SUCCESS') {
          self._isConnected = true;
          return true;
        }
        this._emitError('Connect', 'Connection failed: ' + result);
        return false;
      } catch(err) {
        this._emitError('Connect', 'Native Bluetooth error: ' + (err.message || String(err)));
        return false;
      }
    }
    // Fallback: Web Bluetooth API (works in Chrome, not in standard WebView)
    if (typeof navigator === 'undefined' || !navigator.bluetooth || !navigator.bluetooth.requestDevice) {
      this._emitError('Connect', 'Bluetooth API not available in this WebView');
      return false;
    }
    navigator.bluetooth.requestDevice({ acceptAllDevices: true, optionalServices: [] })
      .then(function(device) {
        self._addressesAndNames = [device.name || 'Bluetooth Device'];
        if (!device.gatt) {
          self._isConnected = true;
          return null;
        }
        return device.gatt.connect().then(function() { self._isConnected = true; });
      })
      .catch(function(err) {
        self._isConnected = false;
        self._emitError('Connect', err && err.message ? err.message : String(err));
      });
    return true;
  };
  BluetoothClientShim.prototype.ConnectWithUUID = function(address, uuid) {
    return this.Connect(address);
  };
  BluetoothClientShim.prototype.IsDevicePaired = function(address) {
    address = extractMacAddress(address);
    // Native Android bridge: check paired devices list
    if (window.Android && typeof window.Android.getPairedDevices === 'function') {
      try {
        var json = window.Android.getPairedDevices();
        var devices = JSON.parse(json);
        for (var i = 0; i < devices.length; i++) {
          if (devices[i].address === address) return true;
        }
      } catch(e) {}
    }
    return false;
  };

  function BluetoothServerShim(id, props) {
    BluetoothConnectionBaseShim.call(this, id, props || {});
    this._accepting = false;
  }
  BluetoothServerShim.prototype = Object.create(BluetoothConnectionBaseShim.prototype);
  BluetoothServerShim.prototype.constructor = BluetoothServerShim;
  BluetoothServerShim.prototype.AcceptConnection = function(serviceName) {
    this._accepting = true;
    if (typeof window[this.id + '_ConnectionAccepted'] === 'function') {
      window[this.id + '_ConnectionAccepted']();
    }
  };
  BluetoothServerShim.prototype.AcceptConnectionWithUUID = function(serviceName, uuid) {
    this.AcceptConnection(serviceName);
  };
  BluetoothServerShim.prototype.StopAccepting = function() {
    this._accepting = false;
  };

  // ── Color Utilities ────────────────────────────────────────────────────
  function parseColor(color) {
    try {
      var canvas = document.createElement('canvas');
      var ctx = canvas.getContext('2d');
      ctx.fillStyle = color;
      var resolved = ctx.fillStyle;
      if (resolved.charAt(0) === '#') {
        return [
          parseInt(resolved.substring(1, 3), 16),
          parseInt(resolved.substring(3, 5), 16),
          parseInt(resolved.substring(5, 7), 16)
        ];
      }
    } catch (e) {}
    if (typeof color === 'string') {
      var match = color.match(/^#?([a-f\\d]{2})([a-f\\d]{2})([a-f\\d]{2})$/i);
      if (match) {
        return [parseInt(match[1], 16), parseInt(match[2], 16), parseInt(match[3], 16)];
      }
    }
    return [0, 0, 0];
  }

  function blendColors(color1, color2, ratio) {
    var c1 = parseColor(color1);
    var c2 = parseColor(color2);
    var r = Math.min(1, Math.max(0, Number(ratio)));
    var red = Math.round(c1[0] * (1 - r) + c2[0] * r);
    var green = Math.round(c1[1] * (1 - r) + c2[1] * r);
    var blue = Math.round(c1[2] * (1 - r) + c2[2] * r);
    return 'rgb(' + red + ',' + green + ',' + blue + ')';
  }

  // ── Component Registry ─────────────────────────────────────────────────
  function getComponent(id) {
    return components[id] || document.getElementById('comp-' + id);
  }

  function getComponentValue(id, prop) {
    var el = getComponent(id);
    if (!el) return '';
    
    // Special properties
    if (prop === 'Selection' || prop === 'selection') return el._selection || '';
    if (prop === 'SelectionIndex' || prop === 'selectionIndex') return el._selectionIndex || 0;
    if (prop === 'Elements' || prop === 'elements') return el._elements || [];
    if (prop === 'ElementsFromString' || prop === 'elementsFromString') return (el._elements || []).join(',');
    
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') return el.value;
    if (el.type === 'checkbox') return el.checked;
    return el.textContent || '';
  }

  function setComponentProperty(id, prop, value) {
    var el = getComponent(id);
    if (!el) return;
    switch (prop) {
      case 'Text': case 'text':
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') el.value = value;
        else el.textContent = value;
        break;
      case 'BackgroundColor': case 'backgroundColor':
        el.style.backgroundColor = value;
        break;
      case 'TextColor': case 'textColor':
        el.style.color = value;
        break;
      case 'Visible': case 'visible':
        el.style.display = value ? '' : 'none';
        break;
      case 'Enabled': case 'enabled':
        el.disabled = !value;
        if (!value) el.style.opacity = '0.5';
        else el.style.opacity = '1';
        break;
      case 'Width': case 'width':
        el.style.width = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'Height': case 'height':
        el.style.height = typeof value === 'number' ? value + 'px' : value;
        break;
      case 'Picture': case 'picture': case 'Image':
        if (el.tagName === 'IMG') el.src = mediaUrl(value);
        else el.style.backgroundImage = 'url(' + mediaUrl(value) + ')';
        break;
      case 'Hint': case 'hint':
        el.placeholder = value;
        break;
      case 'Checked': case 'checked':
        var cb = el.querySelector('input[type="checkbox"]') || el;
        cb.checked = !!value;
        break;
      case 'ElementsFromString': case 'elementsFromString':
        el._elements = typeof value === 'string' ? value.split(',') : [];
        break;
      case 'Elements': case 'elements':
        el._elements = Array.isArray(value) ? value : (typeof value === 'string' ? value.split(',') : []);
        break;
      case 'Selection': case 'selection':
        el._selection = value;
        var idx = (el._elements || []).indexOf(value);
        el._selectionIndex = idx >= 0 ? idx + 1 : 0;
        break;
      case 'AlignHorizontal': case 'alignHorizontal':
        // Flex column: alignItems controls cross-axis (horizontal)
        var ha = { 'Left': 'flex-start', 'Center': 'center', 'Right': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
        el.style.alignItems = ha[String(value)] || 'flex-start';
        break;
      case 'AlignVertical': case 'alignVertical':
        // Flex column: justifyContent controls main-axis (vertical)
        var va = { 'Top': 'flex-start', 'Center': 'center', 'Bottom': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
        el.style.justifyContent = va[String(value)] || 'flex-start';
        break;
      case 'FontBold': case 'fontBold':
        el.style.fontWeight = value ? 'bold' : 'normal';
        break;
      case 'FontItalic': case 'fontItalic':
        el.style.fontStyle = value ? 'italic' : 'normal';
        break;
      case 'FontTypeface': case 'fontTypeface':
        // FontTypeface handled via CSS generator; no runtime DOM change needed
        break;
      case 'FontSize': case 'fontSize':
        if (typeof value === 'number' || !isNaN(Number(value))) {
          el.style.fontSize = Number(value) + 'px';
        }
        break;
    }
  }

  // ── Screen Navigation ──────────────────────────────────────────────────
  function applyDesignViewportScale() {
    var viewports = document.querySelectorAll('.screen-viewport');
    var availableWidth = Math.max(1, window.innerWidth || document.documentElement.clientWidth || DESIGN_WIDTH);
    var availableHeight = Math.max(1, window.innerHeight || document.documentElement.clientHeight || DESIGN_HEIGHT);
    var scale = Math.min(availableWidth / DESIGN_WIDTH, availableHeight / DESIGN_HEIGHT);
    for (var i = 0; i < viewports.length; i++) {
      viewports[i].style.transform = 'scale(' + scale + ')';
    }
  }

  window.addEventListener('resize', applyDesignViewportScale);
  window.addEventListener('orientationchange', applyDesignViewportScale);

  function navigateTo(screenId) {
    var allScreens = document.querySelectorAll('.screen');
    for (var i = 0; i < allScreens.length; i++) {
      allScreens[i].classList.remove('active');
    }
    var target = document.getElementById('screen-' + screenId);
    if (target) {
      target.classList.add('active');
      currentScreen = screenId;
    }
  }

  function closeScreen() {
    // Go back to first screen
    navigateTo(${JSON.stringify(firstScreenId)});
  }

  function getScreenElement(id) {
    return document.getElementById('screen-' + id);
  }

  function getScreenProperty(id, prop) {
    var el = getScreenElement(id);
    if (!el) return '';
    var inner = el.querySelector('.screen-inner');
    var viewport = el.querySelector('.screen-viewport') || el;
    switch (prop) {
      case 'BackgroundColor': case 'backgroundColor':
        return viewport.style.backgroundColor || '';
      case 'AlignHorizontal': case 'alignHorizontal':
        return inner ? (inner.style.alignItems || 'flex-start') : 'flex-start';
      case 'AlignVertical': case 'alignVertical':
        return inner ? (inner.style.justifyContent || 'flex-start') : 'flex-start';
      default:
        return '';
    }
  }

  function setScreenProperty(id, prop, value) {
    var el = getScreenElement(id);
    if (!el) return;
    var inner = el.querySelector('.screen-inner');
    var viewport = el.querySelector('.screen-viewport') || el;
    switch (prop) {
      case 'BackgroundColor': case 'backgroundColor':
        viewport.style.backgroundColor = value;
        break;
      case 'Visible': case 'visible':
        el.style.display = value ? '' : 'none';
        break;
      case 'AlignHorizontal': case 'alignHorizontal':
        var ha = { 'Left': 'flex-start', 'Center': 'center', 'Right': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
        if (inner) inner.style.alignItems = ha[String(value)] || 'flex-start';
        break;
      case 'AlignVertical': case 'alignVertical':
        var va = { 'Top': 'flex-start', 'Center': 'center', 'Bottom': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
        if (inner) inner.style.justifyContent = va[String(value)] || 'flex-start';
        break;
    }
  }

`;

  // Generate screen rendering
  screens.forEach(screen => {
    js += generateScreenRenderer(screen);
  });

  // Generate component proxy objects so block-generated code like
  // Button1.Text or Button1.Text = 'Hello' works seamlessly.
  js += `\n  // ── Component Proxy Objects ──────────────────────────────────────────\n`;
  screens.forEach(screen => {
    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      js += generateComponentProxy(comp);
    });
  });

  js += `\n  // ── Screen Proxy Objects ───────────────────────────────────────────────\n`;
  screens.forEach(screen => {
    const screenId = screen.id;
    js += `  var ${screenId} = {\n`;
    js += `    get BackgroundColor() { return getScreenProperty('${screenId}', 'BackgroundColor'); },\n`;
    js += `    set BackgroundColor(v) { setScreenProperty('${screenId}', 'BackgroundColor', v); },\n`;
    js += `    get AlignHorizontal() { return getScreenProperty('${screenId}', 'AlignHorizontal'); },\n`;
    js += `    set AlignHorizontal(v) { setScreenProperty('${screenId}', 'AlignHorizontal', v); },\n`;
    js += `    get AlignVertical() { return getScreenProperty('${screenId}', 'AlignVertical'); },\n`;
    js += `    set AlignVertical(v) { setScreenProperty('${screenId}', 'AlignVertical', v); },\n`;
    js += `    get Visible() { return true; },\n`;
    js += `    set Visible(v) { setScreenProperty('${screenId}', 'Visible', v); }\n`;
    js += `  };\n\n`;
  });

  // Event handlers from block logic
  js += `
  // ── Block Logic (User-defined) ───────────────────────────────────────
  var __leapUserCodeError = null;
  try {
  ${indentMultiline(blockCode, 4)}
  } catch (__err) {
    __leapUserCodeError = __err;
    console.error('[LeapApp] User block logic error:', __err);
  }

  // Warn if no block logic was found
  var __eventFuncs = ['Click','TouchDown','TouchUp','GotFocus','LostFocus','Changed','AfterPicking','BeforePicking','Timer'];
  var __hasBlockHandlers = false;
  ${indentMultiline(blockCode ? '  __hasBlockHandlers = true;' : '', 2)}

  // ── Initialization ─────────────────────────────────────────────────────
  window.LeapApp = {
    init: function() {
      var root = document.getElementById('app-root');
      if (!root) throw new Error('Missing app root element.');
      root.innerHTML = '';
      if (__leapUserCodeError) {
        root.innerHTML = '<div style="padding:16px;font-family:Arial,sans-serif;color:#b91c1c;background:#fef2f2;border:1px solid #fecaca;border-radius:8px;margin:12px;">App failed: ' + String(__leapUserCodeError.message || __leapUserCodeError) + '</div>';
        throw __leapUserCodeError;
      }
`;

  screens.forEach(screen => {
    js += `      ${screenRendererName(screen.id)}();\n`;
  });

  js += `      applyDesignViewportScale();
      navigateTo(${JSON.stringify(firstScreenId)});
    },
    navigateTo: navigateTo,
    getComponent: getComponent,
    setProperty: setComponentProperty,
    getValue: getComponentValue,
    NativeBridge: NativeBridge,
    state: state
  };

})();
`;

  validateGeneratedJavaScript(js);
  return js;
}

/**
 * Generate all files needed for the APK injection
 */
function generateWebApp(appState) {
  return {
    'www/index.html': generateIndexHtml(appState),
    'www/styles.css': generateStylesCss(appState),
    'www/app.js': generateAppJs(appState),
    'www/app_config.json': JSON.stringify({
      appName: appState.appName || 'My App',
      packageName: appState.packageName || 'com.leaplab.myapp',
      versionCode: appState.versionCode || 1,
      versionName: appState.versionName || '1.0',
      designViewport: getDesignViewport(appState),
      screens: (appState.screens || []).map(s => s.id)
    }, null, 2)
  };
}

// ── Helpers ────────────────────────────────────────────────────────────────

function toJsIdentifier(value, fallback = 'item') {
  const raw = String(value || fallback);
  const normalized = raw.replace(/[^a-zA-Z0-9_$]/g, '_');
  return /^[a-zA-Z_$]/.test(normalized) ? normalized : `_${normalized}`;
}

function screenRendererName(screenId) {
  return `render_${toJsIdentifier(screenId, 'Screen')}`;
}

function isValidJsIdentifier(value) {
  return /^[A-Za-z_$][0-9A-Za-z_$]*$/.test(String(value || ''));
}

function validateComponentIdentifiers(screens) {
  const invalid = [];
  screens.forEach(screen => {
    const allComponents = [...(screen.components || []), ...(screen.nonVisibleComponents || [])];
    walkComponentTree(allComponents, comp => {
      if (!isValidJsIdentifier(comp.id)) invalid.push(comp.id);
    });
  });

  if (invalid.length) {
    throw new Error(`Invalid component name(s) for APK build: ${invalid.join(', ')}. Use names like Button1 without spaces or symbols.`);
  }
}

function validateGeneratedJavaScript(js) {
  try {
    // Build-time validation prevents shipping APKs that open to a blank WebView.
    new Function(js);
  } catch (error) {
    throw new Error(`Generated app JavaScript is invalid: ${error.message}`);
  }
}

function cssIdSelector(id) {
  return `#${String(id).replace(/[^a-zA-Z0-9_-]/g, (char) => `\\${char}`)}`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function mediaUrl(value) {
  if (!value) return '';
  const s = String(value);
  if (s.startsWith('http://') || s.startsWith('https://') || s.startsWith('data:') || s.startsWith('file://') || s.startsWith('blob:')) return s;
  return 'media/' + s;
}

function indentMultiline(value, spaces = 2) {
  const pad = ' '.repeat(Math.max(0, spaces));
  if (!value) return '';
  return String(value)
    .split('\n')
    .map((line) => (line ? pad + line : line))
    .join('\n');
}

function walkComponentTree(list, visitor) {
  if (!list) return;
  for (const item of list) {
    visitor(item);
    if (item.children?.length) walkComponentTree(item.children, visitor);
  }
}

function resolveDimension(value, fallback, percentValue) {
  const normalized = typeof value === 'string' ? value.trim().toLowerCase().replace(/\s+/g, '_') : value;
  if (normalized === 'fill_parent' || normalized === 'fill_parent...' || value === -2) return '100%';
  if (normalized === 'automatic' || value === -1) return fallback || 'auto';
  if (typeof value === 'number') return value + 'px';
  if (percentValue !== undefined && percentValue !== null && percentValue !== '') return `${percentValue}%`;
  if (value === undefined || value === null || value === '') return fallback || 'auto';
  return value;
}

function generateComponentCss(comp) {
  const { id, type, props = {} } = comp;
  const selector = cssIdSelector('comp-' + id);
  let rules = '';

  const width = resolveDimension(firstDefined(props.Width, props.width), 'auto', firstDefined(props.WidthPercent, props.widthPercent));
  const height = resolveDimension(firstDefined(props.Height, props.height), 'auto', firstDefined(props.HeightPercent, props.heightPercent));

  // Resolve defaults based on component type (matching studio canvas)
  let defaultBg = 'transparent';
  let defaultTextColor = '';
  let typePadding = '8px';
  let typeMinHeight = '';
  let typeBorder = '';
  
  if (['Button', 'ListPicker', 'DatePicker', 'TimePicker', 'ImagePicker', 'FilePicker', 'ContactPicker'].includes(type)) {
    defaultBg = '#E0E0E0';
    defaultTextColor = '#000000';
    typePadding = '8px 12px';
    typeMinHeight = height === 'auto' ? '36px' : '';
    typeBorder = '1px solid #BDBDBD';
  } else if (type === 'ListView') {
    defaultBg = '#000000';
    defaultTextColor = '#ffffff';
  } else if (['Label', 'CheckBox', 'Switch'].includes(type)) {
    defaultBg = 'transparent';
    defaultTextColor = '#000000';
    typePadding = '2px 0';
  } else if (['TextBox', 'PasswordTextBox', 'Spinner'].includes(type)) {
    defaultBg = '#ffffff';
    defaultTextColor = '#000000';
    typePadding = '6px 8px';
  }

  const bgColor = props.backgroundColor || props.BackgroundColor || defaultBg;
  const textColor = props.textColor || props.TextColor || defaultTextColor;
  const fontSize = props.fontSize || props.FontSize || 14;
  const bold = props.bold || props.FontBold;
  const italic = props.italic || props.FontItalic;
  const padding = props.padding || typePadding;
  const shape = props.Shape || 'default';

  let borderRadius;
  const isButtonType = ['Button', 'ListPicker', 'DatePicker', 'TimePicker', 'ImagePicker', 'FilePicker', 'ContactPicker'].includes(type);
  if (props.borderRadius !== undefined) {
    borderRadius = props.borderRadius;
  } else if (isButtonType) {
    if (shape === 'rounded') borderRadius = 9999;
    else if (shape === 'rectangular') borderRadius = 0;
    else if (shape === 'oval') borderRadius = '50%';
    else borderRadius = 12;
  }

  rules += `${selector} {\n`;
  if (width !== 'auto') rules += `  width: ${width};\n`;
  if (height !== 'auto') rules += `  height: ${height};\n`;
  if (firstDefined(props.Visible, props.visible) === false) rules += `  display: none;\n`;
  if (bgColor !== 'transparent') rules += `  background-color: ${bgColor};\n`;
  if (textColor) rules += `  color: ${textColor};\n`;
  rules += `  font-size: ${fontSize}px;\n`;
  if (bold) rules += `  font-weight: bold;\n`;
  if (italic) rules += `  font-style: italic;\n`;
  rules += `  padding: ${padding};\n`;
  if (typeMinHeight) rules += `  min-height: ${typeMinHeight};\n`;
  if (typeBorder) rules += `  border: ${typeBorder};\n`;
  if (['HorizontalArrangement', 'HorizontalScrollArrangement', 'VerticalArrangement', 'VerticalScrollArrangement', 'TableArrangement', 'AbsoluteArrangement'].includes(type)) {
    const alignH = props.AlignHorizontal || 'Left';
    const alignV = props.AlignVertical || 'Top';
    const haMap = { 'Left': 'flex-start', 'Center': 'center', 'Right': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
    const vaMap = { 'Top': 'flex-start', 'Center': 'center', 'Bottom': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
    if (type.startsWith('Horizontal') || type.startsWith('Table') || type.startsWith('Absolute')) {
      rules += `  justify-content: ${haMap[String(alignH)] || 'flex-start'};\n`;
      rules += `  align-items: ${vaMap[String(alignV)] || 'flex-start'};\n`;
    } else {
      rules += `  align-items: ${haMap[String(alignH)] || 'flex-start'};\n`;
      rules += `  justify-content: ${vaMap[String(alignV)] || 'flex-start'};\n`;
    }
  }
  if (borderRadius != null) {
    if (typeof borderRadius === 'number') {
      rules += `  border-radius: ${borderRadius}px;\n`;
    } else {
      rules += `  border-radius: ${borderRadius};\n`;
    }
  }
  const bgImage = props.picture || props.Picture || props.image || props.Image || '';
  if (bgImage) rules += `  background-image: url(${mediaUrl(bgImage)}); background-size: 100% 100%;\n`;
  rules += `}\n`;

  return rules;
}

function generateScreenRenderer(screen) {
  const screenId = screen.id;
  const components = screen.components || [];
  const renderName = screenRendererName(screenId);

  const ha = { 'Left': 'flex-start', 'Center': 'center', 'Right': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
  const va = { 'Top': 'flex-start', 'Center': 'center', 'Bottom': 'flex-end', '1': 'flex-start', '2': 'center', '3': 'flex-end' };
  const alignH = ha[screen.alignHorizontal] || 'flex-start';
  const alignV = va[screen.alignVertical] || 'flex-start';

  let js = `  function ${renderName}() {\n`;
    js += `    var container = document.createElement('div');\n`;
    js += `    container.id = ${JSON.stringify('screen-' + screenId)};\n`;
    js += `    container.className = 'screen';\n`;
    js += `    var viewport = document.createElement('div');\n`;
    js += `    viewport.className = 'screen-viewport';\n`;
    js += `    viewport.dataset.designWidth = String(DESIGN_WIDTH);\n`;
    js += `    viewport.dataset.designHeight = String(DESIGN_HEIGHT);\n`;
    js += `    var inner = document.createElement('div');\n`;
    js += `    inner.className = 'screen-inner';\n`;
    js += `    inner.style.alignItems = '${alignH}';\n`;
    js += `    inner.style.justifyContent = '${alignV}';\n`;
    js += `    viewport.appendChild(inner);\n`;
    js += `    container.appendChild(viewport);\n`;

  components.forEach(comp => {
    js += generateComponentCreation(comp, 'inner');
  });
  js += `    document.getElementById('app-root').appendChild(container);\n`;
  js += `  }\n\n`;

  return js;
}

function generateComponentCreation(comp, parentVar, parentType) {
  const { id, type, props = {}, children } = comp;
  const varName = `el_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
  let js = '';

  switch (type) {
    case 'Button':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Button')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var _fn = window['${id}_Click'];\n`;
      js += `      if (typeof _fn === 'function') {\n`;
      js += `        try { _fn(); } catch(_e) { console.error('[LeapApp] Error in ${id}_Click:', _e); }\n`;
      js += `      } else if (typeof _fn !== 'undefined') {\n`;
      js += `        console.warn('[LeapApp] ${id}_Click is not a function:', typeof _fn);\n`;
      js += `      }\n`;
      js += `    });\n`;
      break;

    case 'Label':
      js += `    var ${varName} = document.createElement('span');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-label';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || '')};\n`;
      break;

    case 'TextBox':
      const multiLine = props.multiLine || props.MultiLine;
      const tag = multiLine ? 'textarea' : 'input';
      js += `    var ${varName} = document.createElement('${tag}');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      if (!multiLine) js += `    ${varName}.type = 'text';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || '')};\n`;
      js += `    ${varName}.value = ${JSON.stringify(props.text || props.Text || '')};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'PasswordTextBox':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      js += `    ${varName}.type = 'password';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || 'Password')};\n`;
      break;

    case 'Image':
      js += `    var ${varName} = document.createElement('img');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-image';\n`;
      js += `    ${varName}.src = '${mediaUrl(props.picture || props.Picture || '')}';\n`;
      js += `    ${varName}.alt = ${JSON.stringify(id)};\n`;
      break;

    case 'CheckBox':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-checkbox';\n`;
      js += `    var ${varName}_cb = document.createElement('input');\n`;
      js += `    ${varName}_cb.type = 'checkbox';\n`;
      js += `    ${varName}_cb.checked = ${Boolean(props.checked || props.Checked)};\n`;
      js += `    ${varName}_cb.addEventListener('change', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](e.target.checked);\n`;
      js += `    });\n`;
      js += `    var ${varName}_lbl = document.createElement('span');\n`;
      js += `    ${varName}_lbl.textContent = ${JSON.stringify(props.text || props.Text || 'CheckBox')};\n`;
      js += `    ${varName}.appendChild(${varName}_cb);\n`;
      js += `    ${varName}.appendChild(${varName}_lbl);\n`;
      break;

    case 'Slider':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-slider';\n`;
      js += `    ${varName}.type = 'range';\n`;
      js += `    ${varName}.min = ${props.minValue || props.MinValue || 0};\n`;
      js += `    ${varName}.max = ${props.maxValue || props.MaxValue || 100};\n`;
      js += `    ${varName}.value = ${props.thumbPosition || props.ThumbPosition || 50};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](Number(e.target.value));\n`;
      js += `    });\n`;
      break;

    case 'Switch':
      js += `    var ${varName} = document.createElement('label');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-switch';\n`;
      js += `    var ${varName}_sw = document.createElement('input');\n`;
      js += `    ${varName}_sw.type = 'checkbox';\n`;
      js += `    ${varName}_sw.checked = ${Boolean(props.on || props.On)};\n`;
      js += `    ${varName}_sw.addEventListener('change', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](e.target.checked);\n`;
      js += `    });\n`;
      js += `    ${varName}.appendChild(${varName}_sw);\n`;
      break;

    case 'ListView':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-listview';\n`;
      const items = props.elements || props.Elements || [];
      const itemsList = typeof items === 'string' ? items.split(',') : items;
      itemsList.forEach((item, idx) => {
        js += `    (function() {\n`;
        js += `      var item = document.createElement('div');\n`;
        js += `      item.className = 'comp-listview-item';\n`;
        js += `      item.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      item.addEventListener('click', function() {\n`;
        js += `        if (typeof window['${id}_AfterPicking'] === 'function') window['${id}_AfterPicking'](${idx}, item.textContent);\n`;
        js += `      });\n`;
        js += `      ${varName}.appendChild(item);\n`;
        js += `    })();\n`;
      });
      break;

    case 'ListPicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'ListPicker')};\n`;

      const lpItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      js += `    ${varName}._elements = ${JSON.stringify(lpItems)};\n`;
      js += `    ${varName}._selection = '';\n`;
      js += `    ${varName}._selectionIndex = 0;\n`;

      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      if (typeof window['${id}_BeforePicking'] === 'function') window['${id}_BeforePicking']();\n`;
      js += `      var _pickElements = ${varName}._elements || [];\n`;
      js += `      NativeBridge.showListPickerModal(_pickElements, function(index, item) {\n`;
      js += `        ${varName}._selection = item;\n`;
      js += `        ${varName}._selectionIndex = index + 1;\n`; // 1-based index for App Inventor
      js += `        if (typeof window['${id}_AfterPicking'] === 'function') window['${id}_AfterPicking']();\n`;
      js += `      });\n`;
      js += `    });\n`;
      break;

    case 'Spinner':
      js += `    var ${varName} = document.createElement('select');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-spinner';\n`;
      const spinnerItems = props.elements || props.Elements || (props.ElementsFromString ? props.ElementsFromString.split(',') : []);
      const spinnerList = typeof spinnerItems === 'string' ? spinnerItems.split(',') : spinnerItems;
      spinnerList.forEach(item => {
        js += `    (function() {\n`;
        js += `      var opt = document.createElement('option');\n`;
        js += `      opt.value = ${JSON.stringify(String(item).trim())};\n`;
        js += `      opt.textContent = ${JSON.stringify(String(item).trim())};\n`;
        js += `      ${varName}.appendChild(opt);\n`;
        js += `    })();\n`;
      });
      js += `    ${varName}.addEventListener('change', function(e) {\n`;
      js += `      ${varName}._selection = e.target.value;\n`;
      js += `      ${varName}._selectionIndex = e.target.selectedIndex + 1;\n`;
      js += `      if (typeof window['${id}_AfterSelecting'] === 'function') window['${id}_AfterSelecting'](e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'WebViewer':
      js += `    var ${varName} = document.createElement('iframe');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-webviewer';\n`;
      js += `    ${varName}.src = ${JSON.stringify(props.homeUrl || props.HomeUrl || 'about:blank')};\n`;
      break;

    case 'Canvas':
      const canvasWidth = positiveNumber(firstDefined(props.Width, props.width), 300);
      const canvasHeight = positiveNumber(firstDefined(props.Height, props.height), 300);
      js += `    var ${varName} = document.createElement('canvas');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-canvas';\n`;
      js += `    ${varName}.width = ${canvasWidth};\n`;
      js += `    ${varName}.height = ${canvasHeight};\n`;
      js += `    (function(canvas) {\n`;
      js += `      var isDrawing = false;\n`;
      js += `      var lastX = 0, lastY = 0;\n`;
      js += `      var startX = 0, startY = 0;\n`;
      js += `      function getPos(e) {\n`;
      js += `        var rect = canvas.getBoundingClientRect();\n`;
      js += `        var clientX = e.touches ? e.touches[0].clientX : e.clientX;\n`;
      js += `        var clientY = e.touches ? e.touches[0].clientY : e.clientY;\n`;
      js += `        return { x: clientX - rect.left, y: clientY - rect.top };\n`;
      js += `      }\n`;
      js += `      function handleStart(e) {\n`;
      js += `        isDrawing = true;\n`;
      js += `        var pos = getPos(e);\n`;
      js += `        lastX = pos.x; lastY = pos.y;\n`;
      js += `        startX = pos.x; startY = pos.y;\n`;
      js += `        if (typeof window['${id}_TouchDown'] === 'function') window['${id}_TouchDown'](pos.x, pos.y);\n`;
      js += `      }\n`;
      js += `      function handleMove(e) {\n`;
      js += `        if (!isDrawing) return;\n`;
      js += `        e.preventDefault();\n`;
      js += `        var pos = getPos(e);\n`;
      js += `        if (typeof window['${id}_Dragged'] === 'function') window['${id}_Dragged'](startX, startY, lastX, lastY, pos.x, pos.y, false);\n`;
      js += `        lastX = pos.x; lastY = pos.y;\n`;
      js += `      }\n`;
      js += `      function handleEnd(e) {\n`;
      js += `        if (!isDrawing) return;\n`;
      js += `        isDrawing = false;\n`;
      js += `        if (typeof window['${id}_TouchUp'] === 'function') window['${id}_TouchUp'](lastX, lastY);\n`;
      js += `        if (typeof window['${id}_Touched'] === 'function') window['${id}_Touched'](lastX, lastY, false);\n`;
      js += `      }\n`;
      js += `      canvas.addEventListener('mousedown', handleStart);\n`;
      js += `      canvas.addEventListener('mousemove', handleMove);\n`;
      js += `      canvas.addEventListener('mouseup', handleEnd);\n`;
      js += `      canvas.addEventListener('touchstart', handleStart, {passive: false});\n`;
      js += `      canvas.addEventListener('touchmove', handleMove, {passive: false});\n`;
      js += `      canvas.addEventListener('touchend', handleEnd);\n`;
      js += `    })(${varName});\n`;
      break;

    // Layout containers
    case 'HorizontalArrangement':
    case 'HorizontalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'horizontal-scroll' : 'horizontal'}';\n`;
      break;

    case 'VerticalArrangement':
    case 'VerticalScrollArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-${type.includes('Scroll') ? 'vertical-scroll' : 'vertical'}';\n`;
      break;

    case 'TableArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'arrangement-table';\n`;
      const cols = props.columns || props.Columns || 2;
      js += `    ${varName}.style.gridTemplateColumns = 'repeat(${cols}, 1fr)';\n`;
      break;

    case 'AbsoluteArrangement':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.position = 'relative';\n`;
      break;

    case 'Map':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.position = 'relative';\n`;
      js += `    ${varName}.style.minHeight = '200px';\n`;
      js += `    ${varName}.style.background = '#e8e8e8';\n`;
      js += `    ${varName}.style.backgroundImage = 'repeating-linear-gradient(45deg, #d0d0d0 0px, #d0d0d0 1px, transparent 1px, transparent 8px)';\n`;
      break;

    case 'Polygon': {
      const polyColor = props.paintColor || props.PaintColor || '#FF0000';
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.width = '52px';\n`;
      js += `    ${varName}.style.height = '34px';\n`;
      js += `    ${varName}.innerHTML = '<svg width=\"52\" height=\"34\" viewBox=\"0 0 52 34\"><polygon points=\"26,2 50,32 2,32\" fill=\"${polyColor}\" stroke=\"#000\" stroke-width=\"1\"/></svg>';\n`;
      break;
    }

    case 'Circle': {
      const circleColor = props.paintColor || props.PaintColor || '#FF0000';
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.width = '14px';\n`;
      js += `    ${varName}.style.height = '14px';\n`;
      js += `    ${varName}.innerHTML = '<svg width=\"14\" height=\"14\" viewBox=\"0 0 14 14\"><circle cx=\"7\" cy=\"7\" r=\"6\" fill=\"${circleColor}\" stroke=\"#000\" stroke-width=\"1\"/></svg>';\n`;
      break;
    }

    case 'Marker':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.width = '30px';\n`;
      js += `    ${varName}.style.height = '50px';\n`;
      js += `    ${varName}.innerHTML = '<svg width=\"30\" height=\"50\" viewBox=\"0 0 30 50\"><path d=\"M15 0C6.7 0 0 6.7 0 15c0 11 15 35 15 35s15-24 15-35C30 6.7 23.3 0 15 0zm0 22c-3.9 0-7-3.1-7-7s3.1-7 7-7 7 3.1 7 7-3.1 7-7 7z\" fill=\"#FF0000\" stroke=\"#000\" stroke-width=\"1\"/></svg>';\n`;
      break;

    case 'LineString': {
      const lineColor = props.paintColor || props.PaintColor || '#FF0000';
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.width = '42px';\n`;
      js += `    ${varName}.style.height = '44px';\n`;
      js += `    ${varName}.innerHTML = '<svg width=\"42\" height=\"44\" viewBox=\"0 0 42 44\"><polyline points=\"2,42 20,22 40,2\" fill=\"none\" stroke=\"${lineColor}\" stroke-width=\"3\"/></svg>';\n`;
      break;
    }

    case 'Rectangle': {
      const rectColor = props.paintColor || props.PaintColor || '#FF0000';
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.width = '52px';\n`;
      js += `    ${varName}.style.height = '32px';\n`;
      js += `    ${varName}.innerHTML = '<svg width=\"52\" height=\"32\" viewBox=\"0 0 52 32\"><rect x=\"2\" y=\"2\" width=\"48\" height=\"28\" fill=\"${rectColor}\" stroke=\"#000\" stroke-width=\"1\"/></svg>';\n`;
      break;
    }

    case 'FeatureCollection':
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify('FeatureCollection (' + id + ')')};\n`;
      break;

    case 'VideoPlayer':
      js += `    var ${varName} = document.createElement('video');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.controls = true;\n`;
      js += `    ${varName}.style.width = '100%';\n`;
      js += `    ${varName}.src = '${mediaUrl(props.source || props.Source || '')}';\n`;
      break;

    case 'Ball': {
      const ballColor = props.paintColor || props.PaintColor || '#FF0000';
      const radius = Math.max(1, Number(props.radius || props.Radius || 10));
      const diameter = radius * 2;
      const ballX = Number(props.x || props.X || 0);
      const ballY = Number(props.y || props.Y || 0);
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.position = 'absolute';\n`;
      js += `    ${varName}.style.width = '${diameter}px';\n`;
      js += `    ${varName}.style.height = '${diameter}px';\n`;
      js += `    ${varName}.style.borderRadius = '50%';\n`;
      js += `    ${varName}.style.backgroundColor = '${ballColor}';\n`;
      js += `    ${varName}.style.left = '${ballX}px';\n`;
      js += `    ${varName}.style.top = '${ballY}px';\n`;
      break;
    }

    case 'ImageSprite': {
      const spritePic = props.picture || props.Picture || '';
      const spriteX = Number(props.x || props.X || 0);
      const spriteY = Number(props.y || props.Y || 0);
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.style.position = 'absolute';\n`;
      js += `    ${varName}.style.overflow = 'hidden';\n`;
      js += `    var ${varName}_img = document.createElement('img');\n`;
      js += `    ${varName}_img.src = '${mediaUrl(spritePic)}';\n`;
      js += `    ${varName}_img.style.display = 'block';\n`;
      const spriteW = firstDefined(props.Width, props.width);
      const spriteH = firstDefined(props.Height, props.height);
      if (spriteW > 0) js += `    ${varName}_img.style.width = '${spriteW}px';\n`;
      if (spriteH > 0) js += `    ${varName}_img.style.height = '${spriteH}px';\n`;
      js += `    ${varName}.appendChild(${varName}_img);\n`;
      js += `    ${varName}.style.left = '${spriteX}px';\n`;
      js += `    ${varName}.style.top = '${spriteY}px';\n`;
      break;
    }

    case 'ImagePicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Pick Image')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var input = document.createElement('input');\n`;
      js += `      input.type = 'file';\n`;
      js += `      input.accept = 'image/*';\n`;
      js += `      input.addEventListener('change', function(e) {\n`;
      js += `        var file = e.target.files[0];\n`;
      js += `        if (file && typeof window['${id}_FilePicked'] === 'function') window['${id}_FilePicked'](file.name);\n`;
      js += `      });\n`;
      js += `      input.click();\n`;
      js += `    });\n`;
      break;

    case 'DatePicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Pick Date')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var d = new Date();\n`;
      js += `      var val = prompt('Enter date (YYYY-MM-DD):', d.toISOString().split('T')[0]);\n`;
      js += `      if (val) {\n`;
      js += `        ${varName}.textContent = val;\n`;
      js += `        if (typeof window['${id}_DatePicked'] === 'function') window['${id}_DatePicked'](val);\n`;
      js += `      }\n`;
      js += `    });\n`;
      break;

    case 'TimePicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Pick Time')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var d = new Date();\n`;
      js += `      var val = prompt('Enter time (HH:MM):', d.toTimeString().slice(0,5));\n`;
      js += `      if (val) {\n`;
      js += `        ${varName}.textContent = val;\n`;
      js += `        if (typeof window['${id}_TimePicked'] === 'function') window['${id}_TimePicked'](val);\n`;
      js += `      }\n`;
      js += `    });\n`;
      break;

    case 'ContactPicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Pick Contact')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var contact = prompt('Enter contact name:');\n`;
      js += `      if (contact) {\n`;
      js += `        if (typeof window['${id}_ContactPicked'] === 'function') window['${id}_ContactPicked'](contact, '', '');\n`;
      js += `      }\n`;
      js += `    });\n`;
      break;

    case 'EmailPicker':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      js += `    ${varName}.type = 'email';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || 'Email')};\n`;
      js += `    ${varName}.value = ${JSON.stringify(props.text || props.Text || '')};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'PhoneNumberPicker':
      js += `    var ${varName} = document.createElement('input');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-textbox';\n`;
      js += `    ${varName}.type = 'tel';\n`;
      js += `    ${varName}.placeholder = ${JSON.stringify(props.hint || props.Hint || 'Phone')};\n`;
      js += `    ${varName}.value = ${JSON.stringify(props.text || props.Text || '')};\n`;
      js += `    ${varName}.addEventListener('input', function(e) {\n`;
      js += `      if (typeof window['${id}_Changed'] === 'function') window['${id}_Changed'](e.target.value);\n`;
      js += `    });\n`;
      break;

    case 'FilePicker':
      js += `    var ${varName} = document.createElement('button');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.className = 'comp-button';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(props.text || props.Text || 'Pick File')};\n`;
      js += `    ${varName}.addEventListener('click', function() {\n`;
      js += `      var input = document.createElement('input');\n`;
      js += `      input.type = 'file';\n`;
      js += `      input.addEventListener('change', function(e) {\n`;
      js += `        var file = e.target.files[0];\n`;
      js += `        if (file && typeof window['${id}_FilePicked'] === 'function') window['${id}_FilePicked'](file.name);\n`;
      js += `      });\n`;
      js += `      input.click();\n`;
      js += `    });\n`;
      break;

    default:
      js += `    var ${varName} = document.createElement('div');\n`;
      js += `    ${varName}.id = 'comp-${id}';\n`;
      js += `    ${varName}.textContent = ${JSON.stringify(type + ' (' + id + ')')};\n`;
      break;
  }

  js += `    components['${id}'] = ${varName};\n`;

  // Apply absolute positioning when inside AbsoluteArrangement
  if (parentType === 'AbsoluteArrangement') {
    const posX = firstDefined(props.X, props.x) || 0;
    const posY = firstDefined(props.Y, props.y) || 0;
    const posZ = firstDefined(props.Z, props.z) || 1;
    js += `    ${varName}.style.position = 'absolute';\n`;
    js += `    ${varName}.style.left = '${posX}px';\n`;
    js += `    ${varName}.style.top = '${posY}px';\n`;
    js += `    ${varName}.style.zIndex = '${posZ}';\n`;
  }

  // Render children for arrangement containers
  if (children && children.length > 0) {
    children.forEach(child => {
      js += generateComponentCreation(child, varName, type);
    });
  }

  js += `    ${parentVar}.appendChild(${varName});\n`;

  return js;
}

/**
 * Generate a proxy object for a component so block-generated code
 * like `Button1.Text` or `Button1.Text = 'Hello' works.
 */
function generateComponentProxy(comp) {
  const { id, type, props = {} } = comp;

  // Non-visible shims instantiation
  if (type === 'Clock') {
    return `  var ${id} = new ClockShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'TinyDB') {
    return `  var ${id} = new TinyDBShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Notifier') {
    return `  var ${id} = new NotifierShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Sound' || type === 'Player') {
    return `  var ${id} = new SoundShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'TextToSpeech') {
    return `  var ${id} = new TextToSpeechShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'LocationSensor') {
    return `  var ${id} = new LocationSensorShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'Web') {
    return `  var ${id} = new WebShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'BluetoothClient') {
    return `  var ${id} = new BluetoothClientShim('${id}', ${JSON.stringify(props)});\n`;
  }
  if (type === 'BluetoothServer') {
    return `  var ${id} = new BluetoothServerShim('${id}', ${JSON.stringify(props)});\n`;
  }

  const propNames = Object.keys(props);
  if (propNames.length === 0 && !['Button', 'Label', 'ListPicker', 'DatePicker', 'TimePicker', 'ImagePicker', 'FilePicker', 'ContactPicker', 'PhoneNumberPicker', 'EmailPicker', 'Spinner', 'CheckBox', 'Switch', 'Slider', 'ListView', 'TextBox', 'PasswordTextBox', 'Image', 'Canvas', 'WebViewer', 'VideoPlayer'].includes(type)) return '';

  // Standard property list based on component type
  const allProps = new Set([
    'Text', 'BackgroundColor', 'TextColor', 'Visible', 'Enabled',
    'Width', 'Height', 'FontSize', 'Hint', 'Picture', 'Checked',
    'AlignHorizontal', 'AlignVertical', 'FontBold', 'FontItalic', 'FontTypeface',
    'PaintColor', 'Radius', 'X', 'Y', 'Source', 'Points',
    ...propNames
  ]);

  let js = `  // Proxy: ${id} (${type})\n`;
  js += `  var ${id} = {\n`;

  // Event names — skip from data-property getters/setters to avoid conflicts
  // with the callback stubs added below.
  var eventNames = ['Click', 'GotFocus', 'LostFocus', 'TouchDown', 'TouchUp', 'LongClick'];
  for (const prop of allProps) {
    if (eventNames.indexOf(prop) !== -1) continue;
    js += `    get ${prop}() { return getComponentValue('${id}', '${prop}'); },\n`;
    js += `    set ${prop}(v) { setComponentProperty('${id}', '${prop}', v); },\n`;
  }

  // Add event callback stubs for blocks that reference Component.Click etc.
  if (['Button', 'Label', 'Image', 'ListView', 'CheckBox'].includes(type)) {
    js += `    Click: function() {},\n`;
  }

  js += `  };\n\n`;
  return js;
}

// ── CommonJS Exports ────────────────────────────────────────────────────────

module.exports = {
  generateIndexHtml,
  generateStylesCss,
  generateAppJs,
  generateWebApp,
  generateComponentProxy
};
