/**
 * Copyright (c) 2026 Creoleap Technologies Pvt. Ltd.
 * All rights reserved. Proprietary and confidential.
 * Unauthorized copying, distribution, or modification is strictly prohibited.
 */

import { getBoards } from "../../leapignite/client/components/BoardSelectionModal";

let _BOARD_NAME_BY_ID;
export function getBoardNameById() {
    if (!_BOARD_NAME_BY_ID) {
        _BOARD_NAME_BY_ID = getBoards().reduce((acc, b) => {
            acc[b.id] = b.name;
            return acc;
        }, {});
    }
    return _BOARD_NAME_BY_ID;
}

export const BOARD_UPLOAD_CONFIG = {
    arduino_uno: {
        fileName: "arduino_uno.ino",
        fqbn: "arduino:avr:uno",
        runtimeLabel: "Arduino Uno",
    },
    arduino_mega: {
        fileName: "arduino_mega.ino",
        fqbn: "arduino:avr:mega",
        runtimeLabel: "Arduino Mega",
    },
    arduino_nano: {
        fileName: "arduino_nano.ino",
        fqbn: "arduino:avr:nano",
        runtimeLabel: "Arduino Nano",
    },
    esp32: {
        fileName: "esp32.cpp",
        fqbn: "esp32:esp32:esp32c3",
        runtimeLabel: "ESP32-C3",
    },
};

export const getBoardConfig = (boardId) => BOARD_UPLOAD_CONFIG[boardId] || BOARD_UPLOAD_CONFIG.arduino_uno;

export const getFileExtension = (fileName = "") => {
    const dotIndex = fileName.lastIndexOf(".");
    return dotIndex >= 0 ? fileName.slice(dotIndex).toLowerCase() : "";
};

export const isBoardUploadFile = (fileName, boardEntryFile) => {
    if (fileName === boardEntryFile) return true;
    const extension = getFileExtension(fileName);
    return BOARD_HEADER_EXTENSIONS.has(extension) || BOARD_SOURCE_EXTENSIONS.has(extension);
};

export const sortUploadFiles = (fileNames, preferredFile) => [...fileNames].sort((left, right) => {
    if (left === preferredFile) return -1;
    if (right === preferredFile) return 1;
    return left.localeCompare(right);
});

export const createUploadFiles = (boardId) => {
    const boardConfig = getBoardConfig(boardId);
    const boardName = getBoardNameById()[boardId] || boardConfig.runtimeLabel;

    return {
        "main.py": buildMicroPythonTemplate(boardName),
        [boardConfig.fileName]: buildBoardTemplate(boardId),
    };
};

export const formatPortLabel = (port) => {
    if (!port) return "";
    if (port.path === "BRIDGE_DETECTED") {
        return `Driver issue: ${port.manufacturer || "Unknown bridge"}`;
    }
    return `${port.path}${port.manufacturer ? ` (${port.manufacturer})` : ""}`;
};

// ─── Template Builders ──────────────────────────────────────────────────────

export const buildMicroPythonTemplate = (boardName) => `# LeapBlocks Python Upload Mode
# Project logic in MicroPython for ${boardName}.
# Keep board-specific firmware in the C++ file.

from machine import Pin
import time

status_led = Pin(2, Pin.OUT)

print("Booting ${boardName} project...")

for cycle in range(3):
    status_led.value(1)
    print("Cycle", cycle + 1, "- LED on")
    time.sleep(0.3)
    status_led.value(0)
    print("Cycle", cycle + 1, "- LED off")
    time.sleep(0.3)

print("Project ready.")
`;

export const buildBoardTemplate = (boardId) => {
    if (boardId === "esp32") {
        return `// This C++ code is generated by LeapBlocks

#include <Arduino.h>

void setup() {
    // put your setup code here, to run once:

}

void loop() {
    // put your main code here, to run repeatedly:

}
`;
    }

    return `// This C++ code is generated by LeapBlocks

void setup() {
    // put your setup code here, to run once:

}

void loop() {
    // put your main code here, to run repeatedly:

}
`;
};

// ─── Library Templates ─────────────────────────────────────────────────────

export const getLibraryBaseName = (rawName = "") => {
    const stripped = rawName.replace(/\.(h|hpp|cpp|cc|c)$/i, "").trim();
    const normalized = stripped.replace(/[^a-zA-Z0-9_]/g, "_").replace(/_+/g, "_").replace(/^_+|_+$/g, "");
    return normalized || "MyLibrary";
};

export const getLibraryClassName = (baseName) => {
    const words = baseName.replace(/_/g, " ").split(/\s+/).filter(Boolean);
    return words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join("") || "MyLibrary";
};

export const getUniqueLibraryBaseName = (rawName, existingFiles) => {
    const baseName = getLibraryBaseName(rawName);
    let candidate = baseName;
    let suffix = 2;

    while (
        existingFiles?.[`${candidate}.h`] ||
        existingFiles?.[`${candidate}.hpp`] ||
        existingFiles?.[`${candidate}.cpp`] ||
        existingFiles?.[`${candidate}.cc`] ||
        existingFiles?.[`${candidate}.c`]
    ) {
        candidate = `${baseName}_${suffix}`;
        suffix += 1;
    }

    return candidate;
};

export const buildLibraryHeaderTemplate = (rawName) => {
    const baseName = getLibraryBaseName(rawName);
    const className = getLibraryClassName(baseName);
    const includeGuard = `${baseName.toUpperCase()}_H`;

    return {
        fileName: `${baseName}.h`,
        content: `#ifndef ${includeGuard}
#define ${includeGuard}

class ${className} {
public:
    ${className}();
    void begin();
};

#endif
`,
    };
};

export const buildLibraryCppTemplate = (rawName) => {
    const baseName = getLibraryBaseName(rawName);
    const className = getLibraryClassName(baseName);

    return {
        fileName: `${baseName}.cpp`,
        content: `#include "${baseName}.h"

${className}::${className}() {
}

void ${className}::begin() {
}
`,
    };
};

// ─── C++ Include Helpers ───────────────────────────────────────────────────

export const normalizeCppInclude = (rawValue = "") => {
    const trimmedValue = rawValue.trim();
    if (!trimmedValue) return "";

    if (trimmedValue.startsWith("#include")) {
        return trimmedValue.replace(/\s+/g, " ").trim();
    }

    if (trimmedValue.startsWith("<") || trimmedValue.startsWith("\"")) {
        return `#include ${trimmedValue}`;
    }

    const headerName = /\.[a-z0-9]+$/i.test(trimmedValue) ? trimmedValue : `${trimmedValue}.h`;
    return `#include <${headerName}>`;
};

export const insertIncludeLineIntoSource = (sourceCode = "", includeLine) => {
    if (!includeLine) return sourceCode;
    const existingLines = sourceCode.split("\n");
    if (existingLines.some((line) => line.trim() === includeLine)) {
        return sourceCode;
    }

    let insertIndex = 0;
    while (insertIndex < existingLines.length) {
        const trimmedLine = existingLines[insertIndex].trim();

        if (
            !trimmedLine ||
            trimmedLine.startsWith("//") ||
            trimmedLine.startsWith("/*") ||
            trimmedLine.startsWith("*") ||
            trimmedLine.startsWith("*/")
        ) {
            insertIndex += 1;
            continue;
        }

        if (trimmedLine.startsWith("#include")) {
            while (insertIndex < existingLines.length && existingLines[insertIndex].trim().startsWith("#include")) {
                insertIndex += 1;
            }
        }
        break;
    }

    const nextLines = [...existingLines];
    nextLines.splice(insertIndex, 0, includeLine);
    return nextLines.join("\n");
};

export default BOARD_UPLOAD_CONFIG;
