import * as Blockly from 'blockly';

// ═══════════════════════════════════════════════════════════════════════════
// ANIMATION BLOCKS - For Stage Mode (sprites and animation)
// ═══════════════════════════════════════════════════════════════════════════

const COLORS = {
    motion: '#4A90E2',       // Blue - Motion blocks
    looks: '#8B5CF6',        // Purple - Looks blocks
    sound: '#D946EF',        // Fuchsia - Sound blocks
    events: '#FACC15',       // Yellow - Events
    control: '#F59E0B',      // Amber - Control blocks
    sensing: '#06B6D4',      // Cyan - Sensing
    operators: '#22C55E',    // Green - Operators
    data: '#F97316',         // Orange - Variables
    variables: '#F97316',    // Alias
    list: '#F97316',         // Unified orange
    myblocks: '#EC4899',     // Pink - My Blocks
    pen: '#00B1B0',          // Teal - Pen blocks (PictoBlox style)
};

export const animationBlocks = Blockly.common.createBlockDefinitionsFromJsonArray([
    // ═══════════════════════════════════════════════════════════════════════════
    // EVENTS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'event_flag_clicked',
        message0: '🏳️ when green flag clicked',
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when the green flag is clicked',
        helpUrl: '',
    },
    {
        type: 'event_sprite_clicked',
        message0: '👆 when this sprite clicked',
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when this sprite is clicked',
        helpUrl: '',
    },
    {
        type: 'event_key_pressed',
        message0: '⌨️ when %1 key pressed',
        args0: [{
            type: 'field_dropdown',
            name: 'KEY',
            options: [
                ['space', 'space'], ['up arrow', 'ArrowUp'], ['down arrow', 'ArrowDown'],
                ['left arrow', 'ArrowLeft'], ['right arrow', 'ArrowRight'],
                ['a', 'a'], ['b', 'b'], ['c', 'c'], ['d', 'd'], ['e', 'e'],
                ['w', 'w'], ['s', 's'],
            ],
        }],
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when a key is pressed',
        helpUrl: '',
    },
    {
        type: 'event_backdrop_switch',
        message0: '🎭 when backdrop switches to %1',
        args0: [{
            type: 'field_dropdown',
            name: 'BACKDROP',
            options: [['backdrop1', 'backdrop1']],
        }],
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when backdrop changes',
        helpUrl: '',
    },
    {
        type: 'event_greater_than',
        message0: '📊 when %1 > %2',
        args0: [
            { type: 'field_dropdown', name: 'SENSOR', options: [['loudness', 'loudness'], ['timer', 'timer']] },
            { type: 'field_number', name: 'VALUE', value: 10 },
        ],
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when value exceeds threshold',
        helpUrl: '',
    },
    {
        type: 'event_broadcast',
        message0: '📢 broadcast %1',
        args0: [{ type: 'field_input', name: 'MESSAGE', text: 'message1' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Send a message to all sprites',
        helpUrl: '',
    },
    {
        type: 'event_broadcast_wait',
        message0: '📢 broadcast %1 and wait',
        args0: [{ type: 'field_input', name: 'MESSAGE', text: 'message1' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Send message and wait for handlers',
        helpUrl: '',
    },
    {
        type: 'event_receive',
        message0: '📨 when I receive %1',
        args0: [{ type: 'field_input', name: 'MESSAGE', text: 'message1' }],
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when message received',
        helpUrl: '',
    },
    {
        type: 'event_clone_start',
        message0: '🔄 when I start as a clone',
        nextStatement: null,
        colour: COLORS.events,
        tooltip: 'Runs when this sprite starts as clone',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // MOTION
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'motion_move_steps',
        message0: '➡️ move %1 steps',
        args0: [{ type: 'field_number', name: 'STEPS', value: 10 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Move sprite forward',
        helpUrl: '',
    },
    {
        type: 'motion_turn_right',
        message0: '↻ turn right %1 degrees',
        args0: [{ type: 'field_number', name: 'DEGREES', value: 15 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Turn clockwise',
        helpUrl: '',
    },
    {
        type: 'motion_turn_left',
        message0: '↺ turn left %1 degrees',
        args0: [{ type: 'field_number', name: 'DEGREES', value: 15 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Turn counter-clockwise',
        helpUrl: '',
    },
    {
        type: 'motion_go_to_xy',
        message0: '📍 go to x: %1 y: %2',
        args0: [
            { type: 'field_number', name: 'X', value: 0 },
            { type: 'field_number', name: 'Y', value: 0 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Move sprite to position',
        helpUrl: '',
    },
    {
        type: 'motion_glide_to_xy',
        message0: '✨ glide %1 secs to x: %2 y: %3',
        args0: [
            { type: 'field_number', name: 'SECS', value: 1, min: 0.1 },
            { type: 'field_number', name: 'X', value: 0 },
            { type: 'field_number', name: 'Y', value: 0 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Glide smoothly to position',
        helpUrl: '',
    },
    {
        type: 'motion_point_direction',
        message0: '🧭 point in direction %1',
        args0: [{ type: 'field_number', name: 'DIRECTION', value: 90 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Point sprite in direction (90 = right)',
        helpUrl: '',
    },
    {
        type: 'motion_change_x',
        message0: '↔️ change x by %1',
        args0: [{ type: 'field_number', name: 'DX', value: 10 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Change horizontal position',
        helpUrl: '',
    },
    {
        type: 'motion_change_y',
        message0: '↕️ change y by %1',
        args0: [{ type: 'field_number', name: 'DY', value: 10 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Change vertical position',
        helpUrl: '',
    },
    {
        type: 'motion_set_x',
        message0: '📐 set x to %1',
        args0: [{ type: 'field_number', name: 'X', value: 0 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Set horizontal position',
        helpUrl: '',
    },
    {
        type: 'motion_set_y',
        message0: '📐 set y to %1',
        args0: [{ type: 'field_number', name: 'Y', value: 0 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.motion,
        tooltip: 'Set vertical position',
        helpUrl: '',
    },
    {
        type: 'motion_x_position',
        message0: 'x position',
        output: 'Number',
        colour: COLORS.motion,
        tooltip: 'Get x position of sprite',
        helpUrl: '',
    },
    {
        type: 'motion_y_position',
        message0: 'y position',
        output: 'Number',
        colour: COLORS.motion,
        tooltip: 'Get y position of sprite',
        helpUrl: '',
    },
    {
        type: 'motion_direction',
        message0: 'direction',
        output: 'Number',
        colour: COLORS.motion,
        tooltip: 'Get direction of sprite',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // LOOKS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'looks_say_for_secs',
        message0: '🗣️ say %1 for %2 seconds',
        args0: [
            { type: 'field_input', name: 'MESSAGE', text: 'Hello!' },
            { type: 'field_number', name: 'SECS', value: 2, min: 0.1 },
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Say message for seconds',
        helpUrl: '',
    },
    {
        type: 'looks_say',
        message0: '🗣️ say %1',
        args0: [{ type: 'field_input', name: 'MESSAGE', text: 'Hello!' }],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Say message',
        helpUrl: '',
    },
    {
        type: 'looks_show',
        message0: '👁️ show',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Make sprite visible',
        helpUrl: '',
    },
    {
        type: 'looks_hide',
        message0: '🙈 hide',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Make sprite invisible',
        helpUrl: '',
    },
    {
        type: 'looks_next_costume',
        message0: '👔 next costume',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Switch to next costume',
        helpUrl: '',
    },
    {
        type: 'looks_set_size',
        message0: '📏 set size to %1 %',
        args0: [{ type: 'field_number', name: 'SIZE', value: 100, min: 1, max: 500 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Set sprite size',
        helpUrl: '',
    },
    {
        type: 'looks_change_size',
        message0: '📏 change size by %1',
        args0: [{ type: 'field_number', name: 'CHANGE', value: 10 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Change sprite size',
        helpUrl: '',
    },
    {
        type: 'looks_set_effect',
        message0: '🎨 set %1 effect to %2',
        args0: [
            { type: 'field_dropdown', name: 'EFFECT', options: [['ghost', 'ghost'], ['brightness', 'brightness']] },
            { type: 'field_number', name: 'VALUE', value: 0 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Set graphic effect',
        helpUrl: '',
    },
    {
        type: 'looks_clear_effects',
        message0: '🎨 clear graphic effects',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Reset all effects',
        helpUrl: '',
    },
    {
        type: 'looks_think_for_secs',
        message0: '💭 think %1 for %2 seconds',
        args0: [
            { type: 'field_input', name: 'MESSAGE', text: 'Hmm...' },
            { type: 'field_number', name: 'SECS', value: 2, min: 0.1 },
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Show thought bubble for seconds',
        helpUrl: '',
    },
    {
        type: 'looks_think',
        message0: '💭 think %1',
        args0: [{ type: 'field_input', name: 'MESSAGE', text: 'Hmm...' }],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Show thought bubble',
        helpUrl: '',
    },
    {
        type: 'looks_switch_costume',
        message0: '👔 switch costume to %1',
        args0: [{
            type: 'field_dropdown',
            name: 'COSTUME',
            options: [['costume1', 'costume1'], ['costume2', 'costume2']],
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Switch to specific costume',
        helpUrl: '',
    },
    {
        type: 'looks_switch_backdrop',
        message0: '🎭 switch backdrop to %1',
        args0: [{
            type: 'field_dropdown',
            name: 'BACKDROP',
            options: [['backdrop1', 'backdrop1']],
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Change stage backdrop',
        helpUrl: '',
    },
    {
        type: 'looks_next_backdrop',
        message0: '🎭 next backdrop',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Switch to next backdrop',
        helpUrl: '',
    },
    {
        type: 'looks_go_to_layer',
        message0: '📚 go to %1 layer',
        args0: [{ type: 'field_dropdown', name: 'LAYER', options: [['front', 'front'], ['back', 'back']] }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Go to front or back layer',
        helpUrl: '',
    },
    {
        type: 'looks_go_forward_layers',
        message0: '📚 go %1 %2 layers',
        args0: [
            { type: 'field_dropdown', name: 'DIRECTION', options: [['forward', 'forward'], ['backward', 'backward']] },
            { type: 'field_number', name: 'LAYERS', value: 1, min: 1 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.looks,
        tooltip: 'Move layers forward/backward',
        helpUrl: '',
    },
    {
        type: 'looks_size',
        message0: 'size',
        output: 'Number',
        colour: COLORS.looks,
        tooltip: 'Get sprite size',
        helpUrl: '',
    },
    {
        type: 'looks_costume_number',
        message0: 'costume %1',
        args0: [{ type: 'field_dropdown', name: 'TYPE', options: [['number', 'number'], ['name', 'name']] }],
        output: null,
        colour: COLORS.looks,
        tooltip: 'Get costume number or name',
        helpUrl: '',
    },
    {
        type: 'looks_backdrop_number',
        message0: 'backdrop %1',
        args0: [{ type: 'field_dropdown', name: 'TYPE', options: [['number', 'number'], ['name', 'name']] }],
        output: null,
        colour: COLORS.looks,
        tooltip: 'Get backdrop number or name',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // CONTROL (Animation)
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'control_wait',
        message0: '⏱️ wait %1 seconds',
        args0: [{ type: 'field_number', name: 'SECS', value: 1, min: 0.1 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'Wait before continuing',
        helpUrl: '',
    },
    {
        type: 'control_repeat',
        message0: '🔁 repeat %1 times',
        args0: [{ type: 'field_number', name: 'TIMES', value: 10, min: 1 }],
        message1: '%1',
        args1: [{ type: 'input_statement', name: 'DO' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'Repeat code N times',
        helpUrl: '',
    },
    {
        type: 'control_forever',
        message0: '🔄 forever',
        message1: '%1',
        args1: [{ type: 'input_statement', name: 'DO' }],
        previousStatement: null,
        colour: COLORS.control,
        tooltip: 'Repeat forever',
        helpUrl: '',
    },
    {
        type: 'control_if',
        message0: '❓ if %1 then',
        args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
        message1: '%1',
        args1: [{ type: 'input_statement', name: 'DO' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'If condition is true',
        helpUrl: '',
    },
    {
        type: 'control_stop',
        message0: '🛑 stop %1',
        args0: [{
            type: 'field_dropdown',
            name: 'STOP_OPTION',
            options: [['all', 'all'], ['this script', 'this script'], ['other scripts in sprite', 'other scripts']],
        }],
        previousStatement: null,
        colour: COLORS.control,
        tooltip: 'Stop scripts',
        helpUrl: '',
    },
    {
        type: 'control_if_else',
        message0: '❓ if %1 then',
        args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
        message1: '%1',
        args1: [{ type: 'input_statement', name: 'DO' }],
        message2: 'else',
        message3: '%1',
        args3: [{ type: 'input_statement', name: 'ELSE' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'If-else condition',
        helpUrl: '',
    },
    {
        type: 'control_wait_until',
        message0: '⏳ wait until %1',
        args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'Wait until condition is true',
        helpUrl: '',
    },
    {
        type: 'control_repeat_until',
        message0: '🔁 repeat until %1',
        args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
        message1: '%1',
        args1: [{ type: 'input_statement', name: 'DO' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'Repeat until condition is true',
        helpUrl: '',
    },
    {
        type: 'control_create_clone',
        message0: '🔄 create clone of %1',
        args0: [{
            type: 'field_dropdown',
            name: 'CLONE_OPTION',
            options: [['myself', '_myself_']],
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.control,
        tooltip: 'Create a clone of this sprite',
        helpUrl: '',
    },
    {
        type: 'control_delete_clone',
        message0: '🗑️ delete this clone',
        previousStatement: null,
        colour: COLORS.control,
        tooltip: 'Delete this clone',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // SENSING
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'sensing_key_pressed',
        message0: 'key %1 pressed?',
        args0: [{
            type: 'field_dropdown',
            name: 'KEY',
            options: [
                ['space', 'space'], ['up arrow', 'ArrowUp'], ['down arrow', 'ArrowDown'],
                ['left arrow', 'ArrowLeft'], ['right arrow', 'ArrowRight'],
            ],
        }],
        output: 'Boolean',
        colour: COLORS.sensing,
        tooltip: 'Check if key is pressed',
        helpUrl: '',
    },
    {
        type: 'sensing_mouse_x',
        message0: 'mouse x',
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Mouse x position',
        helpUrl: '',
    },
    {
        type: 'sensing_mouse_y',
        message0: 'mouse y',
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Mouse y position',
        helpUrl: '',
    },
    {
        type: 'sensing_timer',
        message0: 'timer',
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Timer value in seconds',
        helpUrl: '',
    },
    {
        type: 'sensing_reset_timer',
        message0: 'reset timer',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sensing,
        tooltip: 'Reset the timer to 0',
        helpUrl: '',
    },
    {
        type: 'sensing_touching',
        message0: 'touching %1 ?',
        args0: [{
            type: 'field_dropdown',
            name: 'OBJECT',
            options: [['mouse-pointer', '_mouse_'], ['edge', '_edge_']],
        }],
        output: 'Boolean',
        colour: COLORS.sensing,
        tooltip: 'Check if touching object',
        helpUrl: '',
    },
    {
        type: 'sensing_touching_color',
        message0: 'touching color %1 ?',
        args0: [{ type: 'field_colour', name: 'COLOR', colour: '#ff0000' }],
        output: 'Boolean',
        colour: COLORS.sensing,
        tooltip: 'Check if touching a color',
        helpUrl: '',
    },
    {
        type: 'sensing_color_touching_color',
        message0: 'color %1 is touching %2 ?',
        args0: [
            { type: 'field_colour', name: 'COLOR1', colour: '#ff0000' },
            { type: 'field_colour', name: 'COLOR2', colour: '#00ff00' },
        ],
        output: 'Boolean',
        colour: COLORS.sensing,
        tooltip: 'Check if colors are touching',
        helpUrl: '',
    },
    {
        type: 'sensing_distance_to',
        message0: 'distance to %1',
        args0: [{
            type: 'field_dropdown',
            name: 'OBJECT',
            options: [['mouse-pointer', '_mouse_']],
        }],
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Distance to object',
        helpUrl: '',
    },
    {
        type: 'sensing_ask',
        message0: '❓ ask %1 and wait',
        args0: [{ type: 'field_input', name: 'QUESTION', text: "What's your name?" }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sensing,
        tooltip: 'Ask a question and wait for answer',
        helpUrl: '',
    },
    {
        type: 'sensing_answer',
        message0: 'answer',
        output: 'String',
        colour: COLORS.sensing,
        tooltip: 'The answer to the last question',
        helpUrl: '',
    },
    {
        type: 'sensing_mouse_down',
        message0: 'mouse down?',
        output: 'Boolean',
        colour: COLORS.sensing,
        tooltip: 'Check if mouse button is pressed',
        helpUrl: '',
    },
    {
        type: 'sensing_loudness',
        message0: 'loudness',
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Microphone loudness (0-100)',
        helpUrl: '',
    },
    {
        type: 'sensing_current',
        message0: 'current %1',
        args0: [{
            type: 'field_dropdown',
            name: 'CURRENTMENU',
            options: [
                ['year', 'year'], ['month', 'month'], ['date', 'date'],
                ['day of week', 'dayofweek'], ['hour', 'hour'], ['minute', 'minute'], ['second', 'second'],
            ],
        }],
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Current date/time value',
        helpUrl: '',
    },
    {
        type: 'sensing_days_since_2000',
        message0: 'days since 2000',
        output: 'Number',
        colour: COLORS.sensing,
        tooltip: 'Days since January 1, 2000',
        helpUrl: '',
    },
    {
        type: 'sensing_username',
        message0: 'username',
        output: 'String',
        colour: COLORS.sensing,
        tooltip: 'Current username',
        helpUrl: '',
    },
    // ═══════════════════════════════════════════════════════════════════════════
    // DATA / VARIABLES
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'data_setvariableto',
        message0: 'set %1 to %2',
        args0: [
            {
                type: 'field_variable',
                name: 'VARIABLE',
                variable: 'my variable',
                variableTypes: ['Number', 'String', '']
            },
            { type: 'input_value', name: 'VALUE' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.data,
        tooltip: 'Set variable to value',
        helpUrl: '',
    },
    {
        type: 'data_changevariableby',
        message0: 'change %1 by %2',
        args0: [
            {
                type: 'field_variable',
                name: 'VARIABLE',
                variable: 'my variable',
                variableTypes: ['Number', 'String', '']
            },
            { type: 'input_value', name: 'VALUE', check: 'Number' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.data,
        tooltip: 'Change variable by value',
        helpUrl: '',
    },
    {
        type: 'data_showvariable',
        message0: 'show variable %1',
        args0: [{
            type: 'field_variable',
            name: 'VARIABLE',
            variable: 'my variable',
            variableTypes: ['Number', 'String', '']
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.data,
        tooltip: 'Show variable monitor',
        helpUrl: '',
    },
    {
        type: 'data_hidevariable',
        message0: 'hide variable %1',
        args0: [{
            type: 'field_variable',
            name: 'VARIABLE',
            variable: 'my variable',
            variableTypes: ['Number', 'String', '']
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.data,
        tooltip: 'Hide variable monitor',
        helpUrl: '',
    },
    {
        type: 'variables_get',
        message0: '%1',
        args0: [
            {
                type: 'field_variable',
                name: 'VAR',
                variable: 'my variable',
                variableTypes: ['Number', 'String', '']
            }
        ],
        output: null,
        colour: COLORS.data,
        tooltip: 'Get variable value',
        helpUrl: '',
    },
    {
        type: 'variables_set',
        message0: 'set %1 to %2',
        args0: [
            {
                type: 'field_variable',
                name: 'VAR',
                variable: 'my variable',
                variableTypes: ['Number', 'String', '']
            },
            { type: 'input_value', name: 'VALUE' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.data,
        tooltip: 'Set variable to value',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // SOUND
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'sound_play',
        message0: '🔊 start sound %1',
        args0: [{
            type: 'field_dropdown',
            name: 'SOUND',
            options: [['pop', 'pop'], ['meow', 'meow'], ['boing', 'boing']],
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Play a sound',
        helpUrl: '',
    },
    {
        type: 'sound_play_until_done',
        message0: '🔊 play sound %1 until done',
        args0: [{
            type: 'field_dropdown',
            name: 'SOUND',
            options: [['pop', 'pop'], ['meow', 'meow'], ['boing', 'boing']],
        }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Play sound and wait',
        helpUrl: '',
    },
    {
        type: 'sound_stop_all',
        message0: '🔇 stop all sounds',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Stop all sounds',
        helpUrl: '',
    },
    {
        type: 'sound_set_volume',
        message0: '🔊 set volume to %1 %',
        args0: [{ type: 'field_number', name: 'VOLUME', value: 100, min: 0, max: 100 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Set volume level',
        helpUrl: '',
    },
    {
        type: 'sound_change_volume',
        message0: '🔊 change volume by %1',
        args0: [{ type: 'field_number', name: 'VOLUME', value: -10 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Change volume',
        helpUrl: '',
    },
    {
        type: 'sound_set_effect',
        message0: '🔊 set %1 effect to %2',
        args0: [
            { type: 'field_dropdown', name: 'EFFECT', options: [['pitch', 'pitch'], ['pan', 'pan']] },
            { type: 'field_number', name: 'VALUE', value: 100 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Set sound effect',
        helpUrl: '',
    },
    {
        type: 'sound_change_effect',
        message0: '🔊 change %1 effect by %2',
        args0: [
            { type: 'field_dropdown', name: 'EFFECT', options: [['pitch', 'pitch'], ['pan', 'pan']] },
            { type: 'field_number', name: 'VALUE', value: 10 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Change sound effect',
        helpUrl: '',
    },
    {
        type: 'sound_clear_effects',
        message0: '🔊 clear sound effects',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.sound,
        tooltip: 'Clear all sound effects',
        helpUrl: '',
    },
    {
        type: 'sound_volume',
        message0: 'volume',
        output: 'Number',
        colour: COLORS.sound,
        tooltip: 'Get current volume',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // OPERATORS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'operator_add',
        message0: '%1 + %2',
        args0: [
            { type: 'field_number', name: 'NUM1', value: 0 },
            { type: 'field_number', name: 'NUM2', value: 0 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Add two numbers',
        helpUrl: '',
    },
    {
        type: 'operator_subtract',
        message0: '%1 - %2',
        args0: [
            { type: 'field_number', name: 'NUM1', value: 0 },
            { type: 'field_number', name: 'NUM2', value: 0 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Subtract two numbers',
        helpUrl: '',
    },
    {
        type: 'operator_multiply',
        message0: '%1 × %2',
        args0: [
            { type: 'field_number', name: 'NUM1', value: 0 },
            { type: 'field_number', name: 'NUM2', value: 0 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Multiply two numbers',
        helpUrl: '',
    },
    {
        type: 'operator_divide',
        message0: '%1 ÷ %2',
        args0: [
            { type: 'field_number', name: 'NUM1', value: 0 },
            { type: 'field_number', name: 'NUM2', value: 1 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Divide two numbers',
        helpUrl: '',
    },
    {
        type: 'operator_random',
        message0: 'pick random %1 to %2',
        args0: [
            { type: 'field_number', name: 'FROM', value: 1 },
            { type: 'field_number', name: 'TO', value: 10 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Random number',
        helpUrl: '',
    },
    {
        type: 'operator_gt',
        message0: '%1 > %2',
        args0: [
            { type: 'field_number', name: 'OPERAND1', value: 0 },
            { type: 'field_number', name: 'OPERAND2', value: 50 },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        tooltip: 'Greater than',
        helpUrl: '',
    },
    {
        type: 'operator_lt',
        message0: '%1 < %2',
        args0: [
            { type: 'field_number', name: 'OPERAND1', value: 0 },
            { type: 'field_number', name: 'OPERAND2', value: 50 },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        tooltip: 'Less than',
        helpUrl: '',
    },
    {
        type: 'operator_equals',
        message0: '%1 = %2',
        args0: [
            { type: 'field_number', name: 'OPERAND1', value: 0 },
            { type: 'field_number', name: 'OPERAND2', value: 50 },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        tooltip: 'Equals',
        helpUrl: '',
    },
    {
        type: 'operator_and',
        message0: '%1 and %2',
        args0: [
            { type: 'input_value', name: 'OPERAND1', check: 'Boolean' },
            { type: 'input_value', name: 'OPERAND2', check: 'Boolean' },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        inputsInline: true,
        tooltip: 'And',
        helpUrl: '',
    },
    {
        type: 'operator_or',
        message0: '%1 or %2',
        args0: [
            { type: 'input_value', name: 'OPERAND1', check: 'Boolean' },
            { type: 'input_value', name: 'OPERAND2', check: 'Boolean' },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        inputsInline: true,
        tooltip: 'Or',
        helpUrl: '',
    },
    {
        type: 'operator_not',
        message0: 'not %1',
        args0: [{ type: 'input_value', name: 'OPERAND', check: 'Boolean' }],
        output: 'Boolean',
        colour: COLORS.operators,
        tooltip: 'Not',
        helpUrl: '',
    },
    {
        type: 'operator_mod',
        message0: '%1 mod %2',
        args0: [
            { type: 'field_number', name: 'NUM1', value: 0 },
            { type: 'field_number', name: 'NUM2', value: 1 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Modulo (remainder)',
        helpUrl: '',
    },
    {
        type: 'operator_round',
        message0: 'round %1',
        args0: [{ type: 'field_number', name: 'NUM', value: 0 }],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Round to nearest integer',
        helpUrl: '',
    },
    {
        type: 'operator_mathop',
        message0: '%1 of %2',
        args0: [
            {
                type: 'field_dropdown', name: 'OPERATOR', options: [
                    ['abs', 'abs'], ['floor', 'floor'], ['ceiling', 'ceiling'],
                    ['sqrt', 'sqrt'], ['sin', 'sin'], ['cos', 'cos'], ['tan', 'tan'],
                ]
            },
            { type: 'field_number', name: 'NUM', value: 0 },
        ],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Math operation',
        helpUrl: '',
    },
    {
        type: 'operator_join',
        message0: 'join %1 %2',
        args0: [
            { type: 'field_input', name: 'STRING1', text: 'hello ' },
            { type: 'field_input', name: 'STRING2', text: 'world' },
        ],
        output: 'String',
        colour: COLORS.operators,
        tooltip: 'Join two strings',
        helpUrl: '',
    },
    {
        type: 'operator_letter_of',
        message0: 'letter %1 of %2',
        args0: [
            { type: 'field_number', name: 'LETTER', value: 1, min: 1 },
            { type: 'field_input', name: 'STRING', text: 'apple' },
        ],
        output: 'String',
        colour: COLORS.operators,
        tooltip: 'Letter at position',
        helpUrl: '',
    },
    {
        type: 'operator_length',
        message0: 'length of %1',
        args0: [{ type: 'field_input', name: 'STRING', text: 'apple' }],
        output: 'Number',
        colour: COLORS.operators,
        tooltip: 'Length of string',
        helpUrl: '',
    },
    {
        type: 'operator_contains',
        message0: '%1 contains %2 ?',
        args0: [
            { type: 'field_input', name: 'STRING1', text: 'apple' },
            { type: 'field_input', name: 'STRING2', text: 'a' },
        ],
        output: 'Boolean',
        colour: COLORS.operators,
        tooltip: 'Check if string contains substring',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // VARIABLES
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'data_setvariableto',
        message0: 'set %1 to %2',
        args0: [
            { type: 'field_variable', name: 'VARIABLE', variable: 'my variable' },
            { type: 'field_number', name: 'VALUE', value: 0 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.variables,
        tooltip: 'Set variable value',
        helpUrl: '',
    },
    {
        type: 'data_changevariableby',
        message0: 'change %1 by %2',
        args0: [
            { type: 'field_variable', name: 'VARIABLE', variable: 'my variable' },
            { type: 'field_number', name: 'VALUE', value: 1 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.variables,
        tooltip: 'Change variable by amount',
        helpUrl: '',
    },
    {
        type: 'data_showvariable',
        message0: 'show variable %1',
        args0: [{ type: 'field_variable', name: 'VARIABLE', variable: 'my variable' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.variables,
        tooltip: 'Show variable on stage',
        helpUrl: '',
    },
    {
        type: 'data_hidevariable',
        message0: 'hide variable %1',
        args0: [{ type: 'field_variable', name: 'VARIABLE', variable: 'my variable' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.variables,
        tooltip: 'Hide variable from stage',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // LISTS
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'data_listcontents',
        message0: 'list %1',
        args0: [{ type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' }],
        output: 'String', // Returns string representation
        colour: COLORS.list,
        tooltip: 'List contents',
        helpUrl: '',
    },
    {
        type: 'data_addtolist',
        message0: 'add %1 to %2',
        args0: [
            { type: 'input_value', name: 'ITEM' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Add item to list',
        helpUrl: '',
    },
    {
        type: 'data_deleteoflist',
        message0: 'delete %1 of %2',
        args0: [
            { type: 'input_value', name: 'INDEX' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Delete item at index',
        helpUrl: '',
    },
    {
        type: 'data_deletealloflist',
        message0: 'delete all of %1',
        args0: [{ type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Delete all items',
        helpUrl: '',
    },
    {
        type: 'data_insertatlist',
        message0: 'insert %1 at %2 of %3',
        args0: [
            { type: 'input_value', name: 'ITEM' },
            { type: 'input_value', name: 'INDEX' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Insert item at index',
        helpUrl: '',
    },
    {
        type: 'data_replaceitemoflist',
        message0: 'replace item %1 of %2 with %3',
        args0: [
            { type: 'input_value', name: 'INDEX' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
            { type: 'input_value', name: 'ITEM' },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Replace item at index',
        helpUrl: '',
    },
    {
        type: 'data_itemoflist',
        message0: 'item %1 of %2',
        args0: [
            { type: 'input_value', name: 'INDEX' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
        ],
        output: null,
        colour: COLORS.list,
        tooltip: 'Get item at index',
        helpUrl: '',
    },
    {
        type: 'data_itemnumoflist',
        message0: 'item # of %1 in %2',
        args0: [
            { type: 'input_value', name: 'ITEM' },
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
        ],
        output: 'Number',
        colour: COLORS.list,
        tooltip: 'Get index of item',
        helpUrl: '',
    },
    {
        type: 'data_lengthoflist',
        message0: 'length of %1',
        args0: [{ type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' }],
        output: 'Number',
        colour: COLORS.list,
        tooltip: 'Length of list',
        helpUrl: '',
    },
    {
        type: 'data_listcontainsitem',
        message0: '%1 contains %2 ?',
        args0: [
            { type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' },
            { type: 'input_value', name: 'ITEM' },
        ],
        output: 'Boolean',
        colour: COLORS.list,
        tooltip: 'Check if list contains item',
        helpUrl: '',
    },
    {
        type: 'data_showlist',
        message0: 'show list %1',
        args0: [{ type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Show list monitor',
        helpUrl: '',
    },
    {
        type: 'data_hidelist',
        message0: 'hide list %1',
        args0: [{ type: 'field_variable', name: 'LIST', variable: 'my list', variableTypes: ['list'], defaultType: 'list' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.list,
        tooltip: 'Hide list monitor',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // MY BLOCKS (Custom procedures)
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'procedures_definition',
        message0: 'define %1',
        args0: [{ type: 'field_input', name: 'NAME', text: 'my block' }],
        nextStatement: null,
        colour: COLORS.myblocks,
        tooltip: 'Define a custom block',
        helpUrl: '',
    },
    {
        type: 'procedures_call',
        message0: 'my block',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.myblocks,
        tooltip: 'Call custom block',
        helpUrl: '',
    },

    // ═══════════════════════════════════════════════════════════════════════════
    // PEN
    // ═══════════════════════════════════════════════════════════════════════════
    {
        type: 'pen_clear',
        message0: '🖌️ erase all',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Clear all pen marks',
        helpUrl: '',
    },
    {
        type: 'pen_stamp',
        message0: '🖼️ stamp',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Stamp the sprite onto the background',
        helpUrl: '',
    },
    {
        type: 'pen_penDown',
        message0: '🖋️ pen down',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Start drawing with the pen',
        helpUrl: '',
    },
    {
        type: 'pen_penUp',
        message0: '🖊️ pen up',
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Stop drawing with the pen',
        helpUrl: '',
    },
    {
        type: 'pen_setPenColorToColor',
        message0: '🎨 set pen color to %1',
        args0: [{ type: 'field_colour', name: 'COLOR', colour: '#4c97ff' }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Set the pen color',
        helpUrl: '',
    },
    {
        type: 'pen_changePenSizeBy',
        message0: '📏 change pen size by %1',
        args0: [{ type: 'field_number', name: 'SIZE', value: 1 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Change the pen thickness',
        helpUrl: '',
    },
    {
        type: 'pen_setPenSizeTo',
        message0: '📏 set pen size to %1',
        args0: [{ type: 'field_number', name: 'SIZE', value: 1 }],
        previousStatement: null,
        nextStatement: null,
        colour: COLORS.pen,
        tooltip: 'Set the pen thickness',
        helpUrl: '',
    }
]);

// Animation Toolbox
export const animationToolbox = {
    kind: 'categoryToolbox',
    contents: [
        {
            kind: 'pictobloxCategory',
            name: 'Events',
            colour: COLORS.events,
            contents: [
                { kind: 'block', type: 'event_flag_clicked' },
                { kind: 'block', type: 'event_sprite_clicked' },
                { kind: 'block', type: 'event_key_pressed' },
                { kind: 'label', text: '── Broadcast ──' },
                { kind: 'block', type: 'event_broadcast' },
                { kind: 'block', type: 'event_broadcast_wait' },
                { kind: 'block', type: 'event_receive' },
                { kind: 'label', text: '── Other ──' },
                { kind: 'block', type: 'event_backdrop_switch' },
                { kind: 'block', type: 'event_greater_than' },
                { kind: 'block', type: 'event_clone_start' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Motion',
            colour: COLORS.motion,
            contents: [
                { kind: 'block', type: 'motion_move_steps' },
                { kind: 'block', type: 'motion_turn_right' },
                { kind: 'block', type: 'motion_turn_left' },
                { kind: 'label', text: '── Position ──' },
                { kind: 'block', type: 'motion_go_to_xy' },
                { kind: 'block', type: 'motion_glide_to_xy' },
                { kind: 'block', type: 'motion_point_direction' },
                { kind: 'label', text: '── Change ──' },
                { kind: 'block', type: 'motion_change_x' },
                { kind: 'block', type: 'motion_change_y' },
                { kind: 'block', type: 'motion_set_x' },
                { kind: 'block', type: 'motion_set_y' },
                { kind: 'label', text: '── Reporters ──' },
                { kind: 'block', type: 'motion_x_position' },
                { kind: 'block', type: 'motion_y_position' },
                { kind: 'block', type: 'motion_direction' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Looks',
            colour: COLORS.looks,
            contents: [
                { kind: 'block', type: 'looks_say_for_secs' },
                { kind: 'block', type: 'looks_say' },
                { kind: 'block', type: 'looks_think_for_secs' },
                { kind: 'block', type: 'looks_think' },
                { kind: 'label', text: '── Visibility ──' },
                { kind: 'block', type: 'looks_show' },
                { kind: 'block', type: 'looks_hide' },
                { kind: 'label', text: '── Costume ──' },
                { kind: 'block', type: 'looks_switch_costume' },
                { kind: 'block', type: 'looks_next_costume' },
                { kind: 'block', type: 'looks_switch_backdrop' },
                { kind: 'block', type: 'looks_next_backdrop' },
                { kind: 'label', text: '── Size ──' },
                { kind: 'block', type: 'looks_set_size' },
                { kind: 'block', type: 'looks_change_size' },
                { kind: 'label', text: '── Effects ──' },
                { kind: 'block', type: 'looks_set_effect' },
                { kind: 'block', type: 'looks_clear_effects' },
                { kind: 'label', text: '── Layers ──' },
                { kind: 'block', type: 'looks_go_to_layer' },
                { kind: 'block', type: 'looks_go_forward_layers' },
                { kind: 'label', text: '── Reporters ──' },
                { kind: 'block', type: 'looks_size' },
                { kind: 'block', type: 'looks_costume_number' },
                { kind: 'block', type: 'looks_backdrop_number' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Sound',
            colour: COLORS.sound,
            contents: [
                { kind: 'block', type: 'sound_play' },
                { kind: 'block', type: 'sound_play_until_done' },
                { kind: 'block', type: 'sound_stop_all' },
                { kind: 'label', text: '── Volume ──' },
                { kind: 'block', type: 'sound_set_volume' },
                { kind: 'block', type: 'sound_change_volume' },
                { kind: 'block', type: 'sound_volume' },
                { kind: 'label', text: '── Effects ──' },
                { kind: 'block', type: 'sound_set_effect' },
                { kind: 'block', type: 'sound_change_effect' },
                { kind: 'block', type: 'sound_clear_effects' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Control',
            colour: COLORS.control,
            contents: [
                { kind: 'block', type: 'control_wait' },
                { kind: 'label', text: '── Loops ──' },
                { kind: 'block', type: 'control_repeat' },
                { kind: 'block', type: 'control_forever' },
                { kind: 'block', type: 'control_repeat_until' },
                { kind: 'label', text: '── Conditions ──' },
                { kind: 'block', type: 'control_if' },
                { kind: 'block', type: 'control_if_else' },
                { kind: 'block', type: 'control_wait_until' },
                { kind: 'label', text: '── Cloning ──' },
                { kind: 'block', type: 'control_create_clone' },
                { kind: 'block', type: 'control_delete_clone' },
                { kind: 'label', text: '── Stop ──' },
                { kind: 'block', type: 'control_stop' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Sensing',
            colour: COLORS.sensing,
            contents: [
                { kind: 'block', type: 'sensing_touching' },
                { kind: 'block', type: 'sensing_touching_color' },
                { kind: 'block', type: 'sensing_color_touching_color' },
                { kind: 'block', type: 'sensing_distance_to' },
                { kind: 'label', text: '── Ask ──' },
                { kind: 'block', type: 'sensing_ask' },
                { kind: 'block', type: 'sensing_answer' },
                { kind: 'label', text: '── Keyboard ──' },
                { kind: 'block', type: 'sensing_key_pressed' },
                { kind: 'label', text: '── Mouse ──' },
                { kind: 'block', type: 'sensing_mouse_down' },
                { kind: 'block', type: 'sensing_mouse_x' },
                { kind: 'block', type: 'sensing_mouse_y' },
                { kind: 'label', text: '── Sound ──' },
                { kind: 'block', type: 'sensing_loudness' },
                { kind: 'label', text: '── Timer ──' },
                { kind: 'block', type: 'sensing_timer' },
                { kind: 'block', type: 'sensing_reset_timer' },
                { kind: 'label', text: '── Date/Time ──' },
                { kind: 'block', type: 'sensing_current' },
                { kind: 'block', type: 'sensing_days_since_2000' },
                { kind: 'block', type: 'sensing_username' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Operators',
            colour: COLORS.operators,
            contents: [
                { kind: 'block', type: 'operator_add' },
                { kind: 'block', type: 'operator_subtract' },
                { kind: 'block', type: 'operator_multiply' },
                { kind: 'block', type: 'operator_divide' },
                { kind: 'label', text: '── Random ──' },
                { kind: 'block', type: 'operator_random' },
                { kind: 'label', text: '── Compare ──' },
                { kind: 'block', type: 'operator_gt' },
                { kind: 'block', type: 'operator_lt' },
                { kind: 'block', type: 'operator_equals' },
                { kind: 'label', text: '── Logic ──' },
                { kind: 'block', type: 'operator_and' },
                { kind: 'block', type: 'operator_or' },
                { kind: 'block', type: 'operator_not' },
                { kind: 'label', text: '── Math ──' },
                { kind: 'block', type: 'operator_mod' },
                { kind: 'block', type: 'operator_round' },
                { kind: 'block', type: 'operator_mathop' },
                { kind: 'label', text: '── Strings ──' },
                { kind: 'block', type: 'operator_join' },
                { kind: 'block', type: 'operator_letter_of' },
                { kind: 'block', type: 'operator_length' },
                { kind: 'block', type: 'operator_contains' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Variables',
            colour: COLORS.data,
            custom: 'LEAP_VARIABLES',
            contents: [], // Ignored, handled by callback
        },
        {
            kind: 'pictobloxCategory',
            name: 'My Blocks',
            colour: COLORS.myblocks,
            contents: [
                { kind: 'button', text: 'Make a Block', callbackKey: 'CREATE_PROCEDURE' },
                { kind: 'block', type: 'procedures_definition' },
                { kind: 'block', type: 'procedures_call' },
            ],
        },
        {
            kind: 'pictobloxCategory',
            name: 'Pen',
            colour: COLORS.pen,
            contents: [
                { kind: 'block', type: 'pen_clear' },
                { kind: 'block', type: 'pen_stamp' },
                { kind: 'block', type: 'pen_penDown' },
                { kind: 'block', type: 'pen_penUp' },
                { kind: 'block', type: 'pen_setPenColorToColor' },
                { kind: 'block', type: 'pen_changePenSizeBy' },
                { kind: 'block', type: 'pen_setPenSizeTo' },
            ],
        },
    ],
};
