/**
 * Copyright (c) 2026 Creoleap Technologies Pvt. Ltd.
 * All rights reserved. Proprietary and confidential.
 * Unauthorized copying, distribution, or modification is strictly prohibited.
 */

/**
 * Tailwind CSS Utility Class Dictionary for Intermediate App Layout & Components.
 * Converted from inline React.CSSProperties to native Tailwind CSS class strings.
 */
export const styles: Record<string, string> = {
    container: "flex flex-col h-screen bg-[#f5f5f5] font-sans",
    header: "flex justify-between items-center px-3 h-[48px] bg-[#855CD6] text-white",
    headerLeft: "flex items-center gap-4",
    logo: "text-[18px] font-bold",
    nav: "flex gap-4 ml-6",
    navItem: "text-[13px] cursor-pointer opacity-90",
    projectName: "flex items-center gap-1.5 bg-white/15 px-3 py-1 rounded ml-4",
    projectInput: "bg-transparent border-none text-white text-[13px] w-[100px] outline-none",
    headerRight: "flex items-center gap-2",
    headerDivider: "w-px h-6 bg-white/30 mx-1",
    modeButton: "px-3 py-1.5 bg-white/20 border-none rounded text-white text-xs cursor-pointer",
    modeButtonActive: "px-3 py-1.5 bg-[#4C97FF] border-none rounded text-white text-xs cursor-pointer font-bold",
    portSelect: "px-2 py-1 rounded border-none text-xs",
    uploadButton: "px-3.5 py-1.5 bg-[#4C97FF] border-none rounded text-white text-xs font-bold cursor-pointer",
    headerIcon: "cursor-pointer opacity-90 text-[14px]",
    unifiedToolbar: "flex items-end bg-white border-b border-gray-300 h-[44px] p-0",
    actionButtons: "flex gap-1.5 items-center",
    iconBtn: "bg-transparent border-none cursor-pointer flex items-center justify-center p-1.25 rounded text-[#575E75] transition-colors duration-200 outline-none hover:bg-gray-100",
    iconBtnActive: "bg-[#e0d6ff] text-[#855CD6]",
    runButtonTop: "bg-transparent border-none cursor-pointer flex justify-center items-center p-1",
    stopButtonTop: "bg-transparent border-none cursor-pointer flex justify-center items-center p-1",
    undoRedoBtn: "bg-white border border-gray-300 rounded-full w-8 h-8 flex items-center justify-center cursor-pointer shadow-sm transition-all duration-200 outline-none hover:bg-gray-50",
    main: "flex-1 flex overflow-hidden min-h-0 relative",
    workspaceContainer: "flex-1 relative flex flex-col min-w-0 overflow-visible",
    blockly: "flex-1 w-full min-h-0",
    tabBar: "flex justify-start items-end bg-white border-b border-gray-300 px-5 h-[44px] gap-1",
    tab: "px-6 py-2 border-t border-l border-r border-gray-300 border-b-0 bg-[#f9f9f9] cursor-pointer text-[13px] font-semibold text-gray-400 rounded-t-[10px] flex items-center gap-2.5 transition-all duration-200",
    tabActive: "px-6 py-2.5 border-t border-l border-r border-gray-300 border-b-white bg-white cursor-pointer text-[13px] font-semibold text-[#855CD6] -mb-px rounded-t-[10px] flex items-center gap-2 z-10 shadow-sm",
    pythonEditor: "flex-1 flex flex-col bg-[#1e1e1e] overflow-hidden",
    pythonPlaceholder: "text-center text-gray-500",
    costumesEditor: "flex-1 flex overflow-hidden bg-white",
    costumePlaceholder: "text-center text-gray-500",
    soundsEditor: "flex-1 flex flex-col overflow-hidden bg-[#f9f9f9]",
    soundPlaceholder: "text-center text-gray-500",
    rightPanel: "w-[450px] shrink-0 bg-[#f5f5f5] border-l border-gray-300 flex flex-col gap-2 p-2 overflow-hidden h-full",
    assetsContainer: "flex gap-2 items-center justify-center",
    stageContainer: "bg-white rounded-lg overflow-hidden shadow-sm",
    stageHeader: "flex justify-between items-center px-2.5 py-1.5 bg-gray-50 border-b border-gray-200 text-xs font-medium",
    flagButton: "px-2 py-1 border border-[#4CAF50] rounded bg-white cursor-pointer text-[15px] mr-1 hover:bg-green-50",
    stopButtonSmall: "px-2 py-1 border border-[#f44336] rounded bg-white cursor-pointer text-[15px] hover:bg-red-50",
    codeHeader: "flex justify-between items-center px-3 py-2 border-b border-gray-100 bg-[#f9f9f9] text-[13px] font-medium rounded-t-lg shrink-0",
    uploadCodeBtn: "px-3 py-1.5 bg-[#4C97FF] border-none rounded text-white text-[11px] cursor-pointer",
    codeArea: "overflow-auto bg-gray-50 rounded-b-lg border-b border-l border-r border-gray-100 border-t-0",
    codeContent: "m-0 p-3 font-mono text-xs leading-relaxed text-gray-800",
    codeLine: "flex",
    lineNumber: "w-[35px] pr-2.5 text-right text-gray-400 select-none",
    bottomTabs: "flex border-t border-gray-300 shrink-0",
    bottomTab: "px-4 py-2 bg-[#f5f5f5] border-b-2 border-transparent text-xs cursor-pointer text-gray-600 hover:text-gray-900",
    bottomTabActive: "px-4 py-2 bg-white border-b-2 border-[#4C97FF] text-xs cursor-pointer text-[#4C97FF] font-bold",
    logArea: "overflow-auto px-3 py-2 bg-white text-[11px] font-mono rounded-b-lg flex flex-col",
    logLine: "text-gray-600 mb-0.5",
    refreshButton: "px-2 py-1 bg-white/20 border-none rounded text-white text-xs cursor-pointer",
    connectButton: "px-3 py-1.5 bg-white/20 border-none rounded text-white text-xs cursor-pointer",
    connectedButton: "px-3 py-1.5 bg-[#4CAF50] border-none rounded text-white text-xs cursor-pointer font-bold",
    uploadButtonDisabled: "px-3.5 py-1.5 bg-gray-400 border-none rounded text-white text-xs cursor-not-allowed",
    uploadStatus: "text-[11px] text-[#4CAF50]",
    serialContainer: "flex flex-col h-full",
    serialMessages: "flex-1 overflow-auto pb-1",
    serialLine: "text-gray-800 mb-px font-mono text-[11px] whitespace-pre-wrap break-all",
    serialHeader: "flex justify-between items-center px-2 py-1 border-b border-gray-100 bg-[#f9f9f9]",
    serialSelect: "px-1 py-0.5 text-[10px] border border-gray-300 rounded outline-none",
    clearButton: "px-1.5 py-0.5 bg-transparent border-none cursor-pointer text-xs opacity-70 hover:opacity-100",
    serialPlaceholder: "text-gray-400 text-center p-3 text-[11px]",
    serialInputRow: "flex gap-1 pt-1 border-t border-gray-100",
    serialInput: "flex-1 px-2 py-1 border border-gray-300 rounded text-[11px] font-mono",
    sendButton: "px-3 py-1 bg-[#4C97FF] border-none rounded text-white text-[11px] cursor-pointer",
    modalOverlay: "fixed inset-0 bg-black/50 flex items-center justify-center z-[9999] backdrop-blur-sm",
    modalContent: "bg-white rounded-lg w-[400px] shadow-2xl overflow-hidden flex flex-col gap-4 animate-in fade-in zoom-in-95 duration-200",
    modalTitle: "bg-[#855CD6] text-white px-4 py-3 text-base font-bold flex justify-between items-center",
    modalInput: "p-3 text-base rounded-lg border border-gray-300 w-full outline-none focus:border-[#855CD6]",
    modalButtons: "flex justify-end gap-3",
    modalCancel: "px-4 py-2 rounded-md border border-gray-300 bg-white cursor-pointer text-sm text-gray-600 hover:bg-gray-50",
    modalSubmit: "px-4 py-2 rounded-md border-none bg-[#4C97FF] text-white cursor-pointer font-bold text-sm hover:bg-blue-600",
};
