import type React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        backgroundColor: '#f5f5f5',
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '0 12px',
        height: '48px',
        backgroundColor: '#855CD6',
        color: 'white',
    },
    headerLeft: { display: 'flex', alignItems: 'center', gap: '16px' },
    logo: { fontSize: '18px', fontWeight: 'bold' },
    nav: { display: 'flex', gap: '16px', marginLeft: '24px' },
    navItem: { fontSize: '13px', cursor: 'pointer', opacity: 0.9 },
    projectName: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        backgroundColor: 'rgba(255,255,255,0.15)',
        padding: '4px 12px',
        borderRadius: '4px',
        marginLeft: '16px',
    },
    projectInput: { background: 'transparent', border: 'none', color: 'white', fontSize: '13px', width: '100px' },
    headerRight: { display: 'flex', alignItems: 'center', gap: '8px' },
    headerDivider: { width: '1px', height: '24px', backgroundColor: 'rgba(255,255,255,0.3)', margin: '0 4px' },
    modeButton: {
        padding: '6px 12px',
        backgroundColor: 'rgba(255,255,255,0.2)',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'pointer'
    },
    modeButtonActive: {
        padding: '6px 12px',
        backgroundColor: '#4C97FF',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'pointer',
        fontWeight: 'bold',
    },
    portSelect: {
        padding: '4px 8px',
        borderRadius: '4px',
        border: 'none',
        fontSize: '12px',
    },
    uploadButton: {
        padding: '6px 14px',
        backgroundColor: '#4C97FF',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        fontWeight: 'bold',
        cursor: 'pointer'
    },
    headerIcon: { cursor: 'pointer', opacity: 0.9, fontSize: '14px' },
    unifiedToolbar: {
        display: 'flex',
        alignItems: 'flex-end',
        backgroundColor: '#fff',
        borderBottom: '1px solid #ddd',
        height: '44px',
        padding: '0',
    },
    actionButtons: { display: 'flex', gap: '6px', alignItems: 'center' },
    iconBtn: {
        background: 'transparent',
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '5px',
        borderRadius: '4px',
        color: '#575E75',
        transition: 'background 0.2s',
        outline: 'none',
    },
    iconBtnActive: {
        background: '#e0d6ff',
        color: '#855CD6'
    },
    runButtonTop: {
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '4px',
    },
    stopButtonTop: {
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        padding: '4px',
    },
    undoRedoBtn: {
        backgroundColor: '#fff',
        border: '1px solid #ddd',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
        transition: 'all 0.2s',
        outline: 'none',
    },
    main: {
        flex: 1,
        display: 'flex',
        overflow: 'hidden',
        minHeight: 0,
        position: 'relative'
    },
    workspaceContainer: {
        flex: 1,
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        minWidth: 0,
        overflow: 'visible'
    },
    blockly: {
        flex: 1,
        width: '100%',
        minHeight: 0
    },
    tabBar: {
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'end',
        backgroundColor: '#fff',
        borderBottom: '1px solid #ddd',
        padding: '0 20px',
        height: '44px',
        gap: '4px',
    },
    tab: {
        padding: '8px 24px',
        borderTop: '1px solid #ddd',
        borderLeft: '1px solid #ddd',
        borderRight: '1px solid #ddd',
        borderBottom: 'none',
        backgroundColor: '#f9f9f9',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 600,
        color: '#999',
        borderTopLeftRadius: '10px',
        borderTopRightRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        transition: 'all 0.2s',
    },
    tabActive: {
        padding: '10px 24px',
        borderTop: '1px solid #ddd',
        borderLeft: '1px solid #ddd',
        borderRight: '1px solid #ddd',
        borderBottom: '1px solid #fff',
        backgroundColor: '#fff',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 600,
        color: '#855CD6',
        marginBottom: '-1px',
        borderTopLeftRadius: '10px',
        borderTopRightRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        zIndex: 5,
        boxShadow: '0 -2px 10px rgba(0,0,0,0.05)',
    },
    pythonEditor: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#1e1e1e',
        overflow: 'hidden'
    },
    pythonPlaceholder: {
        textAlign: 'center',
        color: '#888',
    },
    costumesEditor: {
        flex: 1,
        display: 'flex',
        overflow: 'hidden',
        backgroundColor: '#fff',
    },
    costumePlaceholder: {
        textAlign: 'center',
        color: '#666',
    },
    soundsEditor: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        backgroundColor: '#f9f9f9',
    },
    soundPlaceholder: {
        textAlign: 'center',
        color: '#666',
    },
    rightPanel: {
        width: '450px',
        flexShrink: 0,
        backgroundColor: '#f5f5f5',
        borderLeft: '1px solid #d9d9d9',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        padding: '8px',
        overflow: 'hidden',
        height: '100%',
    },
    assetsContainer: {
        display: 'flex',
        gap: '8px',
        alignItems: 'center',
        justifyContent: 'center',
    },
    stageContainer: {
        backgroundColor: 'white',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    },
    stageHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '6px 10px',
        backgroundColor: '#f8f8f8',
        borderBottom: '1px solid #e0e0e0',
        fontSize: '12px',
        fontWeight: 500,
    },
    flagButton: {
        padding: '4px 8px',
        border: '1px solid #4CAF50',
        borderRadius: '4px',
        backgroundColor: 'white',
        cursor: 'pointer',
        fontSize: '15px',
        marginRight: '4px',
    },
    stopButtonSmall: {
        padding: '4px 8px',
        border: '1px solid #f44336',
        borderRadius: '4px',
        backgroundColor: 'white',
        cursor: 'pointer',
        fontSize: '15px',
    },
    codeHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '8px 12px',
        borderBottom: '1px solid #eee',
        backgroundColor: '#f9f9f9',
        fontSize: '13px',
        fontWeight: 500,
        borderRadius: '8px 8px 0 0',
        flexShrink: 0,
    },
    uploadCodeBtn: {
        padding: '6px 12px',
        backgroundColor: '#4C97FF',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '11px',
        cursor: 'pointer'
    },
    codeArea: {
        flex: '1 1 auto',
        minHeight: '150px',
        overflow: 'auto',
        backgroundColor: '#fafafa',
        borderRadius: '0 0 8px 8px',
        borderBottom: '1px solid #eee',
        borderLeft: '1px solid #eee',
        borderRight: '1px solid #eee',
        borderTop: 'none',
        maxHeight: 'calc(50vh - 200px)',
    },
    codeContent: {
        margin: 0,
        padding: '12px',
        fontFamily: "'Consolas', 'Monaco', 'Courier New', monospace",
        fontSize: '12px',
        lineHeight: '1.6',
        color: '#333',
    },
    codeLine: { display: 'flex' },
    lineNumber: {
        width: '35px',
        paddingRight: '10px',
        textAlign: 'right',
        color: '#999',
        userSelect: 'none'
    },
    bottomTabs: {
        display: 'flex',
        borderTop: '1px solid #ddd',
        marginTop: 'auto',
        flexShrink: 0
    },
    bottomTab: {
        padding: '8px 16px',
        backgroundColor: '#f5f5f5',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: '2px solid transparent',
        fontSize: '12px',
        cursor: 'pointer',
        color: '#666'
    },
    bottomTabActive: {
        padding: '8px 16px',
        backgroundColor: '#ffffff',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: '2px solid #4C97FF',
        fontSize: '12px',
        cursor: 'pointer',
        color: '#4C97FF',
        fontWeight: 'bold'
    },
    logArea: {
        height: '180px',
        maxHeight: '180px',
        minHeight: '120px',
        overflow: 'auto',
        padding: '8px 12px',
        backgroundColor: '#fff',
        fontSize: '11px',
        fontFamily: 'monospace',
        borderRadius: '0 0 8px 8px',
        flexShrink: 0,
    },
    logLine: { color: '#666', marginBottom: '2px' },
    refreshButton: {
        padding: '4px 8px',
        backgroundColor: 'rgba(255,255,255,0.2)',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'pointer',
    },
    connectButton: {
        padding: '6px 12px',
        backgroundColor: 'rgba(255,255,255,0.2)',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'pointer',
    },
    connectedButton: {
        padding: '6px 12px',
        backgroundColor: '#4CAF50',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'pointer',
        fontWeight: 'bold',
    },
    uploadButtonDisabled: {
        padding: '6px 14px',
        backgroundColor: '#999',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '12px',
        cursor: 'not-allowed',
    },
    uploadStatus: {
        fontSize: '11px',
        color: '#4CAF50',
    },
    serialContainer: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    serialMessages: {
        flex: 1,
        overflow: 'auto',
        paddingBottom: '4px',
    },
    serialLine: {
        color: '#333',
        marginBottom: '1px',
        fontFamily: 'monospace',
        fontSize: '11px',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-all',
    },
    serialHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '4px 8px',
        borderTop: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderBottom: '1px solid #eee',
        backgroundColor: '#f9f9f9',
    },
    serialSelect: {
        padding: '2px 4px',
        fontSize: '10px',
        border: '1px solid #ddd',
        borderRadius: '3px',
        outline: 'none',
    },
    clearButton: {
        padding: '2px 6px',
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        fontSize: '12px',
        opacity: 0.7,
        transition: 'opacity 0.2s',
    },
    serialPlaceholder: {
        color: '#999',
        textAlign: 'center',
        padding: '12px',
        fontSize: '11px',
    },
    serialInputRow: {
        display: 'flex',
        gap: '4px',
        paddingTop: '4px',
        borderBottom: 'none',
        borderLeft: 'none',
        borderRight: 'none',
        borderTop: '1px solid #eee',
    },
    serialInput: {
        flex: 1,
        padding: '4px 8px',
        border: '1px solid #ddd',
        borderRadius: '4px',
        fontSize: '11px',
        fontFamily: 'monospace',
    },
    sendButton: {
        padding: '4px 12px',
        backgroundColor: '#4C97FF',
        border: 'none',
        borderRadius: '4px',
        color: 'white',
        fontSize: '11px',
        cursor: 'pointer',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        backdropFilter: 'blur(2px)',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: '8px',
        width: '400px',
        boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
        animation: 'popIn 0.2s ease-out',
    },
    modalTitle: {
        backgroundColor: '#855CD6',
        color: 'white',
        padding: '12px 16px',
        fontSize: '16px',
        fontWeight: 'bold',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modalInput: {
        padding: '12px',
        fontSize: '16px',
        borderRadius: '8px',
        border: '1px solid #ddd',
        width: '100%',
        fontFamily: 'inherit',
        outline: 'none',
        transition: 'border-color 0.2s',
    },
    modalButtons: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '12px',
    },
    modalCancel: {
        padding: '8px 16px',
        borderRadius: '6px',
        border: '1px solid #ddd',
        backgroundColor: 'white',
        cursor: 'pointer',
        fontSize: '14px',
        color: '#666',
    },
    modalSubmit: {
        padding: '8px 16px',
        borderRadius: '6px',
        border: 'none',
        backgroundColor: '#4C97FF',
        color: 'white',
        cursor: 'pointer',
        fontWeight: 'bold',
        fontSize: '14px',
    },
};
