import { app, BrowserWindow, ipcMain } from 'electron';
// Use __non_webpack_require__ to completely bypass webpack bundling
// This is a special webpack global that loads modules at runtime
declare const __non_webpack_require__: typeof require;
const { SerialPort } = __non_webpack_require__('serialport');
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { spawn, exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// ═══════════════════════════════════════════════════════════════════════════
// LOGGING UTILITY
// ═══════════════════════════════════════════════════════════════════════════
const log = (category: string, msg: string, data?: any) => {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] [MAIN:${category}] ${msg}`, data ?? '');
};

log('INIT', 'Main process starting...');
log('INIT', 'Electron version', process.versions.electron);
log('INIT', 'Node version', process.versions.node);
log('INIT', 'Chrome version', process.versions.chrome);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  log('INIT', 'Squirrel startup detected, quitting...');
  app.quit();
}

// ═══════════════════════════════════════════════════════════════════════════
// SERIAL PORT STATE
// ═══════════════════════════════════════════════════════════════════════════
let activePort: any = null;
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  log('WINDOW', 'Creating main window...');

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1400,
    minHeight: 600,
    minWidth: 1000,
    title: 'LeetBlocks - Block Programming IDE',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  log('WINDOW', 'Window created', {
    width: 1400,
    height: 800,
    title: 'LeetBlocks',
  });

  // and load the index.html of the app.
  log('WINDOW', 'Loading URL', MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development
  if (process.env.NODE_ENV === 'development') {
    log('DEVTOOLS', 'Opening DevTools');
    mainWindow.webContents.openDevTools();
  }

  // Window event listeners
  mainWindow.on('closed', () => {
    log('WINDOW', 'Window closed');
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  log('APP', 'App ready event fired');
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  log('APP', 'All windows closed');
  if (process.platform !== 'darwin') {
    log('APP', 'Quitting application (not macOS)');
    app.quit();
  }
});

app.on('activate', () => {
  log('APP', 'App activated');
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    log('APP', 'No windows open, creating new window');
    createWindow();
  }
});

app.on('before-quit', () => {
  // Clean up serial port
  if (activePort && activePort.isOpen) {
    log('APP', 'Closing serial port before quit');
    activePort.close();
  }
});

// ═══════════════════════════════════════════════════════════════════════════
// IPC HANDLERS - Serial Port Operations
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Get list of available serial ports
 */
ipcMain.handle('get-ports', async () => {
  log('IPC', 'get-ports requested');
  try {
    const ports = await SerialPort.list();
    log('IPC', 'Found ports', ports.length);
    return ports.map((p: any) => ({
      path: p.path,
      manufacturer: p.manufacturer,
      productId: p.productId,
    }));
  } catch (error) {
    log('IPC', 'Error listing ports', error);
    return [];
  }
});

/**
 * Connect to a serial port
 */
ipcMain.handle('connect-port', async (event, portPath: string, baudRate: number) => {
  log('IPC', 'connect-port requested', { portPath, baudRate });

  // Close existing connection if any
  if (activePort && activePort.isOpen) {
    log('IPC', 'Closing existing port');
    activePort.close();
  }

  try {
    activePort = new SerialPort({
      path: portPath,
      baudRate: baudRate,
    });

    // Set up data listener
    activePort.on('data', (data: Buffer) => {
      const message = data.toString();
      log('SERIAL', 'Data received', message);
      if (mainWindow) {
        mainWindow.webContents.send('serial-data', message);
      }
    });

    activePort.on('error', (err: Error) => {
      log('SERIAL', 'Port error', err.message);
      if (mainWindow) {
        mainWindow.webContents.send('connection-change', false);
      }
    });

    activePort.on('close', () => {
      log('SERIAL', 'Port closed');
      if (mainWindow) {
        mainWindow.webContents.send('connection-change', false);
      }
    });

    // Wait for port to open
    await new Promise<void>((resolve, reject) => {
      activePort!.on('open', () => {
        log('SERIAL', 'Port opened successfully');
        resolve();
      });
      activePort!.on('error', reject);
    });

    if (mainWindow) {
      mainWindow.webContents.send('connection-change', true);
    }

    return { success: true };
  } catch (error) {
    log('IPC', 'Error connecting to port', error);
    return { success: false, error: (error as Error).message };
  }
});

/**
 * Disconnect from current port
 */
ipcMain.handle('disconnect-port', async () => {
  log('IPC', 'disconnect-port requested');

  if (activePort && activePort.isOpen) {
    try {
      activePort.close();
      activePort = null;
      if (mainWindow) {
        mainWindow.webContents.send('connection-change', false);
      }
      return { success: true };
    } catch (error) {
      log('IPC', 'Error disconnecting', error);
      return { success: false, error: (error as Error).message };
    }
  }

  return { success: true };
});

/**
 * Send data to connected port
 */
ipcMain.handle('send-serial', async (event, data: string) => {
  log('IPC', 'send-serial requested', { dataLength: data.length });

  if (!activePort || !activePort.isOpen) {
    log('IPC', 'No port connected');
    return;
  }

  try {
    activePort.write(data);
    log('SERIAL', 'Data sent', data);
  } catch (error) {
    log('SERIAL', 'Error sending data', error);
  }
});

/**
 * Upload code to connected board
 * Uses arduino-cli for compilation and upload if available
 */
ipcMain.handle('upload-code', async (event, code: string, selectedPort?: string) => {
  log('IPC', 'upload-code requested', { codeLength: code.length, selectedPort });

  const sendProgress = (progress: number, message: string) => {
    log('IPC', `Upload progress: ${progress}% - ${message}`);
    if (mainWindow) {
      mainWindow.webContents.send('upload-progress', progress, message);
    }
  };

  try {
    // Step 1: Check for arduino-cli
    sendProgress(5, 'Checking for arduino-cli...');
    let arduinoCliPath = 'arduino-cli';

    try {
      await execAsync('arduino-cli version');
      log('IPC', 'arduino-cli found in PATH');
    } catch {
      // Try common installation locations on Windows
      const possiblePaths = [
        path.join(os.homedir(), 'AppData', 'Local', 'Arduino15', 'arduino-cli.exe'),
        'C:\\Program Files\\Arduino CLI\\arduino-cli.exe',
        'C:\\arduino-cli\\arduino-cli.exe',
      ];

      let found = false;
      for (const p of possiblePaths) {
        if (fs.existsSync(p)) {
          arduinoCliPath = p;
          found = true;
          log('IPC', 'arduino-cli found at', p);
          break;
        }
      }

      if (!found) {
        // arduino-cli not found - save file and return instructions
        sendProgress(100, 'arduino-cli not found');

        const tempDir = os.tmpdir();
        const sketchDir = path.join(tempDir, 'leapblocks_sketch');
        const sketchFile = path.join(sketchDir, 'leapblocks_sketch.ino');

        if (!fs.existsSync(sketchDir)) {
          fs.mkdirSync(sketchDir, { recursive: true });
        }
        fs.writeFileSync(sketchFile, code, 'utf-8');

        return {
          success: false,
          error: 'arduino-cli not found. Please install it from https://arduino.cc/pro/cli',
          output: `Sketch saved to: ${sketchFile}\n\nTo install arduino-cli:\n1. Download from https://arduino.cc/pro/cli\n2. Extract and add to PATH\n3. Run: arduino-cli core install arduino:avr`,
        };
      }
    }

    // Step 2: Save sketch to temp file
    sendProgress(15, 'Saving sketch...');
    const tempDir = os.tmpdir();
    const sketchDir = path.join(tempDir, 'leapblocks_sketch');
    const sketchFile = path.join(sketchDir, 'leapblocks_sketch.ino');

    if (!fs.existsSync(sketchDir)) {
      fs.mkdirSync(sketchDir, { recursive: true });
    }
    fs.writeFileSync(sketchFile, code, 'utf-8');
    log('IPC', 'Sketch saved', sketchFile);

    // Step 3: Detect connected board
    sendProgress(25, 'Detecting board...');
    let fqbn = 'arduino:avr:uno'; // Default to Uno

    try {
      const { stdout } = await execAsync(`"${arduinoCliPath}" board list --format json`);
      const boards = JSON.parse(stdout);
      if (boards.detected_ports && boards.detected_ports.length > 0) {
        const port = boards.detected_ports.find((p: any) =>
          p.port?.address === selectedPort || p.port?.address === activePort?.path
        );
        if (port?.matching_boards?.[0]?.fqbn) {
          fqbn = port.matching_boards[0].fqbn;
          log('IPC', 'Detected board FQBN', fqbn);
        }
      }
    } catch (e) {
      log('IPC', 'Board detection failed, using default Uno', e);
    }

    // Determine upload port
    const uploadPort = selectedPort || (activePort?.path);
    if (!uploadPort) {
      return {
        success: false,
        error: 'No port selected. Please connect to a serial port first.',
      };
    }

    // Close serial connection before upload
    if (activePort && activePort.isOpen) {
      log('IPC', 'Closing serial port for upload');
      activePort.close();
      activePort = null;
    }

    // Step 4: Compile
    sendProgress(40, 'Compiling...');
    try {
      const { stdout: compileOut, stderr: compileErr } = await execAsync(
        `"${arduinoCliPath}" compile --fqbn ${fqbn} "${sketchDir}"`,
        { timeout: 120000 }
      );
      log('IPC', 'Compile output', compileOut);
      if (compileErr) log('IPC', 'Compile stderr', compileErr);
    } catch (compileError: any) {
      log('IPC', 'Compile error', compileError);
      return {
        success: false,
        error: `Compilation failed: ${compileError.stderr || compileError.message}`,
      };
    }

    // Step 5: Upload
    sendProgress(70, 'Uploading to board...');
    try {
      const { stdout: uploadOut, stderr: uploadErr } = await execAsync(
        `"${arduinoCliPath}" upload -p "${uploadPort}" --fqbn ${fqbn} "${sketchDir}"`,
        { timeout: 120000 }
      );
      log('IPC', 'Upload output', uploadOut);
      if (uploadErr) log('IPC', 'Upload stderr', uploadErr);
    } catch (uploadError: any) {
      log('IPC', 'Upload error', uploadError);
      return {
        success: false,
        error: `Upload failed: ${uploadError.stderr || uploadError.message}`,
      };
    }

    sendProgress(100, 'Upload complete!');
    return {
      success: true,
      output: `Successfully compiled and uploaded to ${uploadPort}`,
    };

  } catch (error) {
    log('IPC', 'Error in upload-code', error);
    return { success: false, error: (error as Error).message };
  }
});

log('INIT', 'Main process initialization complete');
